// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/certificate_issuer.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CertificateIssuerServiceName is the fully-qualified name of the CertificateIssuerService service.
	CertificateIssuerServiceName = "neoline.v1.CertificateIssuerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CertificateIssuerServiceListCertificateIssuersProcedure is the fully-qualified name of the
	// CertificateIssuerService's ListCertificateIssuers RPC.
	CertificateIssuerServiceListCertificateIssuersProcedure = "/neoline.v1.CertificateIssuerService/ListCertificateIssuers"
	// CertificateIssuerServiceGetCertificateIssuerDirectoryPreviewProcedure is the fully-qualified name
	// of the CertificateIssuerService's GetCertificateIssuerDirectoryPreview RPC.
	CertificateIssuerServiceGetCertificateIssuerDirectoryPreviewProcedure = "/neoline.v1.CertificateIssuerService/GetCertificateIssuerDirectoryPreview"
	// CertificateIssuerServiceCreateCertificateIssuerProcedure is the fully-qualified name of the
	// CertificateIssuerService's CreateCertificateIssuer RPC.
	CertificateIssuerServiceCreateCertificateIssuerProcedure = "/neoline.v1.CertificateIssuerService/CreateCertificateIssuer"
	// CertificateIssuerServiceGetCertificateIssuerProcedure is the fully-qualified name of the
	// CertificateIssuerService's GetCertificateIssuer RPC.
	CertificateIssuerServiceGetCertificateIssuerProcedure = "/neoline.v1.CertificateIssuerService/GetCertificateIssuer"
	// CertificateIssuerServiceUpdateCertificateIssuerProcedure is the fully-qualified name of the
	// CertificateIssuerService's UpdateCertificateIssuer RPC.
	CertificateIssuerServiceUpdateCertificateIssuerProcedure = "/neoline.v1.CertificateIssuerService/UpdateCertificateIssuer"
	// CertificateIssuerServiceDeleteCertificateIssuerProcedure is the fully-qualified name of the
	// CertificateIssuerService's DeleteCertificateIssuer RPC.
	CertificateIssuerServiceDeleteCertificateIssuerProcedure = "/neoline.v1.CertificateIssuerService/DeleteCertificateIssuer"
	// CertificateIssuerServiceRetryCertificateIssuerRegistrationProcedure is the fully-qualified name
	// of the CertificateIssuerService's RetryCertificateIssuerRegistration RPC.
	CertificateIssuerServiceRetryCertificateIssuerRegistrationProcedure = "/neoline.v1.CertificateIssuerService/RetryCertificateIssuerRegistration"
)

// CertificateIssuerServiceClient is a client for the neoline.v1.CertificateIssuerService service.
type CertificateIssuerServiceClient interface {
	ListCertificateIssuers(context.Context, *connect.Request[v1.ListCertificateIssuersRequest]) (*connect.Response[v1.ListCertificateIssuersResponse], error)
	GetCertificateIssuerDirectoryPreview(context.Context, *connect.Request[v1.GetCertificateIssuerDirectoryPreviewRequest]) (*connect.Response[v1.GetCertificateIssuerDirectoryPreviewResponse], error)
	CreateCertificateIssuer(context.Context, *connect.Request[v1.CreateCertificateIssuerRequest]) (*connect.Response[v1.CreateCertificateIssuerResponse], error)
	GetCertificateIssuer(context.Context, *connect.Request[v1.GetCertificateIssuerRequest]) (*connect.Response[v1.GetCertificateIssuerResponse], error)
	UpdateCertificateIssuer(context.Context, *connect.Request[v1.UpdateCertificateIssuerRequest]) (*connect.Response[v1.UpdateCertificateIssuerResponse], error)
	DeleteCertificateIssuer(context.Context, *connect.Request[v1.DeleteCertificateIssuerRequest]) (*connect.Response[v1.DeleteCertificateIssuerResponse], error)
	RetryCertificateIssuerRegistration(context.Context, *connect.Request[v1.RetryCertificateIssuerRegistrationRequest]) (*connect.Response[v1.RetryCertificateIssuerRegistrationResponse], error)
}

// NewCertificateIssuerServiceClient constructs a client for the neoline.v1.CertificateIssuerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCertificateIssuerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CertificateIssuerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	certificateIssuerServiceMethods := v1.File_neoline_v1_certificate_issuer_proto.Services().ByName("CertificateIssuerService").Methods()
	return &certificateIssuerServiceClient{
		listCertificateIssuers: connect.NewClient[v1.ListCertificateIssuersRequest, v1.ListCertificateIssuersResponse](
			httpClient,
			baseURL+CertificateIssuerServiceListCertificateIssuersProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("ListCertificateIssuers")),
			connect.WithClientOptions(opts...),
		),
		getCertificateIssuerDirectoryPreview: connect.NewClient[v1.GetCertificateIssuerDirectoryPreviewRequest, v1.GetCertificateIssuerDirectoryPreviewResponse](
			httpClient,
			baseURL+CertificateIssuerServiceGetCertificateIssuerDirectoryPreviewProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("GetCertificateIssuerDirectoryPreview")),
			connect.WithClientOptions(opts...),
		),
		createCertificateIssuer: connect.NewClient[v1.CreateCertificateIssuerRequest, v1.CreateCertificateIssuerResponse](
			httpClient,
			baseURL+CertificateIssuerServiceCreateCertificateIssuerProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("CreateCertificateIssuer")),
			connect.WithClientOptions(opts...),
		),
		getCertificateIssuer: connect.NewClient[v1.GetCertificateIssuerRequest, v1.GetCertificateIssuerResponse](
			httpClient,
			baseURL+CertificateIssuerServiceGetCertificateIssuerProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("GetCertificateIssuer")),
			connect.WithClientOptions(opts...),
		),
		updateCertificateIssuer: connect.NewClient[v1.UpdateCertificateIssuerRequest, v1.UpdateCertificateIssuerResponse](
			httpClient,
			baseURL+CertificateIssuerServiceUpdateCertificateIssuerProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("UpdateCertificateIssuer")),
			connect.WithClientOptions(opts...),
		),
		deleteCertificateIssuer: connect.NewClient[v1.DeleteCertificateIssuerRequest, v1.DeleteCertificateIssuerResponse](
			httpClient,
			baseURL+CertificateIssuerServiceDeleteCertificateIssuerProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("DeleteCertificateIssuer")),
			connect.WithClientOptions(opts...),
		),
		retryCertificateIssuerRegistration: connect.NewClient[v1.RetryCertificateIssuerRegistrationRequest, v1.RetryCertificateIssuerRegistrationResponse](
			httpClient,
			baseURL+CertificateIssuerServiceRetryCertificateIssuerRegistrationProcedure,
			connect.WithSchema(certificateIssuerServiceMethods.ByName("RetryCertificateIssuerRegistration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// certificateIssuerServiceClient implements CertificateIssuerServiceClient.
type certificateIssuerServiceClient struct {
	listCertificateIssuers               *connect.Client[v1.ListCertificateIssuersRequest, v1.ListCertificateIssuersResponse]
	getCertificateIssuerDirectoryPreview *connect.Client[v1.GetCertificateIssuerDirectoryPreviewRequest, v1.GetCertificateIssuerDirectoryPreviewResponse]
	createCertificateIssuer              *connect.Client[v1.CreateCertificateIssuerRequest, v1.CreateCertificateIssuerResponse]
	getCertificateIssuer                 *connect.Client[v1.GetCertificateIssuerRequest, v1.GetCertificateIssuerResponse]
	updateCertificateIssuer              *connect.Client[v1.UpdateCertificateIssuerRequest, v1.UpdateCertificateIssuerResponse]
	deleteCertificateIssuer              *connect.Client[v1.DeleteCertificateIssuerRequest, v1.DeleteCertificateIssuerResponse]
	retryCertificateIssuerRegistration   *connect.Client[v1.RetryCertificateIssuerRegistrationRequest, v1.RetryCertificateIssuerRegistrationResponse]
}

// ListCertificateIssuers calls neoline.v1.CertificateIssuerService.ListCertificateIssuers.
func (c *certificateIssuerServiceClient) ListCertificateIssuers(ctx context.Context, req *connect.Request[v1.ListCertificateIssuersRequest]) (*connect.Response[v1.ListCertificateIssuersResponse], error) {
	return c.listCertificateIssuers.CallUnary(ctx, req)
}

// GetCertificateIssuerDirectoryPreview calls
// neoline.v1.CertificateIssuerService.GetCertificateIssuerDirectoryPreview.
func (c *certificateIssuerServiceClient) GetCertificateIssuerDirectoryPreview(ctx context.Context, req *connect.Request[v1.GetCertificateIssuerDirectoryPreviewRequest]) (*connect.Response[v1.GetCertificateIssuerDirectoryPreviewResponse], error) {
	return c.getCertificateIssuerDirectoryPreview.CallUnary(ctx, req)
}

// CreateCertificateIssuer calls neoline.v1.CertificateIssuerService.CreateCertificateIssuer.
func (c *certificateIssuerServiceClient) CreateCertificateIssuer(ctx context.Context, req *connect.Request[v1.CreateCertificateIssuerRequest]) (*connect.Response[v1.CreateCertificateIssuerResponse], error) {
	return c.createCertificateIssuer.CallUnary(ctx, req)
}

// GetCertificateIssuer calls neoline.v1.CertificateIssuerService.GetCertificateIssuer.
func (c *certificateIssuerServiceClient) GetCertificateIssuer(ctx context.Context, req *connect.Request[v1.GetCertificateIssuerRequest]) (*connect.Response[v1.GetCertificateIssuerResponse], error) {
	return c.getCertificateIssuer.CallUnary(ctx, req)
}

// UpdateCertificateIssuer calls neoline.v1.CertificateIssuerService.UpdateCertificateIssuer.
func (c *certificateIssuerServiceClient) UpdateCertificateIssuer(ctx context.Context, req *connect.Request[v1.UpdateCertificateIssuerRequest]) (*connect.Response[v1.UpdateCertificateIssuerResponse], error) {
	return c.updateCertificateIssuer.CallUnary(ctx, req)
}

// DeleteCertificateIssuer calls neoline.v1.CertificateIssuerService.DeleteCertificateIssuer.
func (c *certificateIssuerServiceClient) DeleteCertificateIssuer(ctx context.Context, req *connect.Request[v1.DeleteCertificateIssuerRequest]) (*connect.Response[v1.DeleteCertificateIssuerResponse], error) {
	return c.deleteCertificateIssuer.CallUnary(ctx, req)
}

// RetryCertificateIssuerRegistration calls
// neoline.v1.CertificateIssuerService.RetryCertificateIssuerRegistration.
func (c *certificateIssuerServiceClient) RetryCertificateIssuerRegistration(ctx context.Context, req *connect.Request[v1.RetryCertificateIssuerRegistrationRequest]) (*connect.Response[v1.RetryCertificateIssuerRegistrationResponse], error) {
	return c.retryCertificateIssuerRegistration.CallUnary(ctx, req)
}

// CertificateIssuerServiceHandler is an implementation of the neoline.v1.CertificateIssuerService
// service.
type CertificateIssuerServiceHandler interface {
	ListCertificateIssuers(context.Context, *connect.Request[v1.ListCertificateIssuersRequest]) (*connect.Response[v1.ListCertificateIssuersResponse], error)
	GetCertificateIssuerDirectoryPreview(context.Context, *connect.Request[v1.GetCertificateIssuerDirectoryPreviewRequest]) (*connect.Response[v1.GetCertificateIssuerDirectoryPreviewResponse], error)
	CreateCertificateIssuer(context.Context, *connect.Request[v1.CreateCertificateIssuerRequest]) (*connect.Response[v1.CreateCertificateIssuerResponse], error)
	GetCertificateIssuer(context.Context, *connect.Request[v1.GetCertificateIssuerRequest]) (*connect.Response[v1.GetCertificateIssuerResponse], error)
	UpdateCertificateIssuer(context.Context, *connect.Request[v1.UpdateCertificateIssuerRequest]) (*connect.Response[v1.UpdateCertificateIssuerResponse], error)
	DeleteCertificateIssuer(context.Context, *connect.Request[v1.DeleteCertificateIssuerRequest]) (*connect.Response[v1.DeleteCertificateIssuerResponse], error)
	RetryCertificateIssuerRegistration(context.Context, *connect.Request[v1.RetryCertificateIssuerRegistrationRequest]) (*connect.Response[v1.RetryCertificateIssuerRegistrationResponse], error)
}

// NewCertificateIssuerServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCertificateIssuerServiceHandler(svc CertificateIssuerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	certificateIssuerServiceMethods := v1.File_neoline_v1_certificate_issuer_proto.Services().ByName("CertificateIssuerService").Methods()
	certificateIssuerServiceListCertificateIssuersHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceListCertificateIssuersProcedure,
		svc.ListCertificateIssuers,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("ListCertificateIssuers")),
		connect.WithHandlerOptions(opts...),
	)
	certificateIssuerServiceGetCertificateIssuerDirectoryPreviewHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceGetCertificateIssuerDirectoryPreviewProcedure,
		svc.GetCertificateIssuerDirectoryPreview,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("GetCertificateIssuerDirectoryPreview")),
		connect.WithHandlerOptions(opts...),
	)
	certificateIssuerServiceCreateCertificateIssuerHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceCreateCertificateIssuerProcedure,
		svc.CreateCertificateIssuer,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("CreateCertificateIssuer")),
		connect.WithHandlerOptions(opts...),
	)
	certificateIssuerServiceGetCertificateIssuerHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceGetCertificateIssuerProcedure,
		svc.GetCertificateIssuer,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("GetCertificateIssuer")),
		connect.WithHandlerOptions(opts...),
	)
	certificateIssuerServiceUpdateCertificateIssuerHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceUpdateCertificateIssuerProcedure,
		svc.UpdateCertificateIssuer,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("UpdateCertificateIssuer")),
		connect.WithHandlerOptions(opts...),
	)
	certificateIssuerServiceDeleteCertificateIssuerHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceDeleteCertificateIssuerProcedure,
		svc.DeleteCertificateIssuer,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("DeleteCertificateIssuer")),
		connect.WithHandlerOptions(opts...),
	)
	certificateIssuerServiceRetryCertificateIssuerRegistrationHandler := connect.NewUnaryHandler(
		CertificateIssuerServiceRetryCertificateIssuerRegistrationProcedure,
		svc.RetryCertificateIssuerRegistration,
		connect.WithSchema(certificateIssuerServiceMethods.ByName("RetryCertificateIssuerRegistration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.CertificateIssuerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CertificateIssuerServiceListCertificateIssuersProcedure:
			certificateIssuerServiceListCertificateIssuersHandler.ServeHTTP(w, r)
		case CertificateIssuerServiceGetCertificateIssuerDirectoryPreviewProcedure:
			certificateIssuerServiceGetCertificateIssuerDirectoryPreviewHandler.ServeHTTP(w, r)
		case CertificateIssuerServiceCreateCertificateIssuerProcedure:
			certificateIssuerServiceCreateCertificateIssuerHandler.ServeHTTP(w, r)
		case CertificateIssuerServiceGetCertificateIssuerProcedure:
			certificateIssuerServiceGetCertificateIssuerHandler.ServeHTTP(w, r)
		case CertificateIssuerServiceUpdateCertificateIssuerProcedure:
			certificateIssuerServiceUpdateCertificateIssuerHandler.ServeHTTP(w, r)
		case CertificateIssuerServiceDeleteCertificateIssuerProcedure:
			certificateIssuerServiceDeleteCertificateIssuerHandler.ServeHTTP(w, r)
		case CertificateIssuerServiceRetryCertificateIssuerRegistrationProcedure:
			certificateIssuerServiceRetryCertificateIssuerRegistrationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCertificateIssuerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCertificateIssuerServiceHandler struct{}

func (UnimplementedCertificateIssuerServiceHandler) ListCertificateIssuers(context.Context, *connect.Request[v1.ListCertificateIssuersRequest]) (*connect.Response[v1.ListCertificateIssuersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.ListCertificateIssuers is not implemented"))
}

func (UnimplementedCertificateIssuerServiceHandler) GetCertificateIssuerDirectoryPreview(context.Context, *connect.Request[v1.GetCertificateIssuerDirectoryPreviewRequest]) (*connect.Response[v1.GetCertificateIssuerDirectoryPreviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.GetCertificateIssuerDirectoryPreview is not implemented"))
}

func (UnimplementedCertificateIssuerServiceHandler) CreateCertificateIssuer(context.Context, *connect.Request[v1.CreateCertificateIssuerRequest]) (*connect.Response[v1.CreateCertificateIssuerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.CreateCertificateIssuer is not implemented"))
}

func (UnimplementedCertificateIssuerServiceHandler) GetCertificateIssuer(context.Context, *connect.Request[v1.GetCertificateIssuerRequest]) (*connect.Response[v1.GetCertificateIssuerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.GetCertificateIssuer is not implemented"))
}

func (UnimplementedCertificateIssuerServiceHandler) UpdateCertificateIssuer(context.Context, *connect.Request[v1.UpdateCertificateIssuerRequest]) (*connect.Response[v1.UpdateCertificateIssuerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.UpdateCertificateIssuer is not implemented"))
}

func (UnimplementedCertificateIssuerServiceHandler) DeleteCertificateIssuer(context.Context, *connect.Request[v1.DeleteCertificateIssuerRequest]) (*connect.Response[v1.DeleteCertificateIssuerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.DeleteCertificateIssuer is not implemented"))
}

func (UnimplementedCertificateIssuerServiceHandler) RetryCertificateIssuerRegistration(context.Context, *connect.Request[v1.RetryCertificateIssuerRegistrationRequest]) (*connect.Response[v1.RetryCertificateIssuerRegistrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateIssuerService.RetryCertificateIssuerRegistration is not implemented"))
}
