// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/certificate_access_token.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CertificateAccessTokenServiceName is the fully-qualified name of the
	// CertificateAccessTokenService service.
	CertificateAccessTokenServiceName = "neoline.v1.CertificateAccessTokenService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CertificateAccessTokenServiceListCertificateAccessTokensProcedure is the fully-qualified name of
	// the CertificateAccessTokenService's ListCertificateAccessTokens RPC.
	CertificateAccessTokenServiceListCertificateAccessTokensProcedure = "/neoline.v1.CertificateAccessTokenService/ListCertificateAccessTokens"
	// CertificateAccessTokenServiceCreateCertificateAccessTokenProcedure is the fully-qualified name of
	// the CertificateAccessTokenService's CreateCertificateAccessToken RPC.
	CertificateAccessTokenServiceCreateCertificateAccessTokenProcedure = "/neoline.v1.CertificateAccessTokenService/CreateCertificateAccessToken"
	// CertificateAccessTokenServiceDeleteCertificateAccessTokenProcedure is the fully-qualified name of
	// the CertificateAccessTokenService's DeleteCertificateAccessToken RPC.
	CertificateAccessTokenServiceDeleteCertificateAccessTokenProcedure = "/neoline.v1.CertificateAccessTokenService/DeleteCertificateAccessToken"
)

// CertificateAccessTokenServiceClient is a client for the neoline.v1.CertificateAccessTokenService
// service.
type CertificateAccessTokenServiceClient interface {
	ListCertificateAccessTokens(context.Context, *connect.Request[v1.ListCertificateAccessTokensRequest]) (*connect.Response[v1.ListCertificateAccessTokensResponse], error)
	CreateCertificateAccessToken(context.Context, *connect.Request[v1.CreateCertificateAccessTokenRequest]) (*connect.Response[v1.CreateCertificateAccessTokenResponse], error)
	DeleteCertificateAccessToken(context.Context, *connect.Request[v1.DeleteCertificateAccessTokenRequest]) (*connect.Response[v1.DeleteCertificateAccessTokenResponse], error)
}

// NewCertificateAccessTokenServiceClient constructs a client for the
// neoline.v1.CertificateAccessTokenService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCertificateAccessTokenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CertificateAccessTokenServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	certificateAccessTokenServiceMethods := v1.File_neoline_v1_certificate_access_token_proto.Services().ByName("CertificateAccessTokenService").Methods()
	return &certificateAccessTokenServiceClient{
		listCertificateAccessTokens: connect.NewClient[v1.ListCertificateAccessTokensRequest, v1.ListCertificateAccessTokensResponse](
			httpClient,
			baseURL+CertificateAccessTokenServiceListCertificateAccessTokensProcedure,
			connect.WithSchema(certificateAccessTokenServiceMethods.ByName("ListCertificateAccessTokens")),
			connect.WithClientOptions(opts...),
		),
		createCertificateAccessToken: connect.NewClient[v1.CreateCertificateAccessTokenRequest, v1.CreateCertificateAccessTokenResponse](
			httpClient,
			baseURL+CertificateAccessTokenServiceCreateCertificateAccessTokenProcedure,
			connect.WithSchema(certificateAccessTokenServiceMethods.ByName("CreateCertificateAccessToken")),
			connect.WithClientOptions(opts...),
		),
		deleteCertificateAccessToken: connect.NewClient[v1.DeleteCertificateAccessTokenRequest, v1.DeleteCertificateAccessTokenResponse](
			httpClient,
			baseURL+CertificateAccessTokenServiceDeleteCertificateAccessTokenProcedure,
			connect.WithSchema(certificateAccessTokenServiceMethods.ByName("DeleteCertificateAccessToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// certificateAccessTokenServiceClient implements CertificateAccessTokenServiceClient.
type certificateAccessTokenServiceClient struct {
	listCertificateAccessTokens  *connect.Client[v1.ListCertificateAccessTokensRequest, v1.ListCertificateAccessTokensResponse]
	createCertificateAccessToken *connect.Client[v1.CreateCertificateAccessTokenRequest, v1.CreateCertificateAccessTokenResponse]
	deleteCertificateAccessToken *connect.Client[v1.DeleteCertificateAccessTokenRequest, v1.DeleteCertificateAccessTokenResponse]
}

// ListCertificateAccessTokens calls
// neoline.v1.CertificateAccessTokenService.ListCertificateAccessTokens.
func (c *certificateAccessTokenServiceClient) ListCertificateAccessTokens(ctx context.Context, req *connect.Request[v1.ListCertificateAccessTokensRequest]) (*connect.Response[v1.ListCertificateAccessTokensResponse], error) {
	return c.listCertificateAccessTokens.CallUnary(ctx, req)
}

// CreateCertificateAccessToken calls
// neoline.v1.CertificateAccessTokenService.CreateCertificateAccessToken.
func (c *certificateAccessTokenServiceClient) CreateCertificateAccessToken(ctx context.Context, req *connect.Request[v1.CreateCertificateAccessTokenRequest]) (*connect.Response[v1.CreateCertificateAccessTokenResponse], error) {
	return c.createCertificateAccessToken.CallUnary(ctx, req)
}

// DeleteCertificateAccessToken calls
// neoline.v1.CertificateAccessTokenService.DeleteCertificateAccessToken.
func (c *certificateAccessTokenServiceClient) DeleteCertificateAccessToken(ctx context.Context, req *connect.Request[v1.DeleteCertificateAccessTokenRequest]) (*connect.Response[v1.DeleteCertificateAccessTokenResponse], error) {
	return c.deleteCertificateAccessToken.CallUnary(ctx, req)
}

// CertificateAccessTokenServiceHandler is an implementation of the
// neoline.v1.CertificateAccessTokenService service.
type CertificateAccessTokenServiceHandler interface {
	ListCertificateAccessTokens(context.Context, *connect.Request[v1.ListCertificateAccessTokensRequest]) (*connect.Response[v1.ListCertificateAccessTokensResponse], error)
	CreateCertificateAccessToken(context.Context, *connect.Request[v1.CreateCertificateAccessTokenRequest]) (*connect.Response[v1.CreateCertificateAccessTokenResponse], error)
	DeleteCertificateAccessToken(context.Context, *connect.Request[v1.DeleteCertificateAccessTokenRequest]) (*connect.Response[v1.DeleteCertificateAccessTokenResponse], error)
}

// NewCertificateAccessTokenServiceHandler builds an HTTP handler from the service implementation.
// It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCertificateAccessTokenServiceHandler(svc CertificateAccessTokenServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	certificateAccessTokenServiceMethods := v1.File_neoline_v1_certificate_access_token_proto.Services().ByName("CertificateAccessTokenService").Methods()
	certificateAccessTokenServiceListCertificateAccessTokensHandler := connect.NewUnaryHandler(
		CertificateAccessTokenServiceListCertificateAccessTokensProcedure,
		svc.ListCertificateAccessTokens,
		connect.WithSchema(certificateAccessTokenServiceMethods.ByName("ListCertificateAccessTokens")),
		connect.WithHandlerOptions(opts...),
	)
	certificateAccessTokenServiceCreateCertificateAccessTokenHandler := connect.NewUnaryHandler(
		CertificateAccessTokenServiceCreateCertificateAccessTokenProcedure,
		svc.CreateCertificateAccessToken,
		connect.WithSchema(certificateAccessTokenServiceMethods.ByName("CreateCertificateAccessToken")),
		connect.WithHandlerOptions(opts...),
	)
	certificateAccessTokenServiceDeleteCertificateAccessTokenHandler := connect.NewUnaryHandler(
		CertificateAccessTokenServiceDeleteCertificateAccessTokenProcedure,
		svc.DeleteCertificateAccessToken,
		connect.WithSchema(certificateAccessTokenServiceMethods.ByName("DeleteCertificateAccessToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.CertificateAccessTokenService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CertificateAccessTokenServiceListCertificateAccessTokensProcedure:
			certificateAccessTokenServiceListCertificateAccessTokensHandler.ServeHTTP(w, r)
		case CertificateAccessTokenServiceCreateCertificateAccessTokenProcedure:
			certificateAccessTokenServiceCreateCertificateAccessTokenHandler.ServeHTTP(w, r)
		case CertificateAccessTokenServiceDeleteCertificateAccessTokenProcedure:
			certificateAccessTokenServiceDeleteCertificateAccessTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCertificateAccessTokenServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCertificateAccessTokenServiceHandler struct{}

func (UnimplementedCertificateAccessTokenServiceHandler) ListCertificateAccessTokens(context.Context, *connect.Request[v1.ListCertificateAccessTokensRequest]) (*connect.Response[v1.ListCertificateAccessTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateAccessTokenService.ListCertificateAccessTokens is not implemented"))
}

func (UnimplementedCertificateAccessTokenServiceHandler) CreateCertificateAccessToken(context.Context, *connect.Request[v1.CreateCertificateAccessTokenRequest]) (*connect.Response[v1.CreateCertificateAccessTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateAccessTokenService.CreateCertificateAccessToken is not implemented"))
}

func (UnimplementedCertificateAccessTokenServiceHandler) DeleteCertificateAccessToken(context.Context, *connect.Request[v1.DeleteCertificateAccessTokenRequest]) (*connect.Response[v1.DeleteCertificateAccessTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.CertificateAccessTokenService.DeleteCertificateAccessToken is not implemented"))
}
