// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/mcp_token.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// McpTokenServiceName is the fully-qualified name of the McpTokenService service.
	McpTokenServiceName = "neoline.v1.McpTokenService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// McpTokenServiceListMcpTokensProcedure is the fully-qualified name of the McpTokenService's
	// ListMcpTokens RPC.
	McpTokenServiceListMcpTokensProcedure = "/neoline.v1.McpTokenService/ListMcpTokens"
	// McpTokenServiceCreateMcpTokenProcedure is the fully-qualified name of the McpTokenService's
	// CreateMcpToken RPC.
	McpTokenServiceCreateMcpTokenProcedure = "/neoline.v1.McpTokenService/CreateMcpToken"
	// McpTokenServiceDeleteMcpTokenProcedure is the fully-qualified name of the McpTokenService's
	// DeleteMcpToken RPC.
	McpTokenServiceDeleteMcpTokenProcedure = "/neoline.v1.McpTokenService/DeleteMcpToken"
)

// McpTokenServiceClient is a client for the neoline.v1.McpTokenService service.
type McpTokenServiceClient interface {
	ListMcpTokens(context.Context, *connect.Request[v1.ListMcpTokensRequest]) (*connect.Response[v1.ListMcpTokensResponse], error)
	CreateMcpToken(context.Context, *connect.Request[v1.CreateMcpTokenRequest]) (*connect.Response[v1.CreateMcpTokenResponse], error)
	DeleteMcpToken(context.Context, *connect.Request[v1.DeleteMcpTokenRequest]) (*connect.Response[v1.DeleteMcpTokenResponse], error)
}

// NewMcpTokenServiceClient constructs a client for the neoline.v1.McpTokenService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMcpTokenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) McpTokenServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mcpTokenServiceMethods := v1.File_neoline_v1_mcp_token_proto.Services().ByName("McpTokenService").Methods()
	return &mcpTokenServiceClient{
		listMcpTokens: connect.NewClient[v1.ListMcpTokensRequest, v1.ListMcpTokensResponse](
			httpClient,
			baseURL+McpTokenServiceListMcpTokensProcedure,
			connect.WithSchema(mcpTokenServiceMethods.ByName("ListMcpTokens")),
			connect.WithClientOptions(opts...),
		),
		createMcpToken: connect.NewClient[v1.CreateMcpTokenRequest, v1.CreateMcpTokenResponse](
			httpClient,
			baseURL+McpTokenServiceCreateMcpTokenProcedure,
			connect.WithSchema(mcpTokenServiceMethods.ByName("CreateMcpToken")),
			connect.WithClientOptions(opts...),
		),
		deleteMcpToken: connect.NewClient[v1.DeleteMcpTokenRequest, v1.DeleteMcpTokenResponse](
			httpClient,
			baseURL+McpTokenServiceDeleteMcpTokenProcedure,
			connect.WithSchema(mcpTokenServiceMethods.ByName("DeleteMcpToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mcpTokenServiceClient implements McpTokenServiceClient.
type mcpTokenServiceClient struct {
	listMcpTokens  *connect.Client[v1.ListMcpTokensRequest, v1.ListMcpTokensResponse]
	createMcpToken *connect.Client[v1.CreateMcpTokenRequest, v1.CreateMcpTokenResponse]
	deleteMcpToken *connect.Client[v1.DeleteMcpTokenRequest, v1.DeleteMcpTokenResponse]
}

// ListMcpTokens calls neoline.v1.McpTokenService.ListMcpTokens.
func (c *mcpTokenServiceClient) ListMcpTokens(ctx context.Context, req *connect.Request[v1.ListMcpTokensRequest]) (*connect.Response[v1.ListMcpTokensResponse], error) {
	return c.listMcpTokens.CallUnary(ctx, req)
}

// CreateMcpToken calls neoline.v1.McpTokenService.CreateMcpToken.
func (c *mcpTokenServiceClient) CreateMcpToken(ctx context.Context, req *connect.Request[v1.CreateMcpTokenRequest]) (*connect.Response[v1.CreateMcpTokenResponse], error) {
	return c.createMcpToken.CallUnary(ctx, req)
}

// DeleteMcpToken calls neoline.v1.McpTokenService.DeleteMcpToken.
func (c *mcpTokenServiceClient) DeleteMcpToken(ctx context.Context, req *connect.Request[v1.DeleteMcpTokenRequest]) (*connect.Response[v1.DeleteMcpTokenResponse], error) {
	return c.deleteMcpToken.CallUnary(ctx, req)
}

// McpTokenServiceHandler is an implementation of the neoline.v1.McpTokenService service.
type McpTokenServiceHandler interface {
	ListMcpTokens(context.Context, *connect.Request[v1.ListMcpTokensRequest]) (*connect.Response[v1.ListMcpTokensResponse], error)
	CreateMcpToken(context.Context, *connect.Request[v1.CreateMcpTokenRequest]) (*connect.Response[v1.CreateMcpTokenResponse], error)
	DeleteMcpToken(context.Context, *connect.Request[v1.DeleteMcpTokenRequest]) (*connect.Response[v1.DeleteMcpTokenResponse], error)
}

// NewMcpTokenServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMcpTokenServiceHandler(svc McpTokenServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mcpTokenServiceMethods := v1.File_neoline_v1_mcp_token_proto.Services().ByName("McpTokenService").Methods()
	mcpTokenServiceListMcpTokensHandler := connect.NewUnaryHandler(
		McpTokenServiceListMcpTokensProcedure,
		svc.ListMcpTokens,
		connect.WithSchema(mcpTokenServiceMethods.ByName("ListMcpTokens")),
		connect.WithHandlerOptions(opts...),
	)
	mcpTokenServiceCreateMcpTokenHandler := connect.NewUnaryHandler(
		McpTokenServiceCreateMcpTokenProcedure,
		svc.CreateMcpToken,
		connect.WithSchema(mcpTokenServiceMethods.ByName("CreateMcpToken")),
		connect.WithHandlerOptions(opts...),
	)
	mcpTokenServiceDeleteMcpTokenHandler := connect.NewUnaryHandler(
		McpTokenServiceDeleteMcpTokenProcedure,
		svc.DeleteMcpToken,
		connect.WithSchema(mcpTokenServiceMethods.ByName("DeleteMcpToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.McpTokenService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case McpTokenServiceListMcpTokensProcedure:
			mcpTokenServiceListMcpTokensHandler.ServeHTTP(w, r)
		case McpTokenServiceCreateMcpTokenProcedure:
			mcpTokenServiceCreateMcpTokenHandler.ServeHTTP(w, r)
		case McpTokenServiceDeleteMcpTokenProcedure:
			mcpTokenServiceDeleteMcpTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMcpTokenServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMcpTokenServiceHandler struct{}

func (UnimplementedMcpTokenServiceHandler) ListMcpTokens(context.Context, *connect.Request[v1.ListMcpTokensRequest]) (*connect.Response[v1.ListMcpTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.McpTokenService.ListMcpTokens is not implemented"))
}

func (UnimplementedMcpTokenServiceHandler) CreateMcpToken(context.Context, *connect.Request[v1.CreateMcpTokenRequest]) (*connect.Response[v1.CreateMcpTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.McpTokenService.CreateMcpToken is not implemented"))
}

func (UnimplementedMcpTokenServiceHandler) DeleteMcpToken(context.Context, *connect.Request[v1.DeleteMcpTokenRequest]) (*connect.Response[v1.DeleteMcpTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.McpTokenService.DeleteMcpToken is not implemented"))
}
