// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/notify_group.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotifyGroupServiceName is the fully-qualified name of the NotifyGroupService service.
	NotifyGroupServiceName = "neoline.v1.NotifyGroupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotifyGroupServiceListNotifyGroupsProcedure is the fully-qualified name of the
	// NotifyGroupService's ListNotifyGroups RPC.
	NotifyGroupServiceListNotifyGroupsProcedure = "/neoline.v1.NotifyGroupService/ListNotifyGroups"
	// NotifyGroupServiceCreateNotifyGroupProcedure is the fully-qualified name of the
	// NotifyGroupService's CreateNotifyGroup RPC.
	NotifyGroupServiceCreateNotifyGroupProcedure = "/neoline.v1.NotifyGroupService/CreateNotifyGroup"
	// NotifyGroupServiceGetNotifyGroupProcedure is the fully-qualified name of the NotifyGroupService's
	// GetNotifyGroup RPC.
	NotifyGroupServiceGetNotifyGroupProcedure = "/neoline.v1.NotifyGroupService/GetNotifyGroup"
	// NotifyGroupServiceUpdateNotifyGroupProcedure is the fully-qualified name of the
	// NotifyGroupService's UpdateNotifyGroup RPC.
	NotifyGroupServiceUpdateNotifyGroupProcedure = "/neoline.v1.NotifyGroupService/UpdateNotifyGroup"
	// NotifyGroupServiceDeleteNotifyGroupProcedure is the fully-qualified name of the
	// NotifyGroupService's DeleteNotifyGroup RPC.
	NotifyGroupServiceDeleteNotifyGroupProcedure = "/neoline.v1.NotifyGroupService/DeleteNotifyGroup"
)

// NotifyGroupServiceClient is a client for the neoline.v1.NotifyGroupService service.
type NotifyGroupServiceClient interface {
	ListNotifyGroups(context.Context, *connect.Request[v1.ListNotifyGroupsRequest]) (*connect.Response[v1.ListNotifyGroupsResponse], error)
	CreateNotifyGroup(context.Context, *connect.Request[v1.CreateNotifyGroupRequest]) (*connect.Response[v1.CreateNotifyGroupResponse], error)
	GetNotifyGroup(context.Context, *connect.Request[v1.GetNotifyGroupRequest]) (*connect.Response[v1.GetNotifyGroupResponse], error)
	UpdateNotifyGroup(context.Context, *connect.Request[v1.UpdateNotifyGroupRequest]) (*connect.Response[v1.UpdateNotifyGroupResponse], error)
	DeleteNotifyGroup(context.Context, *connect.Request[v1.DeleteNotifyGroupRequest]) (*connect.Response[v1.DeleteNotifyGroupResponse], error)
}

// NewNotifyGroupServiceClient constructs a client for the neoline.v1.NotifyGroupService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotifyGroupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotifyGroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notifyGroupServiceMethods := v1.File_neoline_v1_notify_group_proto.Services().ByName("NotifyGroupService").Methods()
	return &notifyGroupServiceClient{
		listNotifyGroups: connect.NewClient[v1.ListNotifyGroupsRequest, v1.ListNotifyGroupsResponse](
			httpClient,
			baseURL+NotifyGroupServiceListNotifyGroupsProcedure,
			connect.WithSchema(notifyGroupServiceMethods.ByName("ListNotifyGroups")),
			connect.WithClientOptions(opts...),
		),
		createNotifyGroup: connect.NewClient[v1.CreateNotifyGroupRequest, v1.CreateNotifyGroupResponse](
			httpClient,
			baseURL+NotifyGroupServiceCreateNotifyGroupProcedure,
			connect.WithSchema(notifyGroupServiceMethods.ByName("CreateNotifyGroup")),
			connect.WithClientOptions(opts...),
		),
		getNotifyGroup: connect.NewClient[v1.GetNotifyGroupRequest, v1.GetNotifyGroupResponse](
			httpClient,
			baseURL+NotifyGroupServiceGetNotifyGroupProcedure,
			connect.WithSchema(notifyGroupServiceMethods.ByName("GetNotifyGroup")),
			connect.WithClientOptions(opts...),
		),
		updateNotifyGroup: connect.NewClient[v1.UpdateNotifyGroupRequest, v1.UpdateNotifyGroupResponse](
			httpClient,
			baseURL+NotifyGroupServiceUpdateNotifyGroupProcedure,
			connect.WithSchema(notifyGroupServiceMethods.ByName("UpdateNotifyGroup")),
			connect.WithClientOptions(opts...),
		),
		deleteNotifyGroup: connect.NewClient[v1.DeleteNotifyGroupRequest, v1.DeleteNotifyGroupResponse](
			httpClient,
			baseURL+NotifyGroupServiceDeleteNotifyGroupProcedure,
			connect.WithSchema(notifyGroupServiceMethods.ByName("DeleteNotifyGroup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notifyGroupServiceClient implements NotifyGroupServiceClient.
type notifyGroupServiceClient struct {
	listNotifyGroups  *connect.Client[v1.ListNotifyGroupsRequest, v1.ListNotifyGroupsResponse]
	createNotifyGroup *connect.Client[v1.CreateNotifyGroupRequest, v1.CreateNotifyGroupResponse]
	getNotifyGroup    *connect.Client[v1.GetNotifyGroupRequest, v1.GetNotifyGroupResponse]
	updateNotifyGroup *connect.Client[v1.UpdateNotifyGroupRequest, v1.UpdateNotifyGroupResponse]
	deleteNotifyGroup *connect.Client[v1.DeleteNotifyGroupRequest, v1.DeleteNotifyGroupResponse]
}

// ListNotifyGroups calls neoline.v1.NotifyGroupService.ListNotifyGroups.
func (c *notifyGroupServiceClient) ListNotifyGroups(ctx context.Context, req *connect.Request[v1.ListNotifyGroupsRequest]) (*connect.Response[v1.ListNotifyGroupsResponse], error) {
	return c.listNotifyGroups.CallUnary(ctx, req)
}

// CreateNotifyGroup calls neoline.v1.NotifyGroupService.CreateNotifyGroup.
func (c *notifyGroupServiceClient) CreateNotifyGroup(ctx context.Context, req *connect.Request[v1.CreateNotifyGroupRequest]) (*connect.Response[v1.CreateNotifyGroupResponse], error) {
	return c.createNotifyGroup.CallUnary(ctx, req)
}

// GetNotifyGroup calls neoline.v1.NotifyGroupService.GetNotifyGroup.
func (c *notifyGroupServiceClient) GetNotifyGroup(ctx context.Context, req *connect.Request[v1.GetNotifyGroupRequest]) (*connect.Response[v1.GetNotifyGroupResponse], error) {
	return c.getNotifyGroup.CallUnary(ctx, req)
}

// UpdateNotifyGroup calls neoline.v1.NotifyGroupService.UpdateNotifyGroup.
func (c *notifyGroupServiceClient) UpdateNotifyGroup(ctx context.Context, req *connect.Request[v1.UpdateNotifyGroupRequest]) (*connect.Response[v1.UpdateNotifyGroupResponse], error) {
	return c.updateNotifyGroup.CallUnary(ctx, req)
}

// DeleteNotifyGroup calls neoline.v1.NotifyGroupService.DeleteNotifyGroup.
func (c *notifyGroupServiceClient) DeleteNotifyGroup(ctx context.Context, req *connect.Request[v1.DeleteNotifyGroupRequest]) (*connect.Response[v1.DeleteNotifyGroupResponse], error) {
	return c.deleteNotifyGroup.CallUnary(ctx, req)
}

// NotifyGroupServiceHandler is an implementation of the neoline.v1.NotifyGroupService service.
type NotifyGroupServiceHandler interface {
	ListNotifyGroups(context.Context, *connect.Request[v1.ListNotifyGroupsRequest]) (*connect.Response[v1.ListNotifyGroupsResponse], error)
	CreateNotifyGroup(context.Context, *connect.Request[v1.CreateNotifyGroupRequest]) (*connect.Response[v1.CreateNotifyGroupResponse], error)
	GetNotifyGroup(context.Context, *connect.Request[v1.GetNotifyGroupRequest]) (*connect.Response[v1.GetNotifyGroupResponse], error)
	UpdateNotifyGroup(context.Context, *connect.Request[v1.UpdateNotifyGroupRequest]) (*connect.Response[v1.UpdateNotifyGroupResponse], error)
	DeleteNotifyGroup(context.Context, *connect.Request[v1.DeleteNotifyGroupRequest]) (*connect.Response[v1.DeleteNotifyGroupResponse], error)
}

// NewNotifyGroupServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotifyGroupServiceHandler(svc NotifyGroupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notifyGroupServiceMethods := v1.File_neoline_v1_notify_group_proto.Services().ByName("NotifyGroupService").Methods()
	notifyGroupServiceListNotifyGroupsHandler := connect.NewUnaryHandler(
		NotifyGroupServiceListNotifyGroupsProcedure,
		svc.ListNotifyGroups,
		connect.WithSchema(notifyGroupServiceMethods.ByName("ListNotifyGroups")),
		connect.WithHandlerOptions(opts...),
	)
	notifyGroupServiceCreateNotifyGroupHandler := connect.NewUnaryHandler(
		NotifyGroupServiceCreateNotifyGroupProcedure,
		svc.CreateNotifyGroup,
		connect.WithSchema(notifyGroupServiceMethods.ByName("CreateNotifyGroup")),
		connect.WithHandlerOptions(opts...),
	)
	notifyGroupServiceGetNotifyGroupHandler := connect.NewUnaryHandler(
		NotifyGroupServiceGetNotifyGroupProcedure,
		svc.GetNotifyGroup,
		connect.WithSchema(notifyGroupServiceMethods.ByName("GetNotifyGroup")),
		connect.WithHandlerOptions(opts...),
	)
	notifyGroupServiceUpdateNotifyGroupHandler := connect.NewUnaryHandler(
		NotifyGroupServiceUpdateNotifyGroupProcedure,
		svc.UpdateNotifyGroup,
		connect.WithSchema(notifyGroupServiceMethods.ByName("UpdateNotifyGroup")),
		connect.WithHandlerOptions(opts...),
	)
	notifyGroupServiceDeleteNotifyGroupHandler := connect.NewUnaryHandler(
		NotifyGroupServiceDeleteNotifyGroupProcedure,
		svc.DeleteNotifyGroup,
		connect.WithSchema(notifyGroupServiceMethods.ByName("DeleteNotifyGroup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.NotifyGroupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotifyGroupServiceListNotifyGroupsProcedure:
			notifyGroupServiceListNotifyGroupsHandler.ServeHTTP(w, r)
		case NotifyGroupServiceCreateNotifyGroupProcedure:
			notifyGroupServiceCreateNotifyGroupHandler.ServeHTTP(w, r)
		case NotifyGroupServiceGetNotifyGroupProcedure:
			notifyGroupServiceGetNotifyGroupHandler.ServeHTTP(w, r)
		case NotifyGroupServiceUpdateNotifyGroupProcedure:
			notifyGroupServiceUpdateNotifyGroupHandler.ServeHTTP(w, r)
		case NotifyGroupServiceDeleteNotifyGroupProcedure:
			notifyGroupServiceDeleteNotifyGroupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotifyGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotifyGroupServiceHandler struct{}

func (UnimplementedNotifyGroupServiceHandler) ListNotifyGroups(context.Context, *connect.Request[v1.ListNotifyGroupsRequest]) (*connect.Response[v1.ListNotifyGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.NotifyGroupService.ListNotifyGroups is not implemented"))
}

func (UnimplementedNotifyGroupServiceHandler) CreateNotifyGroup(context.Context, *connect.Request[v1.CreateNotifyGroupRequest]) (*connect.Response[v1.CreateNotifyGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.NotifyGroupService.CreateNotifyGroup is not implemented"))
}

func (UnimplementedNotifyGroupServiceHandler) GetNotifyGroup(context.Context, *connect.Request[v1.GetNotifyGroupRequest]) (*connect.Response[v1.GetNotifyGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.NotifyGroupService.GetNotifyGroup is not implemented"))
}

func (UnimplementedNotifyGroupServiceHandler) UpdateNotifyGroup(context.Context, *connect.Request[v1.UpdateNotifyGroupRequest]) (*connect.Response[v1.UpdateNotifyGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.NotifyGroupService.UpdateNotifyGroup is not implemented"))
}

func (UnimplementedNotifyGroupServiceHandler) DeleteNotifyGroup(context.Context, *connect.Request[v1.DeleteNotifyGroupRequest]) (*connect.Response[v1.DeleteNotifyGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.NotifyGroupService.DeleteNotifyGroup is not implemented"))
}
