// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/server.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServerServiceName is the fully-qualified name of the ServerService service.
	ServerServiceName = "neoline.v1.ServerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerServiceListServersProcedure is the fully-qualified name of the ServerService's ListServers
	// RPC.
	ServerServiceListServersProcedure = "/neoline.v1.ServerService/ListServers"
	// ServerServiceCreateServerProcedure is the fully-qualified name of the ServerService's
	// CreateServer RPC.
	ServerServiceCreateServerProcedure = "/neoline.v1.ServerService/CreateServer"
	// ServerServiceGetServerProcedure is the fully-qualified name of the ServerService's GetServer RPC.
	ServerServiceGetServerProcedure = "/neoline.v1.ServerService/GetServer"
	// ServerServiceUpdateServerProcedure is the fully-qualified name of the ServerService's
	// UpdateServer RPC.
	ServerServiceUpdateServerProcedure = "/neoline.v1.ServerService/UpdateServer"
	// ServerServiceDeleteServerProcedure is the fully-qualified name of the ServerService's
	// DeleteServer RPC.
	ServerServiceDeleteServerProcedure = "/neoline.v1.ServerService/DeleteServer"
	// ServerServiceGetServerHealthProcedure is the fully-qualified name of the ServerService's
	// GetServerHealth RPC.
	ServerServiceGetServerHealthProcedure = "/neoline.v1.ServerService/GetServerHealth"
	// ServerServiceListServerEventsProcedure is the fully-qualified name of the ServerService's
	// ListServerEvents RPC.
	ServerServiceListServerEventsProcedure = "/neoline.v1.ServerService/ListServerEvents"
)

// ServerServiceClient is a client for the neoline.v1.ServerService service.
type ServerServiceClient interface {
	ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error)
	CreateServer(context.Context, *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error)
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
	UpdateServer(context.Context, *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error)
	DeleteServer(context.Context, *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error)
	GetServerHealth(context.Context, *connect.Request[v1.GetServerHealthRequest]) (*connect.Response[v1.GetServerHealthResponse], error)
	ListServerEvents(context.Context, *connect.Request[v1.ListServerEventsRequest]) (*connect.Response[v1.ListServerEventsResponse], error)
}

// NewServerServiceClient constructs a client for the neoline.v1.ServerService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serverServiceMethods := v1.File_neoline_v1_server_proto.Services().ByName("ServerService").Methods()
	return &serverServiceClient{
		listServers: connect.NewClient[v1.ListServersRequest, v1.ListServersResponse](
			httpClient,
			baseURL+ServerServiceListServersProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ListServers")),
			connect.WithClientOptions(opts...),
		),
		createServer: connect.NewClient[v1.CreateServerRequest, v1.CreateServerResponse](
			httpClient,
			baseURL+ServerServiceCreateServerProcedure,
			connect.WithSchema(serverServiceMethods.ByName("CreateServer")),
			connect.WithClientOptions(opts...),
		),
		getServer: connect.NewClient[v1.GetServerRequest, v1.GetServerResponse](
			httpClient,
			baseURL+ServerServiceGetServerProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetServer")),
			connect.WithClientOptions(opts...),
		),
		updateServer: connect.NewClient[v1.UpdateServerRequest, v1.UpdateServerResponse](
			httpClient,
			baseURL+ServerServiceUpdateServerProcedure,
			connect.WithSchema(serverServiceMethods.ByName("UpdateServer")),
			connect.WithClientOptions(opts...),
		),
		deleteServer: connect.NewClient[v1.DeleteServerRequest, v1.DeleteServerResponse](
			httpClient,
			baseURL+ServerServiceDeleteServerProcedure,
			connect.WithSchema(serverServiceMethods.ByName("DeleteServer")),
			connect.WithClientOptions(opts...),
		),
		getServerHealth: connect.NewClient[v1.GetServerHealthRequest, v1.GetServerHealthResponse](
			httpClient,
			baseURL+ServerServiceGetServerHealthProcedure,
			connect.WithSchema(serverServiceMethods.ByName("GetServerHealth")),
			connect.WithClientOptions(opts...),
		),
		listServerEvents: connect.NewClient[v1.ListServerEventsRequest, v1.ListServerEventsResponse](
			httpClient,
			baseURL+ServerServiceListServerEventsProcedure,
			connect.WithSchema(serverServiceMethods.ByName("ListServerEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serverServiceClient implements ServerServiceClient.
type serverServiceClient struct {
	listServers      *connect.Client[v1.ListServersRequest, v1.ListServersResponse]
	createServer     *connect.Client[v1.CreateServerRequest, v1.CreateServerResponse]
	getServer        *connect.Client[v1.GetServerRequest, v1.GetServerResponse]
	updateServer     *connect.Client[v1.UpdateServerRequest, v1.UpdateServerResponse]
	deleteServer     *connect.Client[v1.DeleteServerRequest, v1.DeleteServerResponse]
	getServerHealth  *connect.Client[v1.GetServerHealthRequest, v1.GetServerHealthResponse]
	listServerEvents *connect.Client[v1.ListServerEventsRequest, v1.ListServerEventsResponse]
}

// ListServers calls neoline.v1.ServerService.ListServers.
func (c *serverServiceClient) ListServers(ctx context.Context, req *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error) {
	return c.listServers.CallUnary(ctx, req)
}

// CreateServer calls neoline.v1.ServerService.CreateServer.
func (c *serverServiceClient) CreateServer(ctx context.Context, req *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error) {
	return c.createServer.CallUnary(ctx, req)
}

// GetServer calls neoline.v1.ServerService.GetServer.
func (c *serverServiceClient) GetServer(ctx context.Context, req *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return c.getServer.CallUnary(ctx, req)
}

// UpdateServer calls neoline.v1.ServerService.UpdateServer.
func (c *serverServiceClient) UpdateServer(ctx context.Context, req *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error) {
	return c.updateServer.CallUnary(ctx, req)
}

// DeleteServer calls neoline.v1.ServerService.DeleteServer.
func (c *serverServiceClient) DeleteServer(ctx context.Context, req *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error) {
	return c.deleteServer.CallUnary(ctx, req)
}

// GetServerHealth calls neoline.v1.ServerService.GetServerHealth.
func (c *serverServiceClient) GetServerHealth(ctx context.Context, req *connect.Request[v1.GetServerHealthRequest]) (*connect.Response[v1.GetServerHealthResponse], error) {
	return c.getServerHealth.CallUnary(ctx, req)
}

// ListServerEvents calls neoline.v1.ServerService.ListServerEvents.
func (c *serverServiceClient) ListServerEvents(ctx context.Context, req *connect.Request[v1.ListServerEventsRequest]) (*connect.Response[v1.ListServerEventsResponse], error) {
	return c.listServerEvents.CallUnary(ctx, req)
}

// ServerServiceHandler is an implementation of the neoline.v1.ServerService service.
type ServerServiceHandler interface {
	ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error)
	CreateServer(context.Context, *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error)
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
	UpdateServer(context.Context, *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error)
	DeleteServer(context.Context, *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error)
	GetServerHealth(context.Context, *connect.Request[v1.GetServerHealthRequest]) (*connect.Response[v1.GetServerHealthResponse], error)
	ListServerEvents(context.Context, *connect.Request[v1.ListServerEventsRequest]) (*connect.Response[v1.ListServerEventsResponse], error)
}

// NewServerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServerServiceHandler(svc ServerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serverServiceMethods := v1.File_neoline_v1_server_proto.Services().ByName("ServerService").Methods()
	serverServiceListServersHandler := connect.NewUnaryHandler(
		ServerServiceListServersProcedure,
		svc.ListServers,
		connect.WithSchema(serverServiceMethods.ByName("ListServers")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceCreateServerHandler := connect.NewUnaryHandler(
		ServerServiceCreateServerProcedure,
		svc.CreateServer,
		connect.WithSchema(serverServiceMethods.ByName("CreateServer")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetServerHandler := connect.NewUnaryHandler(
		ServerServiceGetServerProcedure,
		svc.GetServer,
		connect.WithSchema(serverServiceMethods.ByName("GetServer")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceUpdateServerHandler := connect.NewUnaryHandler(
		ServerServiceUpdateServerProcedure,
		svc.UpdateServer,
		connect.WithSchema(serverServiceMethods.ByName("UpdateServer")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceDeleteServerHandler := connect.NewUnaryHandler(
		ServerServiceDeleteServerProcedure,
		svc.DeleteServer,
		connect.WithSchema(serverServiceMethods.ByName("DeleteServer")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceGetServerHealthHandler := connect.NewUnaryHandler(
		ServerServiceGetServerHealthProcedure,
		svc.GetServerHealth,
		connect.WithSchema(serverServiceMethods.ByName("GetServerHealth")),
		connect.WithHandlerOptions(opts...),
	)
	serverServiceListServerEventsHandler := connect.NewUnaryHandler(
		ServerServiceListServerEventsProcedure,
		svc.ListServerEvents,
		connect.WithSchema(serverServiceMethods.ByName("ListServerEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.ServerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServerServiceListServersProcedure:
			serverServiceListServersHandler.ServeHTTP(w, r)
		case ServerServiceCreateServerProcedure:
			serverServiceCreateServerHandler.ServeHTTP(w, r)
		case ServerServiceGetServerProcedure:
			serverServiceGetServerHandler.ServeHTTP(w, r)
		case ServerServiceUpdateServerProcedure:
			serverServiceUpdateServerHandler.ServeHTTP(w, r)
		case ServerServiceDeleteServerProcedure:
			serverServiceDeleteServerHandler.ServeHTTP(w, r)
		case ServerServiceGetServerHealthProcedure:
			serverServiceGetServerHealthHandler.ServeHTTP(w, r)
		case ServerServiceListServerEventsProcedure:
			serverServiceListServerEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServerServiceHandler struct{}

func (UnimplementedServerServiceHandler) ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.ListServers is not implemented"))
}

func (UnimplementedServerServiceHandler) CreateServer(context.Context, *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.CreateServer is not implemented"))
}

func (UnimplementedServerServiceHandler) GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.GetServer is not implemented"))
}

func (UnimplementedServerServiceHandler) UpdateServer(context.Context, *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.UpdateServer is not implemented"))
}

func (UnimplementedServerServiceHandler) DeleteServer(context.Context, *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.DeleteServer is not implemented"))
}

func (UnimplementedServerServiceHandler) GetServerHealth(context.Context, *connect.Request[v1.GetServerHealthRequest]) (*connect.Response[v1.GetServerHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.GetServerHealth is not implemented"))
}

func (UnimplementedServerServiceHandler) ListServerEvents(context.Context, *connect.Request[v1.ListServerEventsRequest]) (*connect.Response[v1.ListServerEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.ServerService.ListServerEvents is not implemented"))
}
