// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/ssh.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SshServiceName is the fully-qualified name of the SshService service.
	SshServiceName = "neoline.v1.SshService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SshServiceExecProcedure is the fully-qualified name of the SshService's Exec RPC.
	SshServiceExecProcedure = "/neoline.v1.SshService/Exec"
	// SshServiceTestConnectionProcedure is the fully-qualified name of the SshService's TestConnection
	// RPC.
	SshServiceTestConnectionProcedure = "/neoline.v1.SshService/TestConnection"
)

// SshServiceClient is a client for the neoline.v1.SshService service.
type SshServiceClient interface {
	Exec(context.Context, *connect.Request[v1.SshServiceExecRequest]) (*connect.Response[v1.SshServiceExecResponse], error)
	TestConnection(context.Context, *connect.Request[v1.SshServiceTestConnectionRequest]) (*connect.Response[v1.SshServiceTestConnectionResponse], error)
}

// NewSshServiceClient constructs a client for the neoline.v1.SshService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSshServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SshServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sshServiceMethods := v1.File_neoline_v1_ssh_proto.Services().ByName("SshService").Methods()
	return &sshServiceClient{
		exec: connect.NewClient[v1.SshServiceExecRequest, v1.SshServiceExecResponse](
			httpClient,
			baseURL+SshServiceExecProcedure,
			connect.WithSchema(sshServiceMethods.ByName("Exec")),
			connect.WithClientOptions(opts...),
		),
		testConnection: connect.NewClient[v1.SshServiceTestConnectionRequest, v1.SshServiceTestConnectionResponse](
			httpClient,
			baseURL+SshServiceTestConnectionProcedure,
			connect.WithSchema(sshServiceMethods.ByName("TestConnection")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sshServiceClient implements SshServiceClient.
type sshServiceClient struct {
	exec           *connect.Client[v1.SshServiceExecRequest, v1.SshServiceExecResponse]
	testConnection *connect.Client[v1.SshServiceTestConnectionRequest, v1.SshServiceTestConnectionResponse]
}

// Exec calls neoline.v1.SshService.Exec.
func (c *sshServiceClient) Exec(ctx context.Context, req *connect.Request[v1.SshServiceExecRequest]) (*connect.Response[v1.SshServiceExecResponse], error) {
	return c.exec.CallUnary(ctx, req)
}

// TestConnection calls neoline.v1.SshService.TestConnection.
func (c *sshServiceClient) TestConnection(ctx context.Context, req *connect.Request[v1.SshServiceTestConnectionRequest]) (*connect.Response[v1.SshServiceTestConnectionResponse], error) {
	return c.testConnection.CallUnary(ctx, req)
}

// SshServiceHandler is an implementation of the neoline.v1.SshService service.
type SshServiceHandler interface {
	Exec(context.Context, *connect.Request[v1.SshServiceExecRequest]) (*connect.Response[v1.SshServiceExecResponse], error)
	TestConnection(context.Context, *connect.Request[v1.SshServiceTestConnectionRequest]) (*connect.Response[v1.SshServiceTestConnectionResponse], error)
}

// NewSshServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSshServiceHandler(svc SshServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sshServiceMethods := v1.File_neoline_v1_ssh_proto.Services().ByName("SshService").Methods()
	sshServiceExecHandler := connect.NewUnaryHandler(
		SshServiceExecProcedure,
		svc.Exec,
		connect.WithSchema(sshServiceMethods.ByName("Exec")),
		connect.WithHandlerOptions(opts...),
	)
	sshServiceTestConnectionHandler := connect.NewUnaryHandler(
		SshServiceTestConnectionProcedure,
		svc.TestConnection,
		connect.WithSchema(sshServiceMethods.ByName("TestConnection")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.SshService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SshServiceExecProcedure:
			sshServiceExecHandler.ServeHTTP(w, r)
		case SshServiceTestConnectionProcedure:
			sshServiceTestConnectionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSshServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSshServiceHandler struct{}

func (UnimplementedSshServiceHandler) Exec(context.Context, *connect.Request[v1.SshServiceExecRequest]) (*connect.Response[v1.SshServiceExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.SshService.Exec is not implemented"))
}

func (UnimplementedSshServiceHandler) TestConnection(context.Context, *connect.Request[v1.SshServiceTestConnectionRequest]) (*connect.Response[v1.SshServiceTestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.SshService.TestConnection is not implemented"))
}
