// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: neoline/v1/status.proto

package neolinev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/neo-line/pkg/proto/neoline/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StatusServiceName is the fully-qualified name of the StatusService service.
	StatusServiceName = "neoline.v1.StatusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StatusServiceGetStatusOverviewProcedure is the fully-qualified name of the StatusService's
	// GetStatusOverview RPC.
	StatusServiceGetStatusOverviewProcedure = "/neoline.v1.StatusService/GetStatusOverview"
)

// StatusServiceClient is a client for the neoline.v1.StatusService service.
type StatusServiceClient interface {
	GetStatusOverview(context.Context, *connect.Request[v1.GetStatusOverviewRequest]) (*connect.Response[v1.GetStatusOverviewResponse], error)
}

// NewStatusServiceClient constructs a client for the neoline.v1.StatusService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	statusServiceMethods := v1.File_neoline_v1_status_proto.Services().ByName("StatusService").Methods()
	return &statusServiceClient{
		getStatusOverview: connect.NewClient[v1.GetStatusOverviewRequest, v1.GetStatusOverviewResponse](
			httpClient,
			baseURL+StatusServiceGetStatusOverviewProcedure,
			connect.WithSchema(statusServiceMethods.ByName("GetStatusOverview")),
			connect.WithClientOptions(opts...),
		),
	}
}

// statusServiceClient implements StatusServiceClient.
type statusServiceClient struct {
	getStatusOverview *connect.Client[v1.GetStatusOverviewRequest, v1.GetStatusOverviewResponse]
}

// GetStatusOverview calls neoline.v1.StatusService.GetStatusOverview.
func (c *statusServiceClient) GetStatusOverview(ctx context.Context, req *connect.Request[v1.GetStatusOverviewRequest]) (*connect.Response[v1.GetStatusOverviewResponse], error) {
	return c.getStatusOverview.CallUnary(ctx, req)
}

// StatusServiceHandler is an implementation of the neoline.v1.StatusService service.
type StatusServiceHandler interface {
	GetStatusOverview(context.Context, *connect.Request[v1.GetStatusOverviewRequest]) (*connect.Response[v1.GetStatusOverviewResponse], error)
}

// NewStatusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatusServiceHandler(svc StatusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statusServiceMethods := v1.File_neoline_v1_status_proto.Services().ByName("StatusService").Methods()
	statusServiceGetStatusOverviewHandler := connect.NewUnaryHandler(
		StatusServiceGetStatusOverviewProcedure,
		svc.GetStatusOverview,
		connect.WithSchema(statusServiceMethods.ByName("GetStatusOverview")),
		connect.WithHandlerOptions(opts...),
	)
	return "/neoline.v1.StatusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatusServiceGetStatusOverviewProcedure:
			statusServiceGetStatusOverviewHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatusServiceHandler struct{}

func (UnimplementedStatusServiceHandler) GetStatusOverview(context.Context, *connect.Request[v1.GetStatusOverviewRequest]) (*connect.Response[v1.GetStatusOverviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("neoline.v1.StatusService.GetStatusOverview is not implemented"))
}
