// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: neoline/v1/certificate_issuer.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertificateIssuerRegistrationStatus tracks async ACME account registration.
type CertificateIssuerRegistrationStatus int32

const (
	CertificateIssuerRegistrationStatus_CERTIFICATE_ISSUER_REGISTRATION_STATUS_UNSPECIFIED CertificateIssuerRegistrationStatus = 0
	CertificateIssuerRegistrationStatus_CERTIFICATE_ISSUER_REGISTRATION_STATUS_PENDING     CertificateIssuerRegistrationStatus = 1
	CertificateIssuerRegistrationStatus_CERTIFICATE_ISSUER_REGISTRATION_STATUS_READY       CertificateIssuerRegistrationStatus = 2
	CertificateIssuerRegistrationStatus_CERTIFICATE_ISSUER_REGISTRATION_STATUS_FAILED      CertificateIssuerRegistrationStatus = 3
)

// Enum value maps for CertificateIssuerRegistrationStatus.
var (
	CertificateIssuerRegistrationStatus_name = map[int32]string{
		0: "CERTIFICATE_ISSUER_REGISTRATION_STATUS_UNSPECIFIED",
		1: "CERTIFICATE_ISSUER_REGISTRATION_STATUS_PENDING",
		2: "CERTIFICATE_ISSUER_REGISTRATION_STATUS_READY",
		3: "CERTIFICATE_ISSUER_REGISTRATION_STATUS_FAILED",
	}
	CertificateIssuerRegistrationStatus_value = map[string]int32{
		"CERTIFICATE_ISSUER_REGISTRATION_STATUS_UNSPECIFIED": 0,
		"CERTIFICATE_ISSUER_REGISTRATION_STATUS_PENDING":     1,
		"CERTIFICATE_ISSUER_REGISTRATION_STATUS_READY":       2,
		"CERTIFICATE_ISSUER_REGISTRATION_STATUS_FAILED":      3,
	}
)

func (x CertificateIssuerRegistrationStatus) Enum() *CertificateIssuerRegistrationStatus {
	p := new(CertificateIssuerRegistrationStatus)
	*p = x
	return p
}

func (x CertificateIssuerRegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateIssuerRegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_neoline_v1_certificate_issuer_proto_enumTypes[0].Descriptor()
}

func (CertificateIssuerRegistrationStatus) Type() protoreflect.EnumType {
	return &file_neoline_v1_certificate_issuer_proto_enumTypes[0]
}

func (x CertificateIssuerRegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateIssuerRegistrationStatus.Descriptor instead.
func (CertificateIssuerRegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{0}
}

// CertificateIssuer holds a named ACME account configuration. Secrets are never
// returned on read; use the *_configured booleans instead.
type CertificateIssuer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Preset or custom CA type, e.g. lets_encrypt_production, lets_encrypt_staging,
	// zerossl, google_public_ca, custom.
	CaType string `protobuf:"bytes,3,opt,name=ca_type,json=caType,proto3" json:"ca_type,omitempty"`
	// Resolved ACME directory URL used for registration and future issuance.
	DirectoryUrl       string                              `protobuf:"bytes,4,opt,name=directory_url,json=directoryUrl,proto3" json:"directory_url,omitempty"`
	Email              string                              `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	RegistrationStatus CertificateIssuerRegistrationStatus `protobuf:"varint,6,opt,name=registration_status,json=registrationStatus,proto3,enum=neoline.v1.CertificateIssuerRegistrationStatus" json:"registration_status,omitempty"`
	// Sanitized registration failure summary; empty when not failed.
	RegistrationError string `protobuf:"bytes,7,opt,name=registration_error,json=registrationError,proto3" json:"registration_error,omitempty"`
	// True for Let's Encrypt staging and other explicitly untrusted environments.
	StagingUntrusted bool `protobuf:"varint,8,opt,name=staging_untrusted,json=stagingUntrusted,proto3" json:"staging_untrusted,omitempty"`
	// Terms of Service URL from the ACME directory metadata at agreement time.
	TermsOfServiceUrl      string                 `protobuf:"bytes,9,opt,name=terms_of_service_url,json=termsOfServiceUrl,proto3" json:"terms_of_service_url,omitempty"`
	TermsOfServiceAgreedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=terms_of_service_agreed_at,json=termsOfServiceAgreedAt,proto3" json:"terms_of_service_agreed_at,omitempty"`
	// True when an ACME account private key is stored.
	AccountKeyConfigured bool `protobuf:"varint,11,opt,name=account_key_configured,json=accountKeyConfigured,proto3" json:"account_key_configured,omitempty"`
	// True when EAB credentials are stored (required for ZeroSSL / Google Public CA).
	EabConfigured bool                   `protobuf:"varint,12,opt,name=eab_configured,json=eabConfigured,proto3" json:"eab_configured,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateIssuer) Reset() {
	*x = CertificateIssuer{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateIssuer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateIssuer) ProtoMessage() {}

func (x *CertificateIssuer) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateIssuer.ProtoReflect.Descriptor instead.
func (*CertificateIssuer) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateIssuer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateIssuer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateIssuer) GetCaType() string {
	if x != nil {
		return x.CaType
	}
	return ""
}

func (x *CertificateIssuer) GetDirectoryUrl() string {
	if x != nil {
		return x.DirectoryUrl
	}
	return ""
}

func (x *CertificateIssuer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CertificateIssuer) GetRegistrationStatus() CertificateIssuerRegistrationStatus {
	if x != nil {
		return x.RegistrationStatus
	}
	return CertificateIssuerRegistrationStatus_CERTIFICATE_ISSUER_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *CertificateIssuer) GetRegistrationError() string {
	if x != nil {
		return x.RegistrationError
	}
	return ""
}

func (x *CertificateIssuer) GetStagingUntrusted() bool {
	if x != nil {
		return x.StagingUntrusted
	}
	return false
}

func (x *CertificateIssuer) GetTermsOfServiceUrl() string {
	if x != nil {
		return x.TermsOfServiceUrl
	}
	return ""
}

func (x *CertificateIssuer) GetTermsOfServiceAgreedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TermsOfServiceAgreedAt
	}
	return nil
}

func (x *CertificateIssuer) GetAccountKeyConfigured() bool {
	if x != nil {
		return x.AccountKeyConfigured
	}
	return false
}

func (x *CertificateIssuer) GetEabConfigured() bool {
	if x != nil {
		return x.EabConfigured
	}
	return false
}

func (x *CertificateIssuer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CertificateIssuer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Directory preview for ToS agreement before create.
type CertificateIssuerDirectoryPreview struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CaType            string                 `protobuf:"bytes,1,opt,name=ca_type,json=caType,proto3" json:"ca_type,omitempty"`
	DirectoryUrl      string                 `protobuf:"bytes,2,opt,name=directory_url,json=directoryUrl,proto3" json:"directory_url,omitempty"`
	TermsOfServiceUrl string                 `protobuf:"bytes,3,opt,name=terms_of_service_url,json=termsOfServiceUrl,proto3" json:"terms_of_service_url,omitempty"`
	StagingUntrusted  bool                   `protobuf:"varint,4,opt,name=staging_untrusted,json=stagingUntrusted,proto3" json:"staging_untrusted,omitempty"`
	// True when the preset requires External Account Binding credentials.
	RequiresEab   bool `protobuf:"varint,5,opt,name=requires_eab,json=requiresEab,proto3" json:"requires_eab,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateIssuerDirectoryPreview) Reset() {
	*x = CertificateIssuerDirectoryPreview{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateIssuerDirectoryPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateIssuerDirectoryPreview) ProtoMessage() {}

func (x *CertificateIssuerDirectoryPreview) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateIssuerDirectoryPreview.ProtoReflect.Descriptor instead.
func (*CertificateIssuerDirectoryPreview) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateIssuerDirectoryPreview) GetCaType() string {
	if x != nil {
		return x.CaType
	}
	return ""
}

func (x *CertificateIssuerDirectoryPreview) GetDirectoryUrl() string {
	if x != nil {
		return x.DirectoryUrl
	}
	return ""
}

func (x *CertificateIssuerDirectoryPreview) GetTermsOfServiceUrl() string {
	if x != nil {
		return x.TermsOfServiceUrl
	}
	return ""
}

func (x *CertificateIssuerDirectoryPreview) GetStagingUntrusted() bool {
	if x != nil {
		return x.StagingUntrusted
	}
	return false
}

func (x *CertificateIssuerDirectoryPreview) GetRequiresEab() bool {
	if x != nil {
		return x.RequiresEab
	}
	return false
}

type ListCertificateIssuersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificateIssuersRequest) Reset() {
	*x = ListCertificateIssuersRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificateIssuersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificateIssuersRequest) ProtoMessage() {}

func (x *ListCertificateIssuersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificateIssuersRequest.ProtoReflect.Descriptor instead.
func (*ListCertificateIssuersRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{2}
}

func (x *ListCertificateIssuersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCertificateIssuersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCertificateIssuersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuers       []*CertificateIssuer   `protobuf:"bytes,1,rep,name=issuers,proto3" json:"issuers,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificateIssuersResponse) Reset() {
	*x = ListCertificateIssuersResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificateIssuersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificateIssuersResponse) ProtoMessage() {}

func (x *ListCertificateIssuersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificateIssuersResponse.ProtoReflect.Descriptor instead.
func (*ListCertificateIssuersResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{3}
}

func (x *ListCertificateIssuersResponse) GetIssuers() []*CertificateIssuer {
	if x != nil {
		return x.Issuers
	}
	return nil
}

func (x *ListCertificateIssuersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetCertificateIssuerDirectoryPreviewRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CaType string                 `protobuf:"bytes,1,opt,name=ca_type,json=caType,proto3" json:"ca_type,omitempty"`
	// Required when ca_type is custom.
	CustomDirectoryUrl string `protobuf:"bytes,2,opt,name=custom_directory_url,json=customDirectoryUrl,proto3" json:"custom_directory_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCertificateIssuerDirectoryPreviewRequest) Reset() {
	*x = GetCertificateIssuerDirectoryPreviewRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateIssuerDirectoryPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateIssuerDirectoryPreviewRequest) ProtoMessage() {}

func (x *GetCertificateIssuerDirectoryPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateIssuerDirectoryPreviewRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateIssuerDirectoryPreviewRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{4}
}

func (x *GetCertificateIssuerDirectoryPreviewRequest) GetCaType() string {
	if x != nil {
		return x.CaType
	}
	return ""
}

func (x *GetCertificateIssuerDirectoryPreviewRequest) GetCustomDirectoryUrl() string {
	if x != nil {
		return x.CustomDirectoryUrl
	}
	return ""
}

type GetCertificateIssuerDirectoryPreviewResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Preview       *CertificateIssuerDirectoryPreview `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateIssuerDirectoryPreviewResponse) Reset() {
	*x = GetCertificateIssuerDirectoryPreviewResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateIssuerDirectoryPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateIssuerDirectoryPreviewResponse) ProtoMessage() {}

func (x *GetCertificateIssuerDirectoryPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateIssuerDirectoryPreviewResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateIssuerDirectoryPreviewResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{5}
}

func (x *GetCertificateIssuerDirectoryPreviewResponse) GetPreview() *CertificateIssuerDirectoryPreview {
	if x != nil {
		return x.Preview
	}
	return nil
}

type CreateCertificateIssuerRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Issuer *CertificateIssuer     `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// ACME account private key in PEM form. Empty generates a new EC P-256 key.
	AccountKeyPem string `protobuf:"bytes,2,opt,name=account_key_pem,json=accountKeyPem,proto3" json:"account_key_pem,omitempty"`
	// External Account Binding KID. Required for ZeroSSL and Google Public CA presets.
	EabKid string `protobuf:"bytes,3,opt,name=eab_kid,json=eabKid,proto3" json:"eab_kid,omitempty"`
	// External Account Binding HMAC key (base64url). Required with eab_kid for EAB presets.
	EabHmac string `protobuf:"bytes,4,opt,name=eab_hmac,json=eabHmac,proto3" json:"eab_hmac,omitempty"`
	// Must be true to persist ToS agreement and start registration.
	TermsOfServiceAgreed bool `protobuf:"varint,5,opt,name=terms_of_service_agreed,json=termsOfServiceAgreed,proto3" json:"terms_of_service_agreed,omitempty"`
	// Required when ca_type is custom.
	CustomDirectoryUrl string `protobuf:"bytes,6,opt,name=custom_directory_url,json=customDirectoryUrl,proto3" json:"custom_directory_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCertificateIssuerRequest) Reset() {
	*x = CreateCertificateIssuerRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertificateIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertificateIssuerRequest) ProtoMessage() {}

func (x *CreateCertificateIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertificateIssuerRequest.ProtoReflect.Descriptor instead.
func (*CreateCertificateIssuerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCertificateIssuerRequest) GetIssuer() *CertificateIssuer {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *CreateCertificateIssuerRequest) GetAccountKeyPem() string {
	if x != nil {
		return x.AccountKeyPem
	}
	return ""
}

func (x *CreateCertificateIssuerRequest) GetEabKid() string {
	if x != nil {
		return x.EabKid
	}
	return ""
}

func (x *CreateCertificateIssuerRequest) GetEabHmac() string {
	if x != nil {
		return x.EabHmac
	}
	return ""
}

func (x *CreateCertificateIssuerRequest) GetTermsOfServiceAgreed() bool {
	if x != nil {
		return x.TermsOfServiceAgreed
	}
	return false
}

func (x *CreateCertificateIssuerRequest) GetCustomDirectoryUrl() string {
	if x != nil {
		return x.CustomDirectoryUrl
	}
	return ""
}

type CreateCertificateIssuerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        *CertificateIssuer     `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCertificateIssuerResponse) Reset() {
	*x = CreateCertificateIssuerResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertificateIssuerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertificateIssuerResponse) ProtoMessage() {}

func (x *CreateCertificateIssuerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertificateIssuerResponse.ProtoReflect.Descriptor instead.
func (*CreateCertificateIssuerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCertificateIssuerResponse) GetIssuer() *CertificateIssuer {
	if x != nil {
		return x.Issuer
	}
	return nil
}

type GetCertificateIssuerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CertificateIssuerId string                 `protobuf:"bytes,1,opt,name=certificate_issuer_id,json=certificateIssuerId,proto3" json:"certificate_issuer_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetCertificateIssuerRequest) Reset() {
	*x = GetCertificateIssuerRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateIssuerRequest) ProtoMessage() {}

func (x *GetCertificateIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateIssuerRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateIssuerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{8}
}

func (x *GetCertificateIssuerRequest) GetCertificateIssuerId() string {
	if x != nil {
		return x.CertificateIssuerId
	}
	return ""
}

type GetCertificateIssuerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        *CertificateIssuer     `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateIssuerResponse) Reset() {
	*x = GetCertificateIssuerResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateIssuerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateIssuerResponse) ProtoMessage() {}

func (x *GetCertificateIssuerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateIssuerResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateIssuerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{9}
}

func (x *GetCertificateIssuerResponse) GetIssuer() *CertificateIssuer {
	if x != nil {
		return x.Issuer
	}
	return nil
}

type UpdateCertificateIssuerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CertificateIssuerId string                 `protobuf:"bytes,1,opt,name=certificate_issuer_id,json=certificateIssuerId,proto3" json:"certificate_issuer_id,omitempty"`
	Issuer              *CertificateIssuer     `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Identity fields below apply only when registration_status is Failed.
	AccountKeyPem      string `protobuf:"bytes,3,opt,name=account_key_pem,json=accountKeyPem,proto3" json:"account_key_pem,omitempty"`
	EabKid             string `protobuf:"bytes,4,opt,name=eab_kid,json=eabKid,proto3" json:"eab_kid,omitempty"`
	EabHmac            string `protobuf:"bytes,5,opt,name=eab_hmac,json=eabHmac,proto3" json:"eab_hmac,omitempty"`
	CustomDirectoryUrl string `protobuf:"bytes,6,opt,name=custom_directory_url,json=customDirectoryUrl,proto3" json:"custom_directory_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateCertificateIssuerRequest) Reset() {
	*x = UpdateCertificateIssuerRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertificateIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertificateIssuerRequest) ProtoMessage() {}

func (x *UpdateCertificateIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertificateIssuerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCertificateIssuerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCertificateIssuerRequest) GetCertificateIssuerId() string {
	if x != nil {
		return x.CertificateIssuerId
	}
	return ""
}

func (x *UpdateCertificateIssuerRequest) GetIssuer() *CertificateIssuer {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *UpdateCertificateIssuerRequest) GetAccountKeyPem() string {
	if x != nil {
		return x.AccountKeyPem
	}
	return ""
}

func (x *UpdateCertificateIssuerRequest) GetEabKid() string {
	if x != nil {
		return x.EabKid
	}
	return ""
}

func (x *UpdateCertificateIssuerRequest) GetEabHmac() string {
	if x != nil {
		return x.EabHmac
	}
	return ""
}

func (x *UpdateCertificateIssuerRequest) GetCustomDirectoryUrl() string {
	if x != nil {
		return x.CustomDirectoryUrl
	}
	return ""
}

type UpdateCertificateIssuerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        *CertificateIssuer     `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCertificateIssuerResponse) Reset() {
	*x = UpdateCertificateIssuerResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertificateIssuerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertificateIssuerResponse) ProtoMessage() {}

func (x *UpdateCertificateIssuerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertificateIssuerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCertificateIssuerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCertificateIssuerResponse) GetIssuer() *CertificateIssuer {
	if x != nil {
		return x.Issuer
	}
	return nil
}

type DeleteCertificateIssuerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CertificateIssuerId string                 `protobuf:"bytes,1,opt,name=certificate_issuer_id,json=certificateIssuerId,proto3" json:"certificate_issuer_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeleteCertificateIssuerRequest) Reset() {
	*x = DeleteCertificateIssuerRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateIssuerRequest) ProtoMessage() {}

func (x *DeleteCertificateIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateIssuerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCertificateIssuerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCertificateIssuerRequest) GetCertificateIssuerId() string {
	if x != nil {
		return x.CertificateIssuerId
	}
	return ""
}

type DeleteCertificateIssuerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateIssuerResponse) Reset() {
	*x = DeleteCertificateIssuerResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateIssuerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateIssuerResponse) ProtoMessage() {}

func (x *DeleteCertificateIssuerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateIssuerResponse.ProtoReflect.Descriptor instead.
func (*DeleteCertificateIssuerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{13}
}

type RetryCertificateIssuerRegistrationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CertificateIssuerId string                 `protobuf:"bytes,1,opt,name=certificate_issuer_id,json=certificateIssuerId,proto3" json:"certificate_issuer_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RetryCertificateIssuerRegistrationRequest) Reset() {
	*x = RetryCertificateIssuerRegistrationRequest{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryCertificateIssuerRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryCertificateIssuerRegistrationRequest) ProtoMessage() {}

func (x *RetryCertificateIssuerRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryCertificateIssuerRegistrationRequest.ProtoReflect.Descriptor instead.
func (*RetryCertificateIssuerRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{14}
}

func (x *RetryCertificateIssuerRegistrationRequest) GetCertificateIssuerId() string {
	if x != nil {
		return x.CertificateIssuerId
	}
	return ""
}

type RetryCertificateIssuerRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        *CertificateIssuer     `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryCertificateIssuerRegistrationResponse) Reset() {
	*x = RetryCertificateIssuerRegistrationResponse{}
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryCertificateIssuerRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryCertificateIssuerRegistrationResponse) ProtoMessage() {}

func (x *RetryCertificateIssuerRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_issuer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryCertificateIssuerRegistrationResponse.ProtoReflect.Descriptor instead.
func (*RetryCertificateIssuerRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_issuer_proto_rawDescGZIP(), []int{15}
}

func (x *RetryCertificateIssuerRegistrationResponse) GetIssuer() *CertificateIssuer {
	if x != nil {
		return x.Issuer
	}
	return nil
}

var File_neoline_v1_certificate_issuer_proto protoreflect.FileDescriptor

const file_neoline_v1_certificate_issuer_proto_rawDesc = "" +
	"\n" +
	"#neoline/v1/certificate_issuer.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x05\n" +
	"\x11CertificateIssuer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aca_type\x18\x03 \x01(\tR\x06caType\x12#\n" +
	"\rdirectory_url\x18\x04 \x01(\tR\fdirectoryUrl\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12`\n" +
	"\x13registration_status\x18\x06 \x01(\x0e2/.neoline.v1.CertificateIssuerRegistrationStatusR\x12registrationStatus\x12-\n" +
	"\x12registration_error\x18\a \x01(\tR\x11registrationError\x12+\n" +
	"\x11staging_untrusted\x18\b \x01(\bR\x10stagingUntrusted\x12/\n" +
	"\x14terms_of_service_url\x18\t \x01(\tR\x11termsOfServiceUrl\x12V\n" +
	"\x1aterms_of_service_agreed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x16termsOfServiceAgreedAt\x124\n" +
	"\x16account_key_configured\x18\v \x01(\bR\x14accountKeyConfigured\x12%\n" +
	"\x0eeab_configured\x18\f \x01(\bR\reabConfigured\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe2\x01\n" +
	"!CertificateIssuerDirectoryPreview\x12\x17\n" +
	"\aca_type\x18\x01 \x01(\tR\x06caType\x12#\n" +
	"\rdirectory_url\x18\x02 \x01(\tR\fdirectoryUrl\x12/\n" +
	"\x14terms_of_service_url\x18\x03 \x01(\tR\x11termsOfServiceUrl\x12+\n" +
	"\x11staging_untrusted\x18\x04 \x01(\bR\x10stagingUntrusted\x12!\n" +
	"\frequires_eab\x18\x05 \x01(\bR\vrequiresEab\"[\n" +
	"\x1dListCertificateIssuersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x1eListCertificateIssuersResponse\x127\n" +
	"\aissuers\x18\x01 \x03(\v2\x1d.neoline.v1.CertificateIssuerR\aissuers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"x\n" +
	"+GetCertificateIssuerDirectoryPreviewRequest\x12\x17\n" +
	"\aca_type\x18\x01 \x01(\tR\x06caType\x120\n" +
	"\x14custom_directory_url\x18\x02 \x01(\tR\x12customDirectoryUrl\"w\n" +
	",GetCertificateIssuerDirectoryPreviewResponse\x12G\n" +
	"\apreview\x18\x01 \x01(\v2-.neoline.v1.CertificateIssuerDirectoryPreviewR\apreview\"\x9c\x02\n" +
	"\x1eCreateCertificateIssuerRequest\x125\n" +
	"\x06issuer\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateIssuerR\x06issuer\x12&\n" +
	"\x0faccount_key_pem\x18\x02 \x01(\tR\raccountKeyPem\x12\x17\n" +
	"\aeab_kid\x18\x03 \x01(\tR\x06eabKid\x12\x19\n" +
	"\beab_hmac\x18\x04 \x01(\tR\aeabHmac\x125\n" +
	"\x17terms_of_service_agreed\x18\x05 \x01(\bR\x14termsOfServiceAgreed\x120\n" +
	"\x14custom_directory_url\x18\x06 \x01(\tR\x12customDirectoryUrl\"X\n" +
	"\x1fCreateCertificateIssuerResponse\x125\n" +
	"\x06issuer\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateIssuerR\x06issuer\"Q\n" +
	"\x1bGetCertificateIssuerRequest\x122\n" +
	"\x15certificate_issuer_id\x18\x01 \x01(\tR\x13certificateIssuerId\"U\n" +
	"\x1cGetCertificateIssuerResponse\x125\n" +
	"\x06issuer\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateIssuerR\x06issuer\"\x99\x02\n" +
	"\x1eUpdateCertificateIssuerRequest\x122\n" +
	"\x15certificate_issuer_id\x18\x01 \x01(\tR\x13certificateIssuerId\x125\n" +
	"\x06issuer\x18\x02 \x01(\v2\x1d.neoline.v1.CertificateIssuerR\x06issuer\x12&\n" +
	"\x0faccount_key_pem\x18\x03 \x01(\tR\raccountKeyPem\x12\x17\n" +
	"\aeab_kid\x18\x04 \x01(\tR\x06eabKid\x12\x19\n" +
	"\beab_hmac\x18\x05 \x01(\tR\aeabHmac\x120\n" +
	"\x14custom_directory_url\x18\x06 \x01(\tR\x12customDirectoryUrl\"X\n" +
	"\x1fUpdateCertificateIssuerResponse\x125\n" +
	"\x06issuer\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateIssuerR\x06issuer\"T\n" +
	"\x1eDeleteCertificateIssuerRequest\x122\n" +
	"\x15certificate_issuer_id\x18\x01 \x01(\tR\x13certificateIssuerId\"!\n" +
	"\x1fDeleteCertificateIssuerResponse\"_\n" +
	")RetryCertificateIssuerRegistrationRequest\x122\n" +
	"\x15certificate_issuer_id\x18\x01 \x01(\tR\x13certificateIssuerId\"c\n" +
	"*RetryCertificateIssuerRegistrationResponse\x125\n" +
	"\x06issuer\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateIssuerR\x06issuer*\xf6\x01\n" +
	"#CertificateIssuerRegistrationStatus\x126\n" +
	"2CERTIFICATE_ISSUER_REGISTRATION_STATUS_UNSPECIFIED\x10\x00\x122\n" +
	".CERTIFICATE_ISSUER_REGISTRATION_STATUS_PENDING\x10\x01\x120\n" +
	",CERTIFICATE_ISSUER_REGISTRATION_STATUS_READY\x10\x02\x121\n" +
	"-CERTIFICATE_ISSUER_REGISTRATION_STATUS_FAILED\x10\x032\x92\a\n" +
	"\x18CertificateIssuerService\x12q\n" +
	"\x16ListCertificateIssuers\x12).neoline.v1.ListCertificateIssuersRequest\x1a*.neoline.v1.ListCertificateIssuersResponse\"\x00\x12\x9b\x01\n" +
	"$GetCertificateIssuerDirectoryPreview\x127.neoline.v1.GetCertificateIssuerDirectoryPreviewRequest\x1a8.neoline.v1.GetCertificateIssuerDirectoryPreviewResponse\"\x00\x12t\n" +
	"\x17CreateCertificateIssuer\x12*.neoline.v1.CreateCertificateIssuerRequest\x1a+.neoline.v1.CreateCertificateIssuerResponse\"\x00\x12k\n" +
	"\x14GetCertificateIssuer\x12'.neoline.v1.GetCertificateIssuerRequest\x1a(.neoline.v1.GetCertificateIssuerResponse\"\x00\x12t\n" +
	"\x17UpdateCertificateIssuer\x12*.neoline.v1.UpdateCertificateIssuerRequest\x1a+.neoline.v1.UpdateCertificateIssuerResponse\"\x00\x12t\n" +
	"\x17DeleteCertificateIssuer\x12*.neoline.v1.DeleteCertificateIssuerRequest\x1a+.neoline.v1.DeleteCertificateIssuerResponse\"\x00\x12\x95\x01\n" +
	"\"RetryCertificateIssuerRegistration\x125.neoline.v1.RetryCertificateIssuerRegistrationRequest\x1a6.neoline.v1.RetryCertificateIssuerRegistrationResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_certificate_issuer_proto_rawDescOnce sync.Once
	file_neoline_v1_certificate_issuer_proto_rawDescData []byte
)

func file_neoline_v1_certificate_issuer_proto_rawDescGZIP() []byte {
	file_neoline_v1_certificate_issuer_proto_rawDescOnce.Do(func() {
		file_neoline_v1_certificate_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_certificate_issuer_proto_rawDesc), len(file_neoline_v1_certificate_issuer_proto_rawDesc)))
	})
	return file_neoline_v1_certificate_issuer_proto_rawDescData
}

var file_neoline_v1_certificate_issuer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neoline_v1_certificate_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_neoline_v1_certificate_issuer_proto_goTypes = []any{
	(CertificateIssuerRegistrationStatus)(0),             // 0: neoline.v1.CertificateIssuerRegistrationStatus
	(*CertificateIssuer)(nil),                            // 1: neoline.v1.CertificateIssuer
	(*CertificateIssuerDirectoryPreview)(nil),            // 2: neoline.v1.CertificateIssuerDirectoryPreview
	(*ListCertificateIssuersRequest)(nil),                // 3: neoline.v1.ListCertificateIssuersRequest
	(*ListCertificateIssuersResponse)(nil),               // 4: neoline.v1.ListCertificateIssuersResponse
	(*GetCertificateIssuerDirectoryPreviewRequest)(nil),  // 5: neoline.v1.GetCertificateIssuerDirectoryPreviewRequest
	(*GetCertificateIssuerDirectoryPreviewResponse)(nil), // 6: neoline.v1.GetCertificateIssuerDirectoryPreviewResponse
	(*CreateCertificateIssuerRequest)(nil),               // 7: neoline.v1.CreateCertificateIssuerRequest
	(*CreateCertificateIssuerResponse)(nil),              // 8: neoline.v1.CreateCertificateIssuerResponse
	(*GetCertificateIssuerRequest)(nil),                  // 9: neoline.v1.GetCertificateIssuerRequest
	(*GetCertificateIssuerResponse)(nil),                 // 10: neoline.v1.GetCertificateIssuerResponse
	(*UpdateCertificateIssuerRequest)(nil),               // 11: neoline.v1.UpdateCertificateIssuerRequest
	(*UpdateCertificateIssuerResponse)(nil),              // 12: neoline.v1.UpdateCertificateIssuerResponse
	(*DeleteCertificateIssuerRequest)(nil),               // 13: neoline.v1.DeleteCertificateIssuerRequest
	(*DeleteCertificateIssuerResponse)(nil),              // 14: neoline.v1.DeleteCertificateIssuerResponse
	(*RetryCertificateIssuerRegistrationRequest)(nil),    // 15: neoline.v1.RetryCertificateIssuerRegistrationRequest
	(*RetryCertificateIssuerRegistrationResponse)(nil),   // 16: neoline.v1.RetryCertificateIssuerRegistrationResponse
	(*timestamppb.Timestamp)(nil),                        // 17: google.protobuf.Timestamp
}
var file_neoline_v1_certificate_issuer_proto_depIdxs = []int32{
	0,  // 0: neoline.v1.CertificateIssuer.registration_status:type_name -> neoline.v1.CertificateIssuerRegistrationStatus
	17, // 1: neoline.v1.CertificateIssuer.terms_of_service_agreed_at:type_name -> google.protobuf.Timestamp
	17, // 2: neoline.v1.CertificateIssuer.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: neoline.v1.CertificateIssuer.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: neoline.v1.ListCertificateIssuersResponse.issuers:type_name -> neoline.v1.CertificateIssuer
	2,  // 5: neoline.v1.GetCertificateIssuerDirectoryPreviewResponse.preview:type_name -> neoline.v1.CertificateIssuerDirectoryPreview
	1,  // 6: neoline.v1.CreateCertificateIssuerRequest.issuer:type_name -> neoline.v1.CertificateIssuer
	1,  // 7: neoline.v1.CreateCertificateIssuerResponse.issuer:type_name -> neoline.v1.CertificateIssuer
	1,  // 8: neoline.v1.GetCertificateIssuerResponse.issuer:type_name -> neoline.v1.CertificateIssuer
	1,  // 9: neoline.v1.UpdateCertificateIssuerRequest.issuer:type_name -> neoline.v1.CertificateIssuer
	1,  // 10: neoline.v1.UpdateCertificateIssuerResponse.issuer:type_name -> neoline.v1.CertificateIssuer
	1,  // 11: neoline.v1.RetryCertificateIssuerRegistrationResponse.issuer:type_name -> neoline.v1.CertificateIssuer
	3,  // 12: neoline.v1.CertificateIssuerService.ListCertificateIssuers:input_type -> neoline.v1.ListCertificateIssuersRequest
	5,  // 13: neoline.v1.CertificateIssuerService.GetCertificateIssuerDirectoryPreview:input_type -> neoline.v1.GetCertificateIssuerDirectoryPreviewRequest
	7,  // 14: neoline.v1.CertificateIssuerService.CreateCertificateIssuer:input_type -> neoline.v1.CreateCertificateIssuerRequest
	9,  // 15: neoline.v1.CertificateIssuerService.GetCertificateIssuer:input_type -> neoline.v1.GetCertificateIssuerRequest
	11, // 16: neoline.v1.CertificateIssuerService.UpdateCertificateIssuer:input_type -> neoline.v1.UpdateCertificateIssuerRequest
	13, // 17: neoline.v1.CertificateIssuerService.DeleteCertificateIssuer:input_type -> neoline.v1.DeleteCertificateIssuerRequest
	15, // 18: neoline.v1.CertificateIssuerService.RetryCertificateIssuerRegistration:input_type -> neoline.v1.RetryCertificateIssuerRegistrationRequest
	4,  // 19: neoline.v1.CertificateIssuerService.ListCertificateIssuers:output_type -> neoline.v1.ListCertificateIssuersResponse
	6,  // 20: neoline.v1.CertificateIssuerService.GetCertificateIssuerDirectoryPreview:output_type -> neoline.v1.GetCertificateIssuerDirectoryPreviewResponse
	8,  // 21: neoline.v1.CertificateIssuerService.CreateCertificateIssuer:output_type -> neoline.v1.CreateCertificateIssuerResponse
	10, // 22: neoline.v1.CertificateIssuerService.GetCertificateIssuer:output_type -> neoline.v1.GetCertificateIssuerResponse
	12, // 23: neoline.v1.CertificateIssuerService.UpdateCertificateIssuer:output_type -> neoline.v1.UpdateCertificateIssuerResponse
	14, // 24: neoline.v1.CertificateIssuerService.DeleteCertificateIssuer:output_type -> neoline.v1.DeleteCertificateIssuerResponse
	16, // 25: neoline.v1.CertificateIssuerService.RetryCertificateIssuerRegistration:output_type -> neoline.v1.RetryCertificateIssuerRegistrationResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_neoline_v1_certificate_issuer_proto_init() }
func file_neoline_v1_certificate_issuer_proto_init() {
	if File_neoline_v1_certificate_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_certificate_issuer_proto_rawDesc), len(file_neoline_v1_certificate_issuer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_certificate_issuer_proto_goTypes,
		DependencyIndexes: file_neoline_v1_certificate_issuer_proto_depIdxs,
		EnumInfos:         file_neoline_v1_certificate_issuer_proto_enumTypes,
		MessageInfos:      file_neoline_v1_certificate_issuer_proto_msgTypes,
	}.Build()
	File_neoline_v1_certificate_issuer_proto = out.File
	file_neoline_v1_certificate_issuer_proto_goTypes = nil
	file_neoline_v1_certificate_issuer_proto_depIdxs = nil
}
