// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: neoline/v1/certificate_access_token.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertificateAccessToken authorizes a Server to call ServerCertificateService.
// The plaintext secret is returned only once on creation and is never stored.
type CertificateAccessToken struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId   string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Prefix     string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	ExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// True when expires_at is in the past; expired tokens remain listed until deleted.
	Expired       bool `protobuf:"varint,8,opt,name=expired,proto3" json:"expired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateAccessToken) Reset() {
	*x = CertificateAccessToken{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateAccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateAccessToken) ProtoMessage() {}

func (x *CertificateAccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateAccessToken.ProtoReflect.Descriptor instead.
func (*CertificateAccessToken) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateAccessToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateAccessToken) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CertificateAccessToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateAccessToken) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CertificateAccessToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CertificateAccessToken) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *CertificateAccessToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CertificateAccessToken) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

type ListCertificateAccessTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificateAccessTokensRequest) Reset() {
	*x = ListCertificateAccessTokensRequest{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificateAccessTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificateAccessTokensRequest) ProtoMessage() {}

func (x *ListCertificateAccessTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificateAccessTokensRequest.ProtoReflect.Descriptor instead.
func (*ListCertificateAccessTokensRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{1}
}

func (x *ListCertificateAccessTokensRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ListCertificateAccessTokensResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Tokens        []*CertificateAccessToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificateAccessTokensResponse) Reset() {
	*x = ListCertificateAccessTokensResponse{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificateAccessTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificateAccessTokensResponse) ProtoMessage() {}

func (x *ListCertificateAccessTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificateAccessTokensResponse.ProtoReflect.Descriptor instead.
func (*ListCertificateAccessTokensResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{2}
}

func (x *ListCertificateAccessTokensResponse) GetTokens() []*CertificateAccessToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CreateCertificateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCertificateAccessTokenRequest) Reset() {
	*x = CreateCertificateAccessTokenRequest{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertificateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertificateAccessTokenRequest) ProtoMessage() {}

func (x *CreateCertificateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertificateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateCertificateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCertificateAccessTokenRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateCertificateAccessTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCertificateAccessTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateCertificateAccessTokenResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         *CertificateAccessToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret        string                  `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCertificateAccessTokenResponse) Reset() {
	*x = CreateCertificateAccessTokenResponse{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertificateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertificateAccessTokenResponse) ProtoMessage() {}

func (x *CreateCertificateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertificateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateCertificateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCertificateAccessTokenResponse) GetToken() *CertificateAccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateCertificateAccessTokenResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeleteCertificateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateAccessTokenRequest) Reset() {
	*x = DeleteCertificateAccessTokenRequest{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateAccessTokenRequest) ProtoMessage() {}

func (x *DeleteCertificateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteCertificateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCertificateAccessTokenRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DeleteCertificateAccessTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type DeleteCertificateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCertificateAccessTokenResponse) Reset() {
	*x = DeleteCertificateAccessTokenResponse{}
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCertificateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCertificateAccessTokenResponse) ProtoMessage() {}

func (x *DeleteCertificateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_certificate_access_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCertificateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteCertificateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_certificate_access_token_proto_rawDescGZIP(), []int{6}
}

var File_neoline_v1_certificate_access_token_proto protoreflect.FileDescriptor

const file_neoline_v1_certificate_access_token_proto_rawDesc = "" +
	"\n" +
	")neoline/v1/certificate_access_token.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\x16CertificateAccessToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aexpired\x18\b \x01(\bR\aexpired\"A\n" +
	"\"ListCertificateAccessTokensRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"a\n" +
	"#ListCertificateAccessTokensResponse\x12:\n" +
	"\x06tokens\x18\x01 \x03(\v2\".neoline.v1.CertificateAccessTokenR\x06tokens\"\x91\x01\n" +
	"#CreateCertificateAccessTokenRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"x\n" +
	"$CreateCertificateAccessTokenResponse\x128\n" +
	"\x05token\x18\x01 \x01(\v2\".neoline.v1.CertificateAccessTokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"]\n" +
	"#DeleteCertificateAccessTokenRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"&\n" +
	"$DeleteCertificateAccessTokenResponse2\xae\x03\n" +
	"\x1dCertificateAccessTokenService\x12\x80\x01\n" +
	"\x1bListCertificateAccessTokens\x12..neoline.v1.ListCertificateAccessTokensRequest\x1a/.neoline.v1.ListCertificateAccessTokensResponse\"\x00\x12\x83\x01\n" +
	"\x1cCreateCertificateAccessToken\x12/.neoline.v1.CreateCertificateAccessTokenRequest\x1a0.neoline.v1.CreateCertificateAccessTokenResponse\"\x00\x12\x83\x01\n" +
	"\x1cDeleteCertificateAccessToken\x12/.neoline.v1.DeleteCertificateAccessTokenRequest\x1a0.neoline.v1.DeleteCertificateAccessTokenResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_certificate_access_token_proto_rawDescOnce sync.Once
	file_neoline_v1_certificate_access_token_proto_rawDescData []byte
)

func file_neoline_v1_certificate_access_token_proto_rawDescGZIP() []byte {
	file_neoline_v1_certificate_access_token_proto_rawDescOnce.Do(func() {
		file_neoline_v1_certificate_access_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_certificate_access_token_proto_rawDesc), len(file_neoline_v1_certificate_access_token_proto_rawDesc)))
	})
	return file_neoline_v1_certificate_access_token_proto_rawDescData
}

var file_neoline_v1_certificate_access_token_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_neoline_v1_certificate_access_token_proto_goTypes = []any{
	(*CertificateAccessToken)(nil),               // 0: neoline.v1.CertificateAccessToken
	(*ListCertificateAccessTokensRequest)(nil),   // 1: neoline.v1.ListCertificateAccessTokensRequest
	(*ListCertificateAccessTokensResponse)(nil),  // 2: neoline.v1.ListCertificateAccessTokensResponse
	(*CreateCertificateAccessTokenRequest)(nil),  // 3: neoline.v1.CreateCertificateAccessTokenRequest
	(*CreateCertificateAccessTokenResponse)(nil), // 4: neoline.v1.CreateCertificateAccessTokenResponse
	(*DeleteCertificateAccessTokenRequest)(nil),  // 5: neoline.v1.DeleteCertificateAccessTokenRequest
	(*DeleteCertificateAccessTokenResponse)(nil), // 6: neoline.v1.DeleteCertificateAccessTokenResponse
	(*timestamppb.Timestamp)(nil),                // 7: google.protobuf.Timestamp
}
var file_neoline_v1_certificate_access_token_proto_depIdxs = []int32{
	7, // 0: neoline.v1.CertificateAccessToken.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: neoline.v1.CertificateAccessToken.last_used_at:type_name -> google.protobuf.Timestamp
	7, // 2: neoline.v1.CertificateAccessToken.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: neoline.v1.ListCertificateAccessTokensResponse.tokens:type_name -> neoline.v1.CertificateAccessToken
	7, // 4: neoline.v1.CreateCertificateAccessTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	0, // 5: neoline.v1.CreateCertificateAccessTokenResponse.token:type_name -> neoline.v1.CertificateAccessToken
	1, // 6: neoline.v1.CertificateAccessTokenService.ListCertificateAccessTokens:input_type -> neoline.v1.ListCertificateAccessTokensRequest
	3, // 7: neoline.v1.CertificateAccessTokenService.CreateCertificateAccessToken:input_type -> neoline.v1.CreateCertificateAccessTokenRequest
	5, // 8: neoline.v1.CertificateAccessTokenService.DeleteCertificateAccessToken:input_type -> neoline.v1.DeleteCertificateAccessTokenRequest
	2, // 9: neoline.v1.CertificateAccessTokenService.ListCertificateAccessTokens:output_type -> neoline.v1.ListCertificateAccessTokensResponse
	4, // 10: neoline.v1.CertificateAccessTokenService.CreateCertificateAccessToken:output_type -> neoline.v1.CreateCertificateAccessTokenResponse
	6, // 11: neoline.v1.CertificateAccessTokenService.DeleteCertificateAccessToken:output_type -> neoline.v1.DeleteCertificateAccessTokenResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_neoline_v1_certificate_access_token_proto_init() }
func file_neoline_v1_certificate_access_token_proto_init() {
	if File_neoline_v1_certificate_access_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_certificate_access_token_proto_rawDesc), len(file_neoline_v1_certificate_access_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_certificate_access_token_proto_goTypes,
		DependencyIndexes: file_neoline_v1_certificate_access_token_proto_depIdxs,
		MessageInfos:      file_neoline_v1_certificate_access_token_proto_msgTypes,
	}.Build()
	File_neoline_v1_certificate_access_token_proto = out.File
	file_neoline_v1_certificate_access_token_proto_goTypes = nil
	file_neoline_v1_certificate_access_token_proto_depIdxs = nil
}
