// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: neoline/v1/managed_certificate.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertificateKeyType selects the private key algorithm for issuance.
type CertificateKeyType int32

const (
	CertificateKeyType_CERTIFICATE_KEY_TYPE_UNSPECIFIED CertificateKeyType = 0
	CertificateKeyType_CERTIFICATE_KEY_TYPE_EC_P256     CertificateKeyType = 1
	CertificateKeyType_CERTIFICATE_KEY_TYPE_RSA_2048    CertificateKeyType = 2
)

// Enum value maps for CertificateKeyType.
var (
	CertificateKeyType_name = map[int32]string{
		0: "CERTIFICATE_KEY_TYPE_UNSPECIFIED",
		1: "CERTIFICATE_KEY_TYPE_EC_P256",
		2: "CERTIFICATE_KEY_TYPE_RSA_2048",
	}
	CertificateKeyType_value = map[string]int32{
		"CERTIFICATE_KEY_TYPE_UNSPECIFIED": 0,
		"CERTIFICATE_KEY_TYPE_EC_P256":     1,
		"CERTIFICATE_KEY_TYPE_RSA_2048":    2,
	}
)

func (x CertificateKeyType) Enum() *CertificateKeyType {
	p := new(CertificateKeyType)
	*p = x
	return p
}

func (x CertificateKeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateKeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_neoline_v1_managed_certificate_proto_enumTypes[0].Descriptor()
}

func (CertificateKeyType) Type() protoreflect.EnumType {
	return &file_neoline_v1_managed_certificate_proto_enumTypes[0]
}

func (x CertificateKeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateKeyType.Descriptor instead.
func (CertificateKeyType) EnumDescriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{0}
}

// CertificateValidity describes the active version lifecycle state.
type CertificateValidity int32

const (
	CertificateValidity_CERTIFICATE_VALIDITY_UNSPECIFIED CertificateValidity = 0
	CertificateValidity_CERTIFICATE_VALIDITY_MISSING     CertificateValidity = 1
	CertificateValidity_CERTIFICATE_VALIDITY_VALID       CertificateValidity = 2
	CertificateValidity_CERTIFICATE_VALIDITY_RENEWAL_DUE CertificateValidity = 3
	CertificateValidity_CERTIFICATE_VALIDITY_EXPIRED     CertificateValidity = 4
	CertificateValidity_CERTIFICATE_VALIDITY_REVOKED     CertificateValidity = 5
)

// Enum value maps for CertificateValidity.
var (
	CertificateValidity_name = map[int32]string{
		0: "CERTIFICATE_VALIDITY_UNSPECIFIED",
		1: "CERTIFICATE_VALIDITY_MISSING",
		2: "CERTIFICATE_VALIDITY_VALID",
		3: "CERTIFICATE_VALIDITY_RENEWAL_DUE",
		4: "CERTIFICATE_VALIDITY_EXPIRED",
		5: "CERTIFICATE_VALIDITY_REVOKED",
	}
	CertificateValidity_value = map[string]int32{
		"CERTIFICATE_VALIDITY_UNSPECIFIED": 0,
		"CERTIFICATE_VALIDITY_MISSING":     1,
		"CERTIFICATE_VALIDITY_VALID":       2,
		"CERTIFICATE_VALIDITY_RENEWAL_DUE": 3,
		"CERTIFICATE_VALIDITY_EXPIRED":     4,
		"CERTIFICATE_VALIDITY_REVOKED":     5,
	}
)

func (x CertificateValidity) Enum() *CertificateValidity {
	p := new(CertificateValidity)
	*p = x
	return p
}

func (x CertificateValidity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateValidity) Descriptor() protoreflect.EnumDescriptor {
	return file_neoline_v1_managed_certificate_proto_enumTypes[1].Descriptor()
}

func (CertificateValidity) Type() protoreflect.EnumType {
	return &file_neoline_v1_managed_certificate_proto_enumTypes[1]
}

func (x CertificateValidity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateValidity.Descriptor instead.
func (CertificateValidity) EnumDescriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{1}
}

type CertificateOperationType int32

const (
	CertificateOperationType_CERTIFICATE_OPERATION_TYPE_UNSPECIFIED CertificateOperationType = 0
	CertificateOperationType_CERTIFICATE_OPERATION_TYPE_ISSUE       CertificateOperationType = 1
	CertificateOperationType_CERTIFICATE_OPERATION_TYPE_RENEW       CertificateOperationType = 2
	CertificateOperationType_CERTIFICATE_OPERATION_TYPE_REVOKE      CertificateOperationType = 3
)

// Enum value maps for CertificateOperationType.
var (
	CertificateOperationType_name = map[int32]string{
		0: "CERTIFICATE_OPERATION_TYPE_UNSPECIFIED",
		1: "CERTIFICATE_OPERATION_TYPE_ISSUE",
		2: "CERTIFICATE_OPERATION_TYPE_RENEW",
		3: "CERTIFICATE_OPERATION_TYPE_REVOKE",
	}
	CertificateOperationType_value = map[string]int32{
		"CERTIFICATE_OPERATION_TYPE_UNSPECIFIED": 0,
		"CERTIFICATE_OPERATION_TYPE_ISSUE":       1,
		"CERTIFICATE_OPERATION_TYPE_RENEW":       2,
		"CERTIFICATE_OPERATION_TYPE_REVOKE":      3,
	}
)

func (x CertificateOperationType) Enum() *CertificateOperationType {
	p := new(CertificateOperationType)
	*p = x
	return p
}

func (x CertificateOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_neoline_v1_managed_certificate_proto_enumTypes[2].Descriptor()
}

func (CertificateOperationType) Type() protoreflect.EnumType {
	return &file_neoline_v1_managed_certificate_proto_enumTypes[2]
}

func (x CertificateOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateOperationType.Descriptor instead.
func (CertificateOperationType) EnumDescriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{2}
}

type CertificateOperationStatus int32

const (
	CertificateOperationStatus_CERTIFICATE_OPERATION_STATUS_UNSPECIFIED CertificateOperationStatus = 0
	CertificateOperationStatus_CERTIFICATE_OPERATION_STATUS_PENDING     CertificateOperationStatus = 1
	CertificateOperationStatus_CERTIFICATE_OPERATION_STATUS_RUNNING     CertificateOperationStatus = 2
	CertificateOperationStatus_CERTIFICATE_OPERATION_STATUS_SUCCEEDED   CertificateOperationStatus = 3
	CertificateOperationStatus_CERTIFICATE_OPERATION_STATUS_FAILED      CertificateOperationStatus = 4
)

// Enum value maps for CertificateOperationStatus.
var (
	CertificateOperationStatus_name = map[int32]string{
		0: "CERTIFICATE_OPERATION_STATUS_UNSPECIFIED",
		1: "CERTIFICATE_OPERATION_STATUS_PENDING",
		2: "CERTIFICATE_OPERATION_STATUS_RUNNING",
		3: "CERTIFICATE_OPERATION_STATUS_SUCCEEDED",
		4: "CERTIFICATE_OPERATION_STATUS_FAILED",
	}
	CertificateOperationStatus_value = map[string]int32{
		"CERTIFICATE_OPERATION_STATUS_UNSPECIFIED": 0,
		"CERTIFICATE_OPERATION_STATUS_PENDING":     1,
		"CERTIFICATE_OPERATION_STATUS_RUNNING":     2,
		"CERTIFICATE_OPERATION_STATUS_SUCCEEDED":   3,
		"CERTIFICATE_OPERATION_STATUS_FAILED":      4,
	}
)

func (x CertificateOperationStatus) Enum() *CertificateOperationStatus {
	p := new(CertificateOperationStatus)
	*p = x
	return p
}

func (x CertificateOperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateOperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_neoline_v1_managed_certificate_proto_enumTypes[3].Descriptor()
}

func (CertificateOperationStatus) Type() protoreflect.EnumType {
	return &file_neoline_v1_managed_certificate_proto_enumTypes[3]
}

func (x CertificateOperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateOperationStatus.Descriptor instead.
func (CertificateOperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{3}
}

// CertificateVersionSlot selects which stored version to download.
type CertificateVersionSlot int32

const (
	CertificateVersionSlot_CERTIFICATE_VERSION_SLOT_UNSPECIFIED CertificateVersionSlot = 0
	CertificateVersionSlot_CERTIFICATE_VERSION_SLOT_ACTIVE      CertificateVersionSlot = 1
	CertificateVersionSlot_CERTIFICATE_VERSION_SLOT_PREVIOUS    CertificateVersionSlot = 2
)

// Enum value maps for CertificateVersionSlot.
var (
	CertificateVersionSlot_name = map[int32]string{
		0: "CERTIFICATE_VERSION_SLOT_UNSPECIFIED",
		1: "CERTIFICATE_VERSION_SLOT_ACTIVE",
		2: "CERTIFICATE_VERSION_SLOT_PREVIOUS",
	}
	CertificateVersionSlot_value = map[string]int32{
		"CERTIFICATE_VERSION_SLOT_UNSPECIFIED": 0,
		"CERTIFICATE_VERSION_SLOT_ACTIVE":      1,
		"CERTIFICATE_VERSION_SLOT_PREVIOUS":    2,
	}
)

func (x CertificateVersionSlot) Enum() *CertificateVersionSlot {
	p := new(CertificateVersionSlot)
	*p = x
	return p
}

func (x CertificateVersionSlot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateVersionSlot) Descriptor() protoreflect.EnumDescriptor {
	return file_neoline_v1_managed_certificate_proto_enumTypes[4].Descriptor()
}

func (CertificateVersionSlot) Type() protoreflect.EnumType {
	return &file_neoline_v1_managed_certificate_proto_enumTypes[4]
}

func (x CertificateVersionSlot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateVersionSlot.Descriptor instead.
func (CertificateVersionSlot) EnumDescriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{4}
}

// IssueConfigSnapshot captures issuance parameters frozen at operation creation.
type IssueConfigSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domains              []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	CertificateIssuerId  string                 `protobuf:"bytes,2,opt,name=certificate_issuer_id,json=certificateIssuerId,proto3" json:"certificate_issuer_id,omitempty"`
	DnsProviderAccountId string                 `protobuf:"bytes,3,opt,name=dns_provider_account_id,json=dnsProviderAccountId,proto3" json:"dns_provider_account_id,omitempty"`
	KeyType              CertificateKeyType     `protobuf:"varint,4,opt,name=key_type,json=keyType,proto3,enum=neoline.v1.CertificateKeyType" json:"key_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IssueConfigSnapshot) Reset() {
	*x = IssueConfigSnapshot{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueConfigSnapshot) ProtoMessage() {}

func (x *IssueConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueConfigSnapshot.ProtoReflect.Descriptor instead.
func (*IssueConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *IssueConfigSnapshot) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *IssueConfigSnapshot) GetCertificateIssuerId() string {
	if x != nil {
		return x.CertificateIssuerId
	}
	return ""
}

func (x *IssueConfigSnapshot) GetDnsProviderAccountId() string {
	if x != nil {
		return x.DnsProviderAccountId
	}
	return ""
}

func (x *IssueConfigSnapshot) GetKeyType() CertificateKeyType {
	if x != nil {
		return x.KeyType
	}
	return CertificateKeyType_CERTIFICATE_KEY_TYPE_UNSPECIFIED
}

type CertificateOperation struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManagedCertificateId string                     `protobuf:"bytes,2,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	Type                 CertificateOperationType   `protobuf:"varint,3,opt,name=type,proto3,enum=neoline.v1.CertificateOperationType" json:"type,omitempty"`
	Status               CertificateOperationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=neoline.v1.CertificateOperationStatus" json:"status,omitempty"`
	AttemptCount         uint32                     `protobuf:"varint,5,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	ConfigSnapshot       *IssueConfigSnapshot       `protobuf:"bytes,6,opt,name=config_snapshot,json=configSnapshot,proto3" json:"config_snapshot,omitempty"`
	ErrorSummary         string                     `protobuf:"bytes,7,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	Warning              string                     `protobuf:"bytes,8,opt,name=warning,proto3" json:"warning,omitempty"`
	StartedAt            *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt           *timestamppb.Timestamp     `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	NextAttemptAt        *timestamppb.Timestamp     `protobuf:"bytes,11,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`
	CreatedAt            *timestamppb.Timestamp     `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp     `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CertificateOperation) Reset() {
	*x = CertificateOperation{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateOperation) ProtoMessage() {}

func (x *CertificateOperation) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateOperation.ProtoReflect.Descriptor instead.
func (*CertificateOperation) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateOperation) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

func (x *CertificateOperation) GetType() CertificateOperationType {
	if x != nil {
		return x.Type
	}
	return CertificateOperationType_CERTIFICATE_OPERATION_TYPE_UNSPECIFIED
}

func (x *CertificateOperation) GetStatus() CertificateOperationStatus {
	if x != nil {
		return x.Status
	}
	return CertificateOperationStatus_CERTIFICATE_OPERATION_STATUS_UNSPECIFIED
}

func (x *CertificateOperation) GetAttemptCount() uint32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *CertificateOperation) GetConfigSnapshot() *IssueConfigSnapshot {
	if x != nil {
		return x.ConfigSnapshot
	}
	return nil
}

func (x *CertificateOperation) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

func (x *CertificateOperation) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *CertificateOperation) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CertificateOperation) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *CertificateOperation) GetNextAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextAttemptAt
	}
	return nil
}

func (x *CertificateOperation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CertificateOperation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CertificateVersionMetadata exposes active/previous version facts without PEM secrets.
type CertificateVersionMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigSnapshot   *IssueConfigSnapshot   `protobuf:"bytes,2,opt,name=config_snapshot,json=configSnapshot,proto3" json:"config_snapshot,omitempty"`
	LeafFingerprint  string                 `protobuf:"bytes,3,opt,name=leaf_fingerprint,json=leafFingerprint,proto3" json:"leaf_fingerprint,omitempty"`
	SerialNumber     string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	IssuerCommonName string                 `protobuf:"bytes,5,opt,name=issuer_common_name,json=issuerCommonName,proto3" json:"issuer_common_name,omitempty"`
	NotBefore        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	KeyType          CertificateKeyType     `protobuf:"varint,8,opt,name=key_type,json=keyType,proto3,enum=neoline.v1.CertificateKeyType" json:"key_type,omitempty"`
	StagingUntrusted bool                   `protobuf:"varint,9,opt,name=staging_untrusted,json=stagingUntrusted,proto3" json:"staging_untrusted,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CertificateVersionMetadata) Reset() {
	*x = CertificateVersionMetadata{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateVersionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateVersionMetadata) ProtoMessage() {}

func (x *CertificateVersionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateVersionMetadata.ProtoReflect.Descriptor instead.
func (*CertificateVersionMetadata) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{2}
}

func (x *CertificateVersionMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateVersionMetadata) GetConfigSnapshot() *IssueConfigSnapshot {
	if x != nil {
		return x.ConfigSnapshot
	}
	return nil
}

func (x *CertificateVersionMetadata) GetLeafFingerprint() string {
	if x != nil {
		return x.LeafFingerprint
	}
	return ""
}

func (x *CertificateVersionMetadata) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CertificateVersionMetadata) GetIssuerCommonName() string {
	if x != nil {
		return x.IssuerCommonName
	}
	return ""
}

func (x *CertificateVersionMetadata) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateVersionMetadata) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateVersionMetadata) GetKeyType() CertificateKeyType {
	if x != nil {
		return x.KeyType
	}
	return CertificateKeyType_CERTIFICATE_KEY_TYPE_UNSPECIFIED
}

func (x *CertificateVersionMetadata) GetStagingUntrusted() bool {
	if x != nil {
		return x.StagingUntrusted
	}
	return false
}

func (x *CertificateVersionMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CertificateVersionMetadata) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type CertificateBundle struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	VersionId            string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Domains              []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	KeyType              CertificateKeyType     `protobuf:"varint,4,opt,name=key_type,json=keyType,proto3,enum=neoline.v1.CertificateKeyType" json:"key_type,omitempty"`
	LeafFingerprint      string                 `protobuf:"bytes,5,opt,name=leaf_fingerprint,json=leafFingerprint,proto3" json:"leaf_fingerprint,omitempty"`
	NotBefore            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	Validity             CertificateValidity    `protobuf:"varint,8,opt,name=validity,proto3,enum=neoline.v1.CertificateValidity" json:"validity,omitempty"`
	StagingUntrusted     bool                   `protobuf:"varint,9,opt,name=staging_untrusted,json=stagingUntrusted,proto3" json:"staging_untrusted,omitempty"`
	FullchainPem         []byte                 `protobuf:"bytes,10,opt,name=fullchain_pem,json=fullchainPem,proto3" json:"fullchain_pem,omitempty"`
	PrivateKeyPem        []byte                 `protobuf:"bytes,11,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CertificateBundle) Reset() {
	*x = CertificateBundle{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateBundle) ProtoMessage() {}

func (x *CertificateBundle) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateBundle.ProtoReflect.Descriptor instead.
func (*CertificateBundle) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{3}
}

func (x *CertificateBundle) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

func (x *CertificateBundle) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *CertificateBundle) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *CertificateBundle) GetKeyType() CertificateKeyType {
	if x != nil {
		return x.KeyType
	}
	return CertificateKeyType_CERTIFICATE_KEY_TYPE_UNSPECIFIED
}

func (x *CertificateBundle) GetLeafFingerprint() string {
	if x != nil {
		return x.LeafFingerprint
	}
	return ""
}

func (x *CertificateBundle) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CertificateBundle) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *CertificateBundle) GetValidity() CertificateValidity {
	if x != nil {
		return x.Validity
	}
	return CertificateValidity_CERTIFICATE_VALIDITY_UNSPECIFIED
}

func (x *CertificateBundle) GetStagingUntrusted() bool {
	if x != nil {
		return x.StagingUntrusted
	}
	return false
}

func (x *CertificateBundle) GetFullchainPem() []byte {
	if x != nil {
		return x.FullchainPem
	}
	return nil
}

func (x *CertificateBundle) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

type GetCertificateBundleRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	// Defaults to active when unspecified.
	VersionSlot   CertificateVersionSlot `protobuf:"varint,2,opt,name=version_slot,json=versionSlot,proto3,enum=neoline.v1.CertificateVersionSlot" json:"version_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateBundleRequest) Reset() {
	*x = GetCertificateBundleRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateBundleRequest) ProtoMessage() {}

func (x *GetCertificateBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateBundleRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateBundleRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{4}
}

func (x *GetCertificateBundleRequest) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

func (x *GetCertificateBundleRequest) GetVersionSlot() CertificateVersionSlot {
	if x != nil {
		return x.VersionSlot
	}
	return CertificateVersionSlot_CERTIFICATE_VERSION_SLOT_UNSPECIFIED
}

type ActivatePreviousVersionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	VersionId            string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ActivatePreviousVersionRequest) Reset() {
	*x = ActivatePreviousVersionRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePreviousVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePreviousVersionRequest) ProtoMessage() {}

func (x *ActivatePreviousVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePreviousVersionRequest.ProtoReflect.Descriptor instead.
func (*ActivatePreviousVersionRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{5}
}

func (x *ActivatePreviousVersionRequest) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

func (x *ActivatePreviousVersionRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type ActivatePreviousVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *ManagedCertificate    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatePreviousVersionResponse) Reset() {
	*x = ActivatePreviousVersionResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePreviousVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePreviousVersionResponse) ProtoMessage() {}

func (x *ActivatePreviousVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePreviousVersionResponse.ProtoReflect.Descriptor instead.
func (*ActivatePreviousVersionResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{6}
}

func (x *ActivatePreviousVersionResponse) GetCertificate() *ManagedCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type GetCertificateBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *CertificateBundle     `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateBundleResponse) Reset() {
	*x = GetCertificateBundleResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateBundleResponse) ProtoMessage() {}

func (x *GetCertificateBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateBundleResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateBundleResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{7}
}

func (x *GetCertificateBundleResponse) GetBundle() *CertificateBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type SubmitIssueOperationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubmitIssueOperationRequest) Reset() {
	*x = SubmitIssueOperationRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIssueOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIssueOperationRequest) ProtoMessage() {}

func (x *SubmitIssueOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIssueOperationRequest.ProtoReflect.Descriptor instead.
func (*SubmitIssueOperationRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitIssueOperationRequest) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

type SubmitIssueOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *CertificateOperation  `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitIssueOperationResponse) Reset() {
	*x = SubmitIssueOperationResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIssueOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIssueOperationResponse) ProtoMessage() {}

func (x *SubmitIssueOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIssueOperationResponse.ProtoReflect.Descriptor instead.
func (*SubmitIssueOperationResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitIssueOperationResponse) GetOperation() *CertificateOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// ManagedCertificate holds desired config, assignments, and version container.
// Secrets are never returned on read.
type ManagedCertificate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domains              []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	CertificateIssuerId  string                 `protobuf:"bytes,4,opt,name=certificate_issuer_id,json=certificateIssuerId,proto3" json:"certificate_issuer_id,omitempty"`
	DnsProviderAccountId string                 `protobuf:"bytes,5,opt,name=dns_provider_account_id,json=dnsProviderAccountId,proto3" json:"dns_provider_account_id,omitempty"`
	KeyType              CertificateKeyType     `protobuf:"varint,6,opt,name=key_type,json=keyType,proto3,enum=neoline.v1.CertificateKeyType" json:"key_type,omitempty"`
	// Defaults to true on create when omitted.
	AutoRenewEnabled *bool               `protobuf:"varint,7,opt,name=auto_renew_enabled,json=autoRenewEnabled,proto3,oneof" json:"auto_renew_enabled,omitempty"`
	RenewBeforeDays  uint32              `protobuf:"varint,8,opt,name=renew_before_days,json=renewBeforeDays,proto3" json:"renew_before_days,omitempty"`
	NotifyGroupIds   []string            `protobuf:"bytes,9,rep,name=notify_group_ids,json=notifyGroupIds,proto3" json:"notify_group_ids,omitempty"`
	ServerIds        []string            `protobuf:"bytes,10,rep,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"`
	ActiveValidity   CertificateValidity `protobuf:"varint,11,opt,name=active_validity,json=activeValidity,proto3,enum=neoline.v1.CertificateValidity" json:"active_validity,omitempty"`
	BundleAvailable  bool                `protobuf:"varint,12,opt,name=bundle_available,json=bundleAvailable,proto3" json:"bundle_available,omitempty"`
	// Most recent non-terminal operation, if any (e.g. Pending Issue after create).
	LatestOperation *CertificateOperation       `protobuf:"bytes,13,opt,name=latest_operation,json=latestOperation,proto3" json:"latest_operation,omitempty"`
	CreatedAt       *timestamppb.Timestamp      `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp      `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ActiveVersion   *CertificateVersionMetadata `protobuf:"bytes,16,opt,name=active_version,json=activeVersion,proto3" json:"active_version,omitempty"`
	PreviousVersion *CertificateVersionMetadata `protobuf:"bytes,17,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	// True when desired config differs from the active version issuance snapshot.
	HasUnpublishedDesiredChanges bool `protobuf:"varint,18,opt,name=has_unpublished_desired_changes,json=hasUnpublishedDesiredChanges,proto3" json:"has_unpublished_desired_changes,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ManagedCertificate) Reset() {
	*x = ManagedCertificate{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCertificate) ProtoMessage() {}

func (x *ManagedCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCertificate.ProtoReflect.Descriptor instead.
func (*ManagedCertificate) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{10}
}

func (x *ManagedCertificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagedCertificate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagedCertificate) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ManagedCertificate) GetCertificateIssuerId() string {
	if x != nil {
		return x.CertificateIssuerId
	}
	return ""
}

func (x *ManagedCertificate) GetDnsProviderAccountId() string {
	if x != nil {
		return x.DnsProviderAccountId
	}
	return ""
}

func (x *ManagedCertificate) GetKeyType() CertificateKeyType {
	if x != nil {
		return x.KeyType
	}
	return CertificateKeyType_CERTIFICATE_KEY_TYPE_UNSPECIFIED
}

func (x *ManagedCertificate) GetAutoRenewEnabled() bool {
	if x != nil && x.AutoRenewEnabled != nil {
		return *x.AutoRenewEnabled
	}
	return false
}

func (x *ManagedCertificate) GetRenewBeforeDays() uint32 {
	if x != nil {
		return x.RenewBeforeDays
	}
	return 0
}

func (x *ManagedCertificate) GetNotifyGroupIds() []string {
	if x != nil {
		return x.NotifyGroupIds
	}
	return nil
}

func (x *ManagedCertificate) GetServerIds() []string {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

func (x *ManagedCertificate) GetActiveValidity() CertificateValidity {
	if x != nil {
		return x.ActiveValidity
	}
	return CertificateValidity_CERTIFICATE_VALIDITY_UNSPECIFIED
}

func (x *ManagedCertificate) GetBundleAvailable() bool {
	if x != nil {
		return x.BundleAvailable
	}
	return false
}

func (x *ManagedCertificate) GetLatestOperation() *CertificateOperation {
	if x != nil {
		return x.LatestOperation
	}
	return nil
}

func (x *ManagedCertificate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ManagedCertificate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ManagedCertificate) GetActiveVersion() *CertificateVersionMetadata {
	if x != nil {
		return x.ActiveVersion
	}
	return nil
}

func (x *ManagedCertificate) GetPreviousVersion() *CertificateVersionMetadata {
	if x != nil {
		return x.PreviousVersion
	}
	return nil
}

func (x *ManagedCertificate) GetHasUnpublishedDesiredChanges() bool {
	if x != nil {
		return x.HasUnpublishedDesiredChanges
	}
	return false
}

type ListManagedCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedCertificatesRequest) Reset() {
	*x = ListManagedCertificatesRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedCertificatesRequest) ProtoMessage() {}

func (x *ListManagedCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListManagedCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{11}
}

func (x *ListManagedCertificatesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManagedCertificatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListManagedCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*ManagedCertificate  `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedCertificatesResponse) Reset() {
	*x = ListManagedCertificatesResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedCertificatesResponse) ProtoMessage() {}

func (x *ListManagedCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedCertificatesResponse.ProtoReflect.Descriptor instead.
func (*ListManagedCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{12}
}

func (x *ListManagedCertificatesResponse) GetCertificates() []*ManagedCertificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *ListManagedCertificatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateManagedCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *ManagedCertificate    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManagedCertificateRequest) Reset() {
	*x = CreateManagedCertificateRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManagedCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManagedCertificateRequest) ProtoMessage() {}

func (x *CreateManagedCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManagedCertificateRequest.ProtoReflect.Descriptor instead.
func (*CreateManagedCertificateRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{13}
}

func (x *CreateManagedCertificateRequest) GetCertificate() *ManagedCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type CreateManagedCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *ManagedCertificate    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManagedCertificateResponse) Reset() {
	*x = CreateManagedCertificateResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManagedCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManagedCertificateResponse) ProtoMessage() {}

func (x *CreateManagedCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManagedCertificateResponse.ProtoReflect.Descriptor instead.
func (*CreateManagedCertificateResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{14}
}

func (x *CreateManagedCertificateResponse) GetCertificate() *ManagedCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type GetManagedCertificateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetManagedCertificateRequest) Reset() {
	*x = GetManagedCertificateRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedCertificateRequest) ProtoMessage() {}

func (x *GetManagedCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetManagedCertificateRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{15}
}

func (x *GetManagedCertificateRequest) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

type GetManagedCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *ManagedCertificate    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagedCertificateResponse) Reset() {
	*x = GetManagedCertificateResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagedCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagedCertificateResponse) ProtoMessage() {}

func (x *GetManagedCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagedCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetManagedCertificateResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{16}
}

func (x *GetManagedCertificateResponse) GetCertificate() *ManagedCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type UpdateManagedCertificateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	Certificate          *ManagedCertificate    `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateManagedCertificateRequest) Reset() {
	*x = UpdateManagedCertificateRequest{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManagedCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManagedCertificateRequest) ProtoMessage() {}

func (x *UpdateManagedCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManagedCertificateRequest.ProtoReflect.Descriptor instead.
func (*UpdateManagedCertificateRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateManagedCertificateRequest) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

func (x *UpdateManagedCertificateRequest) GetCertificate() *ManagedCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type UpdateManagedCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *ManagedCertificate    `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManagedCertificateResponse) Reset() {
	*x = UpdateManagedCertificateResponse{}
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManagedCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManagedCertificateResponse) ProtoMessage() {}

func (x *UpdateManagedCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_managed_certificate_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManagedCertificateResponse.ProtoReflect.Descriptor instead.
func (*UpdateManagedCertificateResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_managed_certificate_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateManagedCertificateResponse) GetCertificate() *ManagedCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

var File_neoline_v1_managed_certificate_proto protoreflect.FileDescriptor

const file_neoline_v1_managed_certificate_proto_rawDesc = "" +
	"\n" +
	"$neoline/v1/managed_certificate.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\x13IssueConfigSnapshot\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\x122\n" +
	"\x15certificate_issuer_id\x18\x02 \x01(\tR\x13certificateIssuerId\x125\n" +
	"\x17dns_provider_account_id\x18\x03 \x01(\tR\x14dnsProviderAccountId\x129\n" +
	"\bkey_type\x18\x04 \x01(\x0e2\x1e.neoline.v1.CertificateKeyTypeR\akeyType\"\xb6\x05\n" +
	"\x14CertificateOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x16managed_certificate_id\x18\x02 \x01(\tR\x14managedCertificateId\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2$.neoline.v1.CertificateOperationTypeR\x04type\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.neoline.v1.CertificateOperationStatusR\x06status\x12#\n" +
	"\rattempt_count\x18\x05 \x01(\rR\fattemptCount\x12H\n" +
	"\x0fconfig_snapshot\x18\x06 \x01(\v2\x1f.neoline.v1.IssueConfigSnapshotR\x0econfigSnapshot\x12#\n" +
	"\rerror_summary\x18\a \x01(\tR\ferrorSummary\x12\x18\n" +
	"\awarning\x18\b \x01(\tR\awarning\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12B\n" +
	"\x0fnext_attempt_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\rnextAttemptAt\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc6\x04\n" +
	"\x1aCertificateVersionMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12H\n" +
	"\x0fconfig_snapshot\x18\x02 \x01(\v2\x1f.neoline.v1.IssueConfigSnapshotR\x0econfigSnapshot\x12)\n" +
	"\x10leaf_fingerprint\x18\x03 \x01(\tR\x0fleafFingerprint\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12,\n" +
	"\x12issuer_common_name\x18\x05 \x01(\tR\x10issuerCommonName\x129\n" +
	"\n" +
	"not_before\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x129\n" +
	"\bkey_type\x18\b \x01(\x0e2\x1e.neoline.v1.CertificateKeyTypeR\akeyType\x12+\n" +
	"\x11staging_untrusted\x18\t \x01(\bR\x10stagingUntrusted\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"revoked_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\x93\x04\n" +
	"\x11CertificateBundle\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x129\n" +
	"\bkey_type\x18\x04 \x01(\x0e2\x1e.neoline.v1.CertificateKeyTypeR\akeyType\x12)\n" +
	"\x10leaf_fingerprint\x18\x05 \x01(\tR\x0fleafFingerprint\x129\n" +
	"\n" +
	"not_before\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12;\n" +
	"\bvalidity\x18\b \x01(\x0e2\x1f.neoline.v1.CertificateValidityR\bvalidity\x12+\n" +
	"\x11staging_untrusted\x18\t \x01(\bR\x10stagingUntrusted\x12#\n" +
	"\rfullchain_pem\x18\n" +
	" \x01(\fR\ffullchainPem\x12&\n" +
	"\x0fprivate_key_pem\x18\v \x01(\fR\rprivateKeyPem\"\x9a\x01\n" +
	"\x1bGetCertificateBundleRequest\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\x12E\n" +
	"\fversion_slot\x18\x02 \x01(\x0e2\".neoline.v1.CertificateVersionSlotR\vversionSlot\"u\n" +
	"\x1eActivatePreviousVersionRequest\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"c\n" +
	"\x1fActivatePreviousVersionResponse\x12@\n" +
	"\vcertificate\x18\x01 \x01(\v2\x1e.neoline.v1.ManagedCertificateR\vcertificate\"U\n" +
	"\x1cGetCertificateBundleResponse\x125\n" +
	"\x06bundle\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateBundleR\x06bundle\"S\n" +
	"\x1bSubmitIssueOperationRequest\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\"^\n" +
	"\x1cSubmitIssueOperationResponse\x12>\n" +
	"\toperation\x18\x01 \x01(\v2 .neoline.v1.CertificateOperationR\toperation\"\xd8\a\n" +
	"\x12ManagedCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x122\n" +
	"\x15certificate_issuer_id\x18\x04 \x01(\tR\x13certificateIssuerId\x125\n" +
	"\x17dns_provider_account_id\x18\x05 \x01(\tR\x14dnsProviderAccountId\x129\n" +
	"\bkey_type\x18\x06 \x01(\x0e2\x1e.neoline.v1.CertificateKeyTypeR\akeyType\x121\n" +
	"\x12auto_renew_enabled\x18\a \x01(\bH\x00R\x10autoRenewEnabled\x88\x01\x01\x12*\n" +
	"\x11renew_before_days\x18\b \x01(\rR\x0frenewBeforeDays\x12(\n" +
	"\x10notify_group_ids\x18\t \x03(\tR\x0enotifyGroupIds\x12\x1d\n" +
	"\n" +
	"server_ids\x18\n" +
	" \x03(\tR\tserverIds\x12H\n" +
	"\x0factive_validity\x18\v \x01(\x0e2\x1f.neoline.v1.CertificateValidityR\x0eactiveValidity\x12)\n" +
	"\x10bundle_available\x18\f \x01(\bR\x0fbundleAvailable\x12K\n" +
	"\x10latest_operation\x18\r \x01(\v2 .neoline.v1.CertificateOperationR\x0flatestOperation\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12M\n" +
	"\x0eactive_version\x18\x10 \x01(\v2&.neoline.v1.CertificateVersionMetadataR\ractiveVersion\x12Q\n" +
	"\x10previous_version\x18\x11 \x01(\v2&.neoline.v1.CertificateVersionMetadataR\x0fpreviousVersion\x12E\n" +
	"\x1fhas_unpublished_desired_changes\x18\x12 \x01(\bR\x1chasUnpublishedDesiredChangesB\x15\n" +
	"\x13_auto_renew_enabled\"\\\n" +
	"\x1eListManagedCertificatesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8d\x01\n" +
	"\x1fListManagedCertificatesResponse\x12B\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1e.neoline.v1.ManagedCertificateR\fcertificates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"c\n" +
	"\x1fCreateManagedCertificateRequest\x12@\n" +
	"\vcertificate\x18\x01 \x01(\v2\x1e.neoline.v1.ManagedCertificateR\vcertificate\"d\n" +
	" CreateManagedCertificateResponse\x12@\n" +
	"\vcertificate\x18\x01 \x01(\v2\x1e.neoline.v1.ManagedCertificateR\vcertificate\"T\n" +
	"\x1cGetManagedCertificateRequest\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\"a\n" +
	"\x1dGetManagedCertificateResponse\x12@\n" +
	"\vcertificate\x18\x01 \x01(\v2\x1e.neoline.v1.ManagedCertificateR\vcertificate\"\x99\x01\n" +
	"\x1fUpdateManagedCertificateRequest\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\x12@\n" +
	"\vcertificate\x18\x02 \x01(\v2\x1e.neoline.v1.ManagedCertificateR\vcertificate\"d\n" +
	" UpdateManagedCertificateResponse\x12@\n" +
	"\vcertificate\x18\x01 \x01(\v2\x1e.neoline.v1.ManagedCertificateR\vcertificate*\x7f\n" +
	"\x12CertificateKeyType\x12$\n" +
	" CERTIFICATE_KEY_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCERTIFICATE_KEY_TYPE_EC_P256\x10\x01\x12!\n" +
	"\x1dCERTIFICATE_KEY_TYPE_RSA_2048\x10\x02*\xe7\x01\n" +
	"\x13CertificateValidity\x12$\n" +
	" CERTIFICATE_VALIDITY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCERTIFICATE_VALIDITY_MISSING\x10\x01\x12\x1e\n" +
	"\x1aCERTIFICATE_VALIDITY_VALID\x10\x02\x12$\n" +
	" CERTIFICATE_VALIDITY_RENEWAL_DUE\x10\x03\x12 \n" +
	"\x1cCERTIFICATE_VALIDITY_EXPIRED\x10\x04\x12 \n" +
	"\x1cCERTIFICATE_VALIDITY_REVOKED\x10\x05*\xb9\x01\n" +
	"\x18CertificateOperationType\x12*\n" +
	"&CERTIFICATE_OPERATION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" CERTIFICATE_OPERATION_TYPE_ISSUE\x10\x01\x12$\n" +
	" CERTIFICATE_OPERATION_TYPE_RENEW\x10\x02\x12%\n" +
	"!CERTIFICATE_OPERATION_TYPE_REVOKE\x10\x03*\xf3\x01\n" +
	"\x1aCertificateOperationStatus\x12,\n" +
	"(CERTIFICATE_OPERATION_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$CERTIFICATE_OPERATION_STATUS_PENDING\x10\x01\x12(\n" +
	"$CERTIFICATE_OPERATION_STATUS_RUNNING\x10\x02\x12*\n" +
	"&CERTIFICATE_OPERATION_STATUS_SUCCEEDED\x10\x03\x12'\n" +
	"#CERTIFICATE_OPERATION_STATUS_FAILED\x10\x04*\x8e\x01\n" +
	"\x16CertificateVersionSlot\x12(\n" +
	"$CERTIFICATE_VERSION_SLOT_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fCERTIFICATE_VERSION_SLOT_ACTIVE\x10\x01\x12%\n" +
	"!CERTIFICATE_VERSION_SLOT_PREVIOUS\x10\x022\xc3\x06\n" +
	"\x19ManagedCertificateService\x12t\n" +
	"\x17ListManagedCertificates\x12*.neoline.v1.ListManagedCertificatesRequest\x1a+.neoline.v1.ListManagedCertificatesResponse\"\x00\x12w\n" +
	"\x18CreateManagedCertificate\x12+.neoline.v1.CreateManagedCertificateRequest\x1a,.neoline.v1.CreateManagedCertificateResponse\"\x00\x12n\n" +
	"\x15GetManagedCertificate\x12(.neoline.v1.GetManagedCertificateRequest\x1a).neoline.v1.GetManagedCertificateResponse\"\x00\x12w\n" +
	"\x18UpdateManagedCertificate\x12+.neoline.v1.UpdateManagedCertificateRequest\x1a,.neoline.v1.UpdateManagedCertificateResponse\"\x00\x12k\n" +
	"\x14SubmitIssueOperation\x12'.neoline.v1.SubmitIssueOperationRequest\x1a(.neoline.v1.SubmitIssueOperationResponse\"\x00\x12k\n" +
	"\x14GetCertificateBundle\x12'.neoline.v1.GetCertificateBundleRequest\x1a(.neoline.v1.GetCertificateBundleResponse\"\x00\x12t\n" +
	"\x17ActivatePreviousVersion\x12*.neoline.v1.ActivatePreviousVersionRequest\x1a+.neoline.v1.ActivatePreviousVersionResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_managed_certificate_proto_rawDescOnce sync.Once
	file_neoline_v1_managed_certificate_proto_rawDescData []byte
)

func file_neoline_v1_managed_certificate_proto_rawDescGZIP() []byte {
	file_neoline_v1_managed_certificate_proto_rawDescOnce.Do(func() {
		file_neoline_v1_managed_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_managed_certificate_proto_rawDesc), len(file_neoline_v1_managed_certificate_proto_rawDesc)))
	})
	return file_neoline_v1_managed_certificate_proto_rawDescData
}

var file_neoline_v1_managed_certificate_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_neoline_v1_managed_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_neoline_v1_managed_certificate_proto_goTypes = []any{
	(CertificateKeyType)(0),                  // 0: neoline.v1.CertificateKeyType
	(CertificateValidity)(0),                 // 1: neoline.v1.CertificateValidity
	(CertificateOperationType)(0),            // 2: neoline.v1.CertificateOperationType
	(CertificateOperationStatus)(0),          // 3: neoline.v1.CertificateOperationStatus
	(CertificateVersionSlot)(0),              // 4: neoline.v1.CertificateVersionSlot
	(*IssueConfigSnapshot)(nil),              // 5: neoline.v1.IssueConfigSnapshot
	(*CertificateOperation)(nil),             // 6: neoline.v1.CertificateOperation
	(*CertificateVersionMetadata)(nil),       // 7: neoline.v1.CertificateVersionMetadata
	(*CertificateBundle)(nil),                // 8: neoline.v1.CertificateBundle
	(*GetCertificateBundleRequest)(nil),      // 9: neoline.v1.GetCertificateBundleRequest
	(*ActivatePreviousVersionRequest)(nil),   // 10: neoline.v1.ActivatePreviousVersionRequest
	(*ActivatePreviousVersionResponse)(nil),  // 11: neoline.v1.ActivatePreviousVersionResponse
	(*GetCertificateBundleResponse)(nil),     // 12: neoline.v1.GetCertificateBundleResponse
	(*SubmitIssueOperationRequest)(nil),      // 13: neoline.v1.SubmitIssueOperationRequest
	(*SubmitIssueOperationResponse)(nil),     // 14: neoline.v1.SubmitIssueOperationResponse
	(*ManagedCertificate)(nil),               // 15: neoline.v1.ManagedCertificate
	(*ListManagedCertificatesRequest)(nil),   // 16: neoline.v1.ListManagedCertificatesRequest
	(*ListManagedCertificatesResponse)(nil),  // 17: neoline.v1.ListManagedCertificatesResponse
	(*CreateManagedCertificateRequest)(nil),  // 18: neoline.v1.CreateManagedCertificateRequest
	(*CreateManagedCertificateResponse)(nil), // 19: neoline.v1.CreateManagedCertificateResponse
	(*GetManagedCertificateRequest)(nil),     // 20: neoline.v1.GetManagedCertificateRequest
	(*GetManagedCertificateResponse)(nil),    // 21: neoline.v1.GetManagedCertificateResponse
	(*UpdateManagedCertificateRequest)(nil),  // 22: neoline.v1.UpdateManagedCertificateRequest
	(*UpdateManagedCertificateResponse)(nil), // 23: neoline.v1.UpdateManagedCertificateResponse
	(*timestamppb.Timestamp)(nil),            // 24: google.protobuf.Timestamp
}
var file_neoline_v1_managed_certificate_proto_depIdxs = []int32{
	0,  // 0: neoline.v1.IssueConfigSnapshot.key_type:type_name -> neoline.v1.CertificateKeyType
	2,  // 1: neoline.v1.CertificateOperation.type:type_name -> neoline.v1.CertificateOperationType
	3,  // 2: neoline.v1.CertificateOperation.status:type_name -> neoline.v1.CertificateOperationStatus
	5,  // 3: neoline.v1.CertificateOperation.config_snapshot:type_name -> neoline.v1.IssueConfigSnapshot
	24, // 4: neoline.v1.CertificateOperation.started_at:type_name -> google.protobuf.Timestamp
	24, // 5: neoline.v1.CertificateOperation.finished_at:type_name -> google.protobuf.Timestamp
	24, // 6: neoline.v1.CertificateOperation.next_attempt_at:type_name -> google.protobuf.Timestamp
	24, // 7: neoline.v1.CertificateOperation.created_at:type_name -> google.protobuf.Timestamp
	24, // 8: neoline.v1.CertificateOperation.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 9: neoline.v1.CertificateVersionMetadata.config_snapshot:type_name -> neoline.v1.IssueConfigSnapshot
	24, // 10: neoline.v1.CertificateVersionMetadata.not_before:type_name -> google.protobuf.Timestamp
	24, // 11: neoline.v1.CertificateVersionMetadata.not_after:type_name -> google.protobuf.Timestamp
	0,  // 12: neoline.v1.CertificateVersionMetadata.key_type:type_name -> neoline.v1.CertificateKeyType
	24, // 13: neoline.v1.CertificateVersionMetadata.created_at:type_name -> google.protobuf.Timestamp
	24, // 14: neoline.v1.CertificateVersionMetadata.revoked_at:type_name -> google.protobuf.Timestamp
	0,  // 15: neoline.v1.CertificateBundle.key_type:type_name -> neoline.v1.CertificateKeyType
	24, // 16: neoline.v1.CertificateBundle.not_before:type_name -> google.protobuf.Timestamp
	24, // 17: neoline.v1.CertificateBundle.not_after:type_name -> google.protobuf.Timestamp
	1,  // 18: neoline.v1.CertificateBundle.validity:type_name -> neoline.v1.CertificateValidity
	4,  // 19: neoline.v1.GetCertificateBundleRequest.version_slot:type_name -> neoline.v1.CertificateVersionSlot
	15, // 20: neoline.v1.ActivatePreviousVersionResponse.certificate:type_name -> neoline.v1.ManagedCertificate
	8,  // 21: neoline.v1.GetCertificateBundleResponse.bundle:type_name -> neoline.v1.CertificateBundle
	6,  // 22: neoline.v1.SubmitIssueOperationResponse.operation:type_name -> neoline.v1.CertificateOperation
	0,  // 23: neoline.v1.ManagedCertificate.key_type:type_name -> neoline.v1.CertificateKeyType
	1,  // 24: neoline.v1.ManagedCertificate.active_validity:type_name -> neoline.v1.CertificateValidity
	6,  // 25: neoline.v1.ManagedCertificate.latest_operation:type_name -> neoline.v1.CertificateOperation
	24, // 26: neoline.v1.ManagedCertificate.created_at:type_name -> google.protobuf.Timestamp
	24, // 27: neoline.v1.ManagedCertificate.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 28: neoline.v1.ManagedCertificate.active_version:type_name -> neoline.v1.CertificateVersionMetadata
	7,  // 29: neoline.v1.ManagedCertificate.previous_version:type_name -> neoline.v1.CertificateVersionMetadata
	15, // 30: neoline.v1.ListManagedCertificatesResponse.certificates:type_name -> neoline.v1.ManagedCertificate
	15, // 31: neoline.v1.CreateManagedCertificateRequest.certificate:type_name -> neoline.v1.ManagedCertificate
	15, // 32: neoline.v1.CreateManagedCertificateResponse.certificate:type_name -> neoline.v1.ManagedCertificate
	15, // 33: neoline.v1.GetManagedCertificateResponse.certificate:type_name -> neoline.v1.ManagedCertificate
	15, // 34: neoline.v1.UpdateManagedCertificateRequest.certificate:type_name -> neoline.v1.ManagedCertificate
	15, // 35: neoline.v1.UpdateManagedCertificateResponse.certificate:type_name -> neoline.v1.ManagedCertificate
	16, // 36: neoline.v1.ManagedCertificateService.ListManagedCertificates:input_type -> neoline.v1.ListManagedCertificatesRequest
	18, // 37: neoline.v1.ManagedCertificateService.CreateManagedCertificate:input_type -> neoline.v1.CreateManagedCertificateRequest
	20, // 38: neoline.v1.ManagedCertificateService.GetManagedCertificate:input_type -> neoline.v1.GetManagedCertificateRequest
	22, // 39: neoline.v1.ManagedCertificateService.UpdateManagedCertificate:input_type -> neoline.v1.UpdateManagedCertificateRequest
	13, // 40: neoline.v1.ManagedCertificateService.SubmitIssueOperation:input_type -> neoline.v1.SubmitIssueOperationRequest
	9,  // 41: neoline.v1.ManagedCertificateService.GetCertificateBundle:input_type -> neoline.v1.GetCertificateBundleRequest
	10, // 42: neoline.v1.ManagedCertificateService.ActivatePreviousVersion:input_type -> neoline.v1.ActivatePreviousVersionRequest
	17, // 43: neoline.v1.ManagedCertificateService.ListManagedCertificates:output_type -> neoline.v1.ListManagedCertificatesResponse
	19, // 44: neoline.v1.ManagedCertificateService.CreateManagedCertificate:output_type -> neoline.v1.CreateManagedCertificateResponse
	21, // 45: neoline.v1.ManagedCertificateService.GetManagedCertificate:output_type -> neoline.v1.GetManagedCertificateResponse
	23, // 46: neoline.v1.ManagedCertificateService.UpdateManagedCertificate:output_type -> neoline.v1.UpdateManagedCertificateResponse
	14, // 47: neoline.v1.ManagedCertificateService.SubmitIssueOperation:output_type -> neoline.v1.SubmitIssueOperationResponse
	12, // 48: neoline.v1.ManagedCertificateService.GetCertificateBundle:output_type -> neoline.v1.GetCertificateBundleResponse
	11, // 49: neoline.v1.ManagedCertificateService.ActivatePreviousVersion:output_type -> neoline.v1.ActivatePreviousVersionResponse
	43, // [43:50] is the sub-list for method output_type
	36, // [36:43] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_neoline_v1_managed_certificate_proto_init() }
func file_neoline_v1_managed_certificate_proto_init() {
	if File_neoline_v1_managed_certificate_proto != nil {
		return
	}
	file_neoline_v1_managed_certificate_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_managed_certificate_proto_rawDesc), len(file_neoline_v1_managed_certificate_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_managed_certificate_proto_goTypes,
		DependencyIndexes: file_neoline_v1_managed_certificate_proto_depIdxs,
		EnumInfos:         file_neoline_v1_managed_certificate_proto_enumTypes,
		MessageInfos:      file_neoline_v1_managed_certificate_proto_msgTypes,
	}.Build()
	File_neoline_v1_managed_certificate_proto = out.File
	file_neoline_v1_managed_certificate_proto_goTypes = nil
	file_neoline_v1_managed_certificate_proto_depIdxs = nil
}
