// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neoline/v1/mcp_token.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// McpToken is an issued MCP API token. The plaintext secret is returned only
// once on creation and is never stored.
type McpToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpToken) Reset() {
	*x = McpToken{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpToken) ProtoMessage() {}

func (x *McpToken) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpToken.ProtoReflect.Descriptor instead.
func (*McpToken) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{0}
}

func (x *McpToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *McpToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *McpToken) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *McpToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *McpToken) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

type ListMcpTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMcpTokensRequest) Reset() {
	*x = ListMcpTokensRequest{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMcpTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMcpTokensRequest) ProtoMessage() {}

func (x *ListMcpTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMcpTokensRequest.ProtoReflect.Descriptor instead.
func (*ListMcpTokensRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{1}
}

type ListMcpTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*McpToken            `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMcpTokensResponse) Reset() {
	*x = ListMcpTokensResponse{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMcpTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMcpTokensResponse) ProtoMessage() {}

func (x *ListMcpTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMcpTokensResponse.ProtoReflect.Descriptor instead.
func (*ListMcpTokensResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{2}
}

func (x *ListMcpTokensResponse) GetTokens() []*McpToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CreateMcpTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMcpTokenRequest) Reset() {
	*x = CreateMcpTokenRequest{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMcpTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMcpTokenRequest) ProtoMessage() {}

func (x *CreateMcpTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMcpTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateMcpTokenRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMcpTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMcpTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *McpToken              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMcpTokenResponse) Reset() {
	*x = CreateMcpTokenResponse{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMcpTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMcpTokenResponse) ProtoMessage() {}

func (x *CreateMcpTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMcpTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateMcpTokenResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMcpTokenResponse) GetToken() *McpToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateMcpTokenResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeleteMcpTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMcpTokenRequest) Reset() {
	*x = DeleteMcpTokenRequest{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMcpTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMcpTokenRequest) ProtoMessage() {}

func (x *DeleteMcpTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMcpTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteMcpTokenRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMcpTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type DeleteMcpTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMcpTokenResponse) Reset() {
	*x = DeleteMcpTokenResponse{}
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMcpTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMcpTokenResponse) ProtoMessage() {}

func (x *DeleteMcpTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_mcp_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMcpTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteMcpTokenResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_mcp_token_proto_rawDescGZIP(), []int{6}
}

var File_neoline_v1_mcp_token_proto protoreflect.FileDescriptor

const file_neoline_v1_mcp_token_proto_rawDesc = "" +
	"\n" +
	"\x1aneoline/v1/mcp_token.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\bMcpToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\"\x16\n" +
	"\x14ListMcpTokensRequest\"E\n" +
	"\x15ListMcpTokensResponse\x12,\n" +
	"\x06tokens\x18\x01 \x03(\v2\x14.neoline.v1.McpTokenR\x06tokens\"+\n" +
	"\x15CreateMcpTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x16CreateMcpTokenResponse\x12*\n" +
	"\x05token\x18\x01 \x01(\v2\x14.neoline.v1.McpTokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"2\n" +
	"\x15DeleteMcpTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"\x18\n" +
	"\x16DeleteMcpTokenResponse2\x9f\x02\n" +
	"\x0fMcpTokenService\x12V\n" +
	"\rListMcpTokens\x12 .neoline.v1.ListMcpTokensRequest\x1a!.neoline.v1.ListMcpTokensResponse\"\x00\x12Y\n" +
	"\x0eCreateMcpToken\x12!.neoline.v1.CreateMcpTokenRequest\x1a\".neoline.v1.CreateMcpTokenResponse\"\x00\x12Y\n" +
	"\x0eDeleteMcpToken\x12!.neoline.v1.DeleteMcpTokenRequest\x1a\".neoline.v1.DeleteMcpTokenResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_mcp_token_proto_rawDescOnce sync.Once
	file_neoline_v1_mcp_token_proto_rawDescData []byte
)

func file_neoline_v1_mcp_token_proto_rawDescGZIP() []byte {
	file_neoline_v1_mcp_token_proto_rawDescOnce.Do(func() {
		file_neoline_v1_mcp_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_mcp_token_proto_rawDesc), len(file_neoline_v1_mcp_token_proto_rawDesc)))
	})
	return file_neoline_v1_mcp_token_proto_rawDescData
}

var file_neoline_v1_mcp_token_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_neoline_v1_mcp_token_proto_goTypes = []any{
	(*McpToken)(nil),               // 0: neoline.v1.McpToken
	(*ListMcpTokensRequest)(nil),   // 1: neoline.v1.ListMcpTokensRequest
	(*ListMcpTokensResponse)(nil),  // 2: neoline.v1.ListMcpTokensResponse
	(*CreateMcpTokenRequest)(nil),  // 3: neoline.v1.CreateMcpTokenRequest
	(*CreateMcpTokenResponse)(nil), // 4: neoline.v1.CreateMcpTokenResponse
	(*DeleteMcpTokenRequest)(nil),  // 5: neoline.v1.DeleteMcpTokenRequest
	(*DeleteMcpTokenResponse)(nil), // 6: neoline.v1.DeleteMcpTokenResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_neoline_v1_mcp_token_proto_depIdxs = []int32{
	7, // 0: neoline.v1.McpToken.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: neoline.v1.McpToken.last_used_at:type_name -> google.protobuf.Timestamp
	0, // 2: neoline.v1.ListMcpTokensResponse.tokens:type_name -> neoline.v1.McpToken
	0, // 3: neoline.v1.CreateMcpTokenResponse.token:type_name -> neoline.v1.McpToken
	1, // 4: neoline.v1.McpTokenService.ListMcpTokens:input_type -> neoline.v1.ListMcpTokensRequest
	3, // 5: neoline.v1.McpTokenService.CreateMcpToken:input_type -> neoline.v1.CreateMcpTokenRequest
	5, // 6: neoline.v1.McpTokenService.DeleteMcpToken:input_type -> neoline.v1.DeleteMcpTokenRequest
	2, // 7: neoline.v1.McpTokenService.ListMcpTokens:output_type -> neoline.v1.ListMcpTokensResponse
	4, // 8: neoline.v1.McpTokenService.CreateMcpToken:output_type -> neoline.v1.CreateMcpTokenResponse
	6, // 9: neoline.v1.McpTokenService.DeleteMcpToken:output_type -> neoline.v1.DeleteMcpTokenResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_neoline_v1_mcp_token_proto_init() }
func file_neoline_v1_mcp_token_proto_init() {
	if File_neoline_v1_mcp_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_mcp_token_proto_rawDesc), len(file_neoline_v1_mcp_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_mcp_token_proto_goTypes,
		DependencyIndexes: file_neoline_v1_mcp_token_proto_depIdxs,
		MessageInfos:      file_neoline_v1_mcp_token_proto_msgTypes,
	}.Build()
	File_neoline_v1_mcp_token_proto = out.File
	file_neoline_v1_mcp_token_proto_goTypes = nil
	file_neoline_v1_mcp_token_proto_depIdxs = nil
}
