// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neoline/v1/monitor_group.proto

package neolinev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertChannel describes a single delivery target for an AlertPolicy. The
// initial supported type is "webhook", which POSTs a JSON payload to target.
type AlertChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertChannel) Reset() {
	*x = AlertChannel{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertChannel) ProtoMessage() {}

func (x *AlertChannel) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertChannel.ProtoReflect.Descriptor instead.
func (*AlertChannel) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{0}
}

func (x *AlertChannel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertChannel) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AlertChannel) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// AlertPolicy is the group-level configuration that drives alert dispatch when
// any monitor in the group transitions between health states.
type AlertPolicy struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Enabled    bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Channels   []*AlertChannel        `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	OnDown     bool                   `protobuf:"varint,3,opt,name=on_down,json=onDown,proto3" json:"on_down,omitempty"`
	OnRecover  bool                   `protobuf:"varint,4,opt,name=on_recover,json=onRecover,proto3" json:"on_recover,omitempty"`
	OnWarning  bool                   `protobuf:"varint,5,opt,name=on_warning,json=onWarning,proto3" json:"on_warning,omitempty"`
	OnCritical bool                   `protobuf:"varint,6,opt,name=on_critical,json=onCritical,proto3" json:"on_critical,omitempty"`
	// min_interval_seconds throttles alerts so the same (group, monitor) pair
	// does not fire more often than this window. Zero disables throttling.
	MinIntervalSeconds uint32 `protobuf:"varint,7,opt,name=min_interval_seconds,json=minIntervalSeconds,proto3" json:"min_interval_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AlertPolicy) Reset() {
	*x = AlertPolicy{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertPolicy) ProtoMessage() {}

func (x *AlertPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertPolicy.ProtoReflect.Descriptor instead.
func (*AlertPolicy) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{1}
}

func (x *AlertPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertPolicy) GetChannels() []*AlertChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *AlertPolicy) GetOnDown() bool {
	if x != nil {
		return x.OnDown
	}
	return false
}

func (x *AlertPolicy) GetOnRecover() bool {
	if x != nil {
		return x.OnRecover
	}
	return false
}

func (x *AlertPolicy) GetOnWarning() bool {
	if x != nil {
		return x.OnWarning
	}
	return false
}

func (x *AlertPolicy) GetOnCritical() bool {
	if x != nil {
		return x.OnCritical
	}
	return false
}

func (x *AlertPolicy) GetMinIntervalSeconds() uint32 {
	if x != nil {
		return x.MinIntervalSeconds
	}
	return 0
}

// MonitorGroup is a flat, named bucket of monitors. A monitor may belong to
// multiple groups, and each group carries its own alert policy.
type MonitorGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AlertPolicy   *AlertPolicy           `protobuf:"bytes,4,opt,name=alert_policy,json=alertPolicy,proto3" json:"alert_policy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorGroup) Reset() {
	*x = MonitorGroup{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorGroup) ProtoMessage() {}

func (x *MonitorGroup) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorGroup.ProtoReflect.Descriptor instead.
func (*MonitorGroup) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{2}
}

func (x *MonitorGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonitorGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MonitorGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MonitorGroup) GetAlertPolicy() *AlertPolicy {
	if x != nil {
		return x.AlertPolicy
	}
	return nil
}

func (x *MonitorGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MonitorGroup) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListMonitorGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorGroupsRequest) Reset() {
	*x = ListMonitorGroupsRequest{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorGroupsRequest) ProtoMessage() {}

func (x *ListMonitorGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListMonitorGroupsRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{3}
}

func (x *ListMonitorGroupsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMonitorGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMonitorGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*MonitorGroup        `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorGroupsResponse) Reset() {
	*x = ListMonitorGroupsResponse{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorGroupsResponse) ProtoMessage() {}

func (x *ListMonitorGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListMonitorGroupsResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{4}
}

func (x *ListMonitorGroupsResponse) GetGroups() []*MonitorGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListMonitorGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateMonitorGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *MonitorGroup          `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMonitorGroupRequest) Reset() {
	*x = CreateMonitorGroupRequest{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorGroupRequest) ProtoMessage() {}

func (x *CreateMonitorGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateMonitorGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMonitorGroupRequest) GetGroup() *MonitorGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type CreateMonitorGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *MonitorGroup          `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMonitorGroupResponse) Reset() {
	*x = CreateMonitorGroupResponse{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMonitorGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMonitorGroupResponse) ProtoMessage() {}

func (x *CreateMonitorGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMonitorGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateMonitorGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMonitorGroupResponse) GetGroup() *MonitorGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetMonitorGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorGroupRequest) Reset() {
	*x = GetMonitorGroupRequest{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorGroupRequest) ProtoMessage() {}

func (x *GetMonitorGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorGroupRequest.ProtoReflect.Descriptor instead.
func (*GetMonitorGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{7}
}

func (x *GetMonitorGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetMonitorGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *MonitorGroup          `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonitorGroupResponse) Reset() {
	*x = GetMonitorGroupResponse{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonitorGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonitorGroupResponse) ProtoMessage() {}

func (x *GetMonitorGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonitorGroupResponse.ProtoReflect.Descriptor instead.
func (*GetMonitorGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{8}
}

func (x *GetMonitorGroupResponse) GetGroup() *MonitorGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateMonitorGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Group         *MonitorGroup          `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMonitorGroupRequest) Reset() {
	*x = UpdateMonitorGroupRequest{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMonitorGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonitorGroupRequest) ProtoMessage() {}

func (x *UpdateMonitorGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonitorGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateMonitorGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMonitorGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateMonitorGroupRequest) GetGroup() *MonitorGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateMonitorGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *MonitorGroup          `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMonitorGroupResponse) Reset() {
	*x = UpdateMonitorGroupResponse{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMonitorGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMonitorGroupResponse) ProtoMessage() {}

func (x *UpdateMonitorGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMonitorGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateMonitorGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMonitorGroupResponse) GetGroup() *MonitorGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteMonitorGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMonitorGroupRequest) Reset() {
	*x = DeleteMonitorGroupRequest{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMonitorGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorGroupRequest) ProtoMessage() {}

func (x *DeleteMonitorGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteMonitorGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMonitorGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteMonitorGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMonitorGroupResponse) Reset() {
	*x = DeleteMonitorGroupResponse{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMonitorGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMonitorGroupResponse) ProtoMessage() {}

func (x *DeleteMonitorGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMonitorGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteMonitorGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{12}
}

type ListMonitorsByGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorsByGroupRequest) Reset() {
	*x = ListMonitorsByGroupRequest{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorsByGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorsByGroupRequest) ProtoMessage() {}

func (x *ListMonitorsByGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorsByGroupRequest.ProtoReflect.Descriptor instead.
func (*ListMonitorsByGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{13}
}

func (x *ListMonitorsByGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListMonitorsByGroupRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMonitorsByGroupRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMonitorsByGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitors      []*Monitor             `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonitorsByGroupResponse) Reset() {
	*x = ListMonitorsByGroupResponse{}
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonitorsByGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonitorsByGroupResponse) ProtoMessage() {}

func (x *ListMonitorsByGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_monitor_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonitorsByGroupResponse.ProtoReflect.Descriptor instead.
func (*ListMonitorsByGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_monitor_group_proto_rawDescGZIP(), []int{14}
}

func (x *ListMonitorsByGroupResponse) GetMonitors() []*Monitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

func (x *ListMonitorsByGroupResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_neoline_v1_monitor_group_proto protoreflect.FileDescriptor

const file_neoline_v1_monitor_group_proto_rawDesc = "" +
	"\n" +
	"\x1eneoline/v1/monitor_group.proto\x12\n" +
	"neoline.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18neoline/v1/monitor.proto\"\xaf\x01\n" +
	"\fAlertChannel\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x129\n" +
	"\x05extra\x18\x03 \x03(\v2#.neoline.v1.AlertChannel.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\vAlertPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x124\n" +
	"\bchannels\x18\x02 \x03(\v2\x18.neoline.v1.AlertChannelR\bchannels\x12\x17\n" +
	"\aon_down\x18\x03 \x01(\bR\x06onDown\x12\x1d\n" +
	"\n" +
	"on_recover\x18\x04 \x01(\bR\tonRecover\x12\x1d\n" +
	"\n" +
	"on_warning\x18\x05 \x01(\bR\tonWarning\x12\x1f\n" +
	"\von_critical\x18\x06 \x01(\bR\n" +
	"onCritical\x120\n" +
	"\x14min_interval_seconds\x18\a \x01(\rR\x12minIntervalSeconds\"\x86\x02\n" +
	"\fMonitorGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\falert_policy\x18\x04 \x01(\v2\x17.neoline.v1.AlertPolicyR\valertPolicy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"V\n" +
	"\x18ListMonitorGroupsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"u\n" +
	"\x19ListMonitorGroupsResponse\x120\n" +
	"\x06groups\x18\x01 \x03(\v2\x18.neoline.v1.MonitorGroupR\x06groups\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"K\n" +
	"\x19CreateMonitorGroupRequest\x12.\n" +
	"\x05group\x18\x01 \x01(\v2\x18.neoline.v1.MonitorGroupR\x05group\"L\n" +
	"\x1aCreateMonitorGroupResponse\x12.\n" +
	"\x05group\x18\x01 \x01(\v2\x18.neoline.v1.MonitorGroupR\x05group\"3\n" +
	"\x16GetMonitorGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"I\n" +
	"\x17GetMonitorGroupResponse\x12.\n" +
	"\x05group\x18\x01 \x01(\v2\x18.neoline.v1.MonitorGroupR\x05group\"f\n" +
	"\x19UpdateMonitorGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12.\n" +
	"\x05group\x18\x02 \x01(\v2\x18.neoline.v1.MonitorGroupR\x05group\"L\n" +
	"\x1aUpdateMonitorGroupResponse\x12.\n" +
	"\x05group\x18\x01 \x01(\v2\x18.neoline.v1.MonitorGroupR\x05group\"6\n" +
	"\x19DeleteMonitorGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x1c\n" +
	"\x1aDeleteMonitorGroupResponse\"s\n" +
	"\x1aListMonitorsByGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"v\n" +
	"\x1bListMonitorsByGroupResponse\x12/\n" +
	"\bmonitors\x18\x01 \x03(\v2\x13.neoline.v1.MonitorR\bmonitors\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xda\x06\n" +
	"\x13MonitorGroupService\x12|\n" +
	"\x11ListMonitorGroups\x12$.neoline.v1.ListMonitorGroupsRequest\x1a%.neoline.v1.ListMonitorGroupsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/monitor-groups\x12\x86\x01\n" +
	"\x12CreateMonitorGroup\x12%.neoline.v1.CreateMonitorGroupRequest\x1a&.neoline.v1.CreateMonitorGroupResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x05group\"\x12/v1/monitor-groups\x12\x81\x01\n" +
	"\x0fGetMonitorGroup\x12\".neoline.v1.GetMonitorGroupRequest\x1a#.neoline.v1.GetMonitorGroupResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/monitor-groups/{group_id}\x12\x91\x01\n" +
	"\x12UpdateMonitorGroup\x12%.neoline.v1.UpdateMonitorGroupRequest\x1a&.neoline.v1.UpdateMonitorGroupResponse\",\x82\xd3\xe4\x93\x02&:\x05group\x1a\x1d/v1/monitor-groups/{group_id}\x12\x8a\x01\n" +
	"\x12DeleteMonitorGroup\x12%.neoline.v1.DeleteMonitorGroupRequest\x1a&.neoline.v1.DeleteMonitorGroupResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/monitor-groups/{group_id}\x12\x96\x01\n" +
	"\x13ListMonitorsByGroup\x12&.neoline.v1.ListMonitorsByGroupRequest\x1a'.neoline.v1.ListMonitorsByGroupResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/monitor-groups/{group_id}/monitorsB;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_monitor_group_proto_rawDescOnce sync.Once
	file_neoline_v1_monitor_group_proto_rawDescData []byte
)

func file_neoline_v1_monitor_group_proto_rawDescGZIP() []byte {
	file_neoline_v1_monitor_group_proto_rawDescOnce.Do(func() {
		file_neoline_v1_monitor_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_monitor_group_proto_rawDesc), len(file_neoline_v1_monitor_group_proto_rawDesc)))
	})
	return file_neoline_v1_monitor_group_proto_rawDescData
}

var file_neoline_v1_monitor_group_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_neoline_v1_monitor_group_proto_goTypes = []any{
	(*AlertChannel)(nil),                // 0: neoline.v1.AlertChannel
	(*AlertPolicy)(nil),                 // 1: neoline.v1.AlertPolicy
	(*MonitorGroup)(nil),                // 2: neoline.v1.MonitorGroup
	(*ListMonitorGroupsRequest)(nil),    // 3: neoline.v1.ListMonitorGroupsRequest
	(*ListMonitorGroupsResponse)(nil),   // 4: neoline.v1.ListMonitorGroupsResponse
	(*CreateMonitorGroupRequest)(nil),   // 5: neoline.v1.CreateMonitorGroupRequest
	(*CreateMonitorGroupResponse)(nil),  // 6: neoline.v1.CreateMonitorGroupResponse
	(*GetMonitorGroupRequest)(nil),      // 7: neoline.v1.GetMonitorGroupRequest
	(*GetMonitorGroupResponse)(nil),     // 8: neoline.v1.GetMonitorGroupResponse
	(*UpdateMonitorGroupRequest)(nil),   // 9: neoline.v1.UpdateMonitorGroupRequest
	(*UpdateMonitorGroupResponse)(nil),  // 10: neoline.v1.UpdateMonitorGroupResponse
	(*DeleteMonitorGroupRequest)(nil),   // 11: neoline.v1.DeleteMonitorGroupRequest
	(*DeleteMonitorGroupResponse)(nil),  // 12: neoline.v1.DeleteMonitorGroupResponse
	(*ListMonitorsByGroupRequest)(nil),  // 13: neoline.v1.ListMonitorsByGroupRequest
	(*ListMonitorsByGroupResponse)(nil), // 14: neoline.v1.ListMonitorsByGroupResponse
	nil,                                 // 15: neoline.v1.AlertChannel.ExtraEntry
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
	(*Monitor)(nil),                     // 17: neoline.v1.Monitor
}
var file_neoline_v1_monitor_group_proto_depIdxs = []int32{
	15, // 0: neoline.v1.AlertChannel.extra:type_name -> neoline.v1.AlertChannel.ExtraEntry
	0,  // 1: neoline.v1.AlertPolicy.channels:type_name -> neoline.v1.AlertChannel
	1,  // 2: neoline.v1.MonitorGroup.alert_policy:type_name -> neoline.v1.AlertPolicy
	16, // 3: neoline.v1.MonitorGroup.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: neoline.v1.MonitorGroup.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: neoline.v1.ListMonitorGroupsResponse.groups:type_name -> neoline.v1.MonitorGroup
	2,  // 6: neoline.v1.CreateMonitorGroupRequest.group:type_name -> neoline.v1.MonitorGroup
	2,  // 7: neoline.v1.CreateMonitorGroupResponse.group:type_name -> neoline.v1.MonitorGroup
	2,  // 8: neoline.v1.GetMonitorGroupResponse.group:type_name -> neoline.v1.MonitorGroup
	2,  // 9: neoline.v1.UpdateMonitorGroupRequest.group:type_name -> neoline.v1.MonitorGroup
	2,  // 10: neoline.v1.UpdateMonitorGroupResponse.group:type_name -> neoline.v1.MonitorGroup
	17, // 11: neoline.v1.ListMonitorsByGroupResponse.monitors:type_name -> neoline.v1.Monitor
	3,  // 12: neoline.v1.MonitorGroupService.ListMonitorGroups:input_type -> neoline.v1.ListMonitorGroupsRequest
	5,  // 13: neoline.v1.MonitorGroupService.CreateMonitorGroup:input_type -> neoline.v1.CreateMonitorGroupRequest
	7,  // 14: neoline.v1.MonitorGroupService.GetMonitorGroup:input_type -> neoline.v1.GetMonitorGroupRequest
	9,  // 15: neoline.v1.MonitorGroupService.UpdateMonitorGroup:input_type -> neoline.v1.UpdateMonitorGroupRequest
	11, // 16: neoline.v1.MonitorGroupService.DeleteMonitorGroup:input_type -> neoline.v1.DeleteMonitorGroupRequest
	13, // 17: neoline.v1.MonitorGroupService.ListMonitorsByGroup:input_type -> neoline.v1.ListMonitorsByGroupRequest
	4,  // 18: neoline.v1.MonitorGroupService.ListMonitorGroups:output_type -> neoline.v1.ListMonitorGroupsResponse
	6,  // 19: neoline.v1.MonitorGroupService.CreateMonitorGroup:output_type -> neoline.v1.CreateMonitorGroupResponse
	8,  // 20: neoline.v1.MonitorGroupService.GetMonitorGroup:output_type -> neoline.v1.GetMonitorGroupResponse
	10, // 21: neoline.v1.MonitorGroupService.UpdateMonitorGroup:output_type -> neoline.v1.UpdateMonitorGroupResponse
	12, // 22: neoline.v1.MonitorGroupService.DeleteMonitorGroup:output_type -> neoline.v1.DeleteMonitorGroupResponse
	14, // 23: neoline.v1.MonitorGroupService.ListMonitorsByGroup:output_type -> neoline.v1.ListMonitorsByGroupResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_neoline_v1_monitor_group_proto_init() }
func file_neoline_v1_monitor_group_proto_init() {
	if File_neoline_v1_monitor_group_proto != nil {
		return
	}
	file_neoline_v1_monitor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_monitor_group_proto_rawDesc), len(file_neoline_v1_monitor_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_monitor_group_proto_goTypes,
		DependencyIndexes: file_neoline_v1_monitor_group_proto_depIdxs,
		MessageInfos:      file_neoline_v1_monitor_group_proto_msgTypes,
	}.Build()
	File_neoline_v1_monitor_group_proto = out.File
	file_neoline_v1_monitor_group_proto_goTypes = nil
	file_neoline_v1_monitor_group_proto_depIdxs = nil
}
