// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neoline/v1/notify_group.proto

package neolinev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertChannel describes a single delivery target inside a NotifyGroup.
// Supported types: "webhook", "telegram", "discord", "mastodon". The meaning of
// target and extra depends on the type (see docs/monitoring-configuration.md).
type AlertChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertChannel) Reset() {
	*x = AlertChannel{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertChannel) ProtoMessage() {}

func (x *AlertChannel) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertChannel.ProtoReflect.Descriptor instead.
func (*AlertChannel) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{0}
}

func (x *AlertChannel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertChannel) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AlertChannel) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// NotifyGroup is a reusable, named bucket of delivery channels. A MonitorGroup's
// AlertPolicy references one or more NotifyGroups by id; dispatch fans out to
// every channel of every referenced group.
type NotifyGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Channels      []*AlertChannel        `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyGroup) Reset() {
	*x = NotifyGroup{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGroup) ProtoMessage() {}

func (x *NotifyGroup) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGroup.ProtoReflect.Descriptor instead.
func (*NotifyGroup) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NotifyGroup) GetChannels() []*AlertChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *NotifyGroup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotifyGroup) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListNotifyGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotifyGroupsRequest) Reset() {
	*x = ListNotifyGroupsRequest{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotifyGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyGroupsRequest) ProtoMessage() {}

func (x *ListNotifyGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListNotifyGroupsRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotifyGroupsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotifyGroupsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNotifyGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*NotifyGroup         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotifyGroupsResponse) Reset() {
	*x = ListNotifyGroupsResponse{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotifyGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifyGroupsResponse) ProtoMessage() {}

func (x *ListNotifyGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifyGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListNotifyGroupsResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{3}
}

func (x *ListNotifyGroupsResponse) GetGroups() []*NotifyGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListNotifyGroupsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateNotifyGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *NotifyGroup           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotifyGroupRequest) Reset() {
	*x = CreateNotifyGroupRequest{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotifyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotifyGroupRequest) ProtoMessage() {}

func (x *CreateNotifyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotifyGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateNotifyGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{4}
}

func (x *CreateNotifyGroupRequest) GetGroup() *NotifyGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type CreateNotifyGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *NotifyGroup           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotifyGroupResponse) Reset() {
	*x = CreateNotifyGroupResponse{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotifyGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotifyGroupResponse) ProtoMessage() {}

func (x *CreateNotifyGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotifyGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateNotifyGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNotifyGroupResponse) GetGroup() *NotifyGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetNotifyGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyGroupId string                 `protobuf:"bytes,1,opt,name=notify_group_id,json=notifyGroupId,proto3" json:"notify_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifyGroupRequest) Reset() {
	*x = GetNotifyGroupRequest{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifyGroupRequest) ProtoMessage() {}

func (x *GetNotifyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifyGroupRequest.ProtoReflect.Descriptor instead.
func (*GetNotifyGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotifyGroupRequest) GetNotifyGroupId() string {
	if x != nil {
		return x.NotifyGroupId
	}
	return ""
}

type GetNotifyGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *NotifyGroup           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifyGroupResponse) Reset() {
	*x = GetNotifyGroupResponse{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifyGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifyGroupResponse) ProtoMessage() {}

func (x *GetNotifyGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifyGroupResponse.ProtoReflect.Descriptor instead.
func (*GetNotifyGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{7}
}

func (x *GetNotifyGroupResponse) GetGroup() *NotifyGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateNotifyGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyGroupId string                 `protobuf:"bytes,1,opt,name=notify_group_id,json=notifyGroupId,proto3" json:"notify_group_id,omitempty"`
	Group         *NotifyGroup           `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotifyGroupRequest) Reset() {
	*x = UpdateNotifyGroupRequest{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotifyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotifyGroupRequest) ProtoMessage() {}

func (x *UpdateNotifyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotifyGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotifyGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNotifyGroupRequest) GetNotifyGroupId() string {
	if x != nil {
		return x.NotifyGroupId
	}
	return ""
}

func (x *UpdateNotifyGroupRequest) GetGroup() *NotifyGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateNotifyGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *NotifyGroup           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotifyGroupResponse) Reset() {
	*x = UpdateNotifyGroupResponse{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotifyGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotifyGroupResponse) ProtoMessage() {}

func (x *UpdateNotifyGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotifyGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotifyGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNotifyGroupResponse) GetGroup() *NotifyGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteNotifyGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyGroupId string                 `protobuf:"bytes,1,opt,name=notify_group_id,json=notifyGroupId,proto3" json:"notify_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotifyGroupRequest) Reset() {
	*x = DeleteNotifyGroupRequest{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotifyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotifyGroupRequest) ProtoMessage() {}

func (x *DeleteNotifyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotifyGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotifyGroupRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNotifyGroupRequest) GetNotifyGroupId() string {
	if x != nil {
		return x.NotifyGroupId
	}
	return ""
}

type DeleteNotifyGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotifyGroupResponse) Reset() {
	*x = DeleteNotifyGroupResponse{}
	mi := &file_neoline_v1_notify_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotifyGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotifyGroupResponse) ProtoMessage() {}

func (x *DeleteNotifyGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_notify_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotifyGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotifyGroupResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_notify_group_proto_rawDescGZIP(), []int{11}
}

var File_neoline_v1_notify_group_proto protoreflect.FileDescriptor

const file_neoline_v1_notify_group_proto_rawDesc = "" +
	"\n" +
	"\x1dneoline/v1/notify_group.proto\x12\n" +
	"neoline.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\fAlertChannel\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x129\n" +
	"\x05extra\x18\x03 \x03(\v2#.neoline.v1.AlertChannel.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\vNotifyGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\bchannels\x18\x04 \x03(\v2\x18.neoline.v1.AlertChannelR\bchannels\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x17ListNotifyGroupsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"s\n" +
	"\x18ListNotifyGroupsResponse\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.neoline.v1.NotifyGroupR\x06groups\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"I\n" +
	"\x18CreateNotifyGroupRequest\x12-\n" +
	"\x05group\x18\x01 \x01(\v2\x17.neoline.v1.NotifyGroupR\x05group\"J\n" +
	"\x19CreateNotifyGroupResponse\x12-\n" +
	"\x05group\x18\x01 \x01(\v2\x17.neoline.v1.NotifyGroupR\x05group\"?\n" +
	"\x15GetNotifyGroupRequest\x12&\n" +
	"\x0fnotify_group_id\x18\x01 \x01(\tR\rnotifyGroupId\"G\n" +
	"\x16GetNotifyGroupResponse\x12-\n" +
	"\x05group\x18\x01 \x01(\v2\x17.neoline.v1.NotifyGroupR\x05group\"q\n" +
	"\x18UpdateNotifyGroupRequest\x12&\n" +
	"\x0fnotify_group_id\x18\x01 \x01(\tR\rnotifyGroupId\x12-\n" +
	"\x05group\x18\x02 \x01(\v2\x17.neoline.v1.NotifyGroupR\x05group\"J\n" +
	"\x19UpdateNotifyGroupResponse\x12-\n" +
	"\x05group\x18\x01 \x01(\v2\x17.neoline.v1.NotifyGroupR\x05group\"B\n" +
	"\x18DeleteNotifyGroupRequest\x12&\n" +
	"\x0fnotify_group_id\x18\x01 \x01(\tR\rnotifyGroupId\"\x1b\n" +
	"\x19DeleteNotifyGroupResponse2\xc1\x05\n" +
	"\x12NotifyGroupService\x12x\n" +
	"\x10ListNotifyGroups\x12#.neoline.v1.ListNotifyGroupsRequest\x1a$.neoline.v1.ListNotifyGroupsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/notify-groups\x12\x82\x01\n" +
	"\x11CreateNotifyGroup\x12$.neoline.v1.CreateNotifyGroupRequest\x1a%.neoline.v1.CreateNotifyGroupResponse\" \x82\xd3\xe4\x93\x02\x1a:\x05group\"\x11/v1/notify-groups\x12\x84\x01\n" +
	"\x0eGetNotifyGroup\x12!.neoline.v1.GetNotifyGroupRequest\x1a\".neoline.v1.GetNotifyGroupResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/notify-groups/{notify_group_id}\x12\x94\x01\n" +
	"\x11UpdateNotifyGroup\x12$.neoline.v1.UpdateNotifyGroupRequest\x1a%.neoline.v1.UpdateNotifyGroupResponse\"2\x82\xd3\xe4\x93\x02,:\x05group\x1a#/v1/notify-groups/{notify_group_id}\x12\x8d\x01\n" +
	"\x11DeleteNotifyGroup\x12$.neoline.v1.DeleteNotifyGroupRequest\x1a%.neoline.v1.DeleteNotifyGroupResponse\"+\x82\xd3\xe4\x93\x02%*#/v1/notify-groups/{notify_group_id}B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_notify_group_proto_rawDescOnce sync.Once
	file_neoline_v1_notify_group_proto_rawDescData []byte
)

func file_neoline_v1_notify_group_proto_rawDescGZIP() []byte {
	file_neoline_v1_notify_group_proto_rawDescOnce.Do(func() {
		file_neoline_v1_notify_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_notify_group_proto_rawDesc), len(file_neoline_v1_notify_group_proto_rawDesc)))
	})
	return file_neoline_v1_notify_group_proto_rawDescData
}

var file_neoline_v1_notify_group_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_neoline_v1_notify_group_proto_goTypes = []any{
	(*AlertChannel)(nil),              // 0: neoline.v1.AlertChannel
	(*NotifyGroup)(nil),               // 1: neoline.v1.NotifyGroup
	(*ListNotifyGroupsRequest)(nil),   // 2: neoline.v1.ListNotifyGroupsRequest
	(*ListNotifyGroupsResponse)(nil),  // 3: neoline.v1.ListNotifyGroupsResponse
	(*CreateNotifyGroupRequest)(nil),  // 4: neoline.v1.CreateNotifyGroupRequest
	(*CreateNotifyGroupResponse)(nil), // 5: neoline.v1.CreateNotifyGroupResponse
	(*GetNotifyGroupRequest)(nil),     // 6: neoline.v1.GetNotifyGroupRequest
	(*GetNotifyGroupResponse)(nil),    // 7: neoline.v1.GetNotifyGroupResponse
	(*UpdateNotifyGroupRequest)(nil),  // 8: neoline.v1.UpdateNotifyGroupRequest
	(*UpdateNotifyGroupResponse)(nil), // 9: neoline.v1.UpdateNotifyGroupResponse
	(*DeleteNotifyGroupRequest)(nil),  // 10: neoline.v1.DeleteNotifyGroupRequest
	(*DeleteNotifyGroupResponse)(nil), // 11: neoline.v1.DeleteNotifyGroupResponse
	nil,                               // 12: neoline.v1.AlertChannel.ExtraEntry
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_neoline_v1_notify_group_proto_depIdxs = []int32{
	12, // 0: neoline.v1.AlertChannel.extra:type_name -> neoline.v1.AlertChannel.ExtraEntry
	0,  // 1: neoline.v1.NotifyGroup.channels:type_name -> neoline.v1.AlertChannel
	13, // 2: neoline.v1.NotifyGroup.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: neoline.v1.NotifyGroup.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: neoline.v1.ListNotifyGroupsResponse.groups:type_name -> neoline.v1.NotifyGroup
	1,  // 5: neoline.v1.CreateNotifyGroupRequest.group:type_name -> neoline.v1.NotifyGroup
	1,  // 6: neoline.v1.CreateNotifyGroupResponse.group:type_name -> neoline.v1.NotifyGroup
	1,  // 7: neoline.v1.GetNotifyGroupResponse.group:type_name -> neoline.v1.NotifyGroup
	1,  // 8: neoline.v1.UpdateNotifyGroupRequest.group:type_name -> neoline.v1.NotifyGroup
	1,  // 9: neoline.v1.UpdateNotifyGroupResponse.group:type_name -> neoline.v1.NotifyGroup
	2,  // 10: neoline.v1.NotifyGroupService.ListNotifyGroups:input_type -> neoline.v1.ListNotifyGroupsRequest
	4,  // 11: neoline.v1.NotifyGroupService.CreateNotifyGroup:input_type -> neoline.v1.CreateNotifyGroupRequest
	6,  // 12: neoline.v1.NotifyGroupService.GetNotifyGroup:input_type -> neoline.v1.GetNotifyGroupRequest
	8,  // 13: neoline.v1.NotifyGroupService.UpdateNotifyGroup:input_type -> neoline.v1.UpdateNotifyGroupRequest
	10, // 14: neoline.v1.NotifyGroupService.DeleteNotifyGroup:input_type -> neoline.v1.DeleteNotifyGroupRequest
	3,  // 15: neoline.v1.NotifyGroupService.ListNotifyGroups:output_type -> neoline.v1.ListNotifyGroupsResponse
	5,  // 16: neoline.v1.NotifyGroupService.CreateNotifyGroup:output_type -> neoline.v1.CreateNotifyGroupResponse
	7,  // 17: neoline.v1.NotifyGroupService.GetNotifyGroup:output_type -> neoline.v1.GetNotifyGroupResponse
	9,  // 18: neoline.v1.NotifyGroupService.UpdateNotifyGroup:output_type -> neoline.v1.UpdateNotifyGroupResponse
	11, // 19: neoline.v1.NotifyGroupService.DeleteNotifyGroup:output_type -> neoline.v1.DeleteNotifyGroupResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_neoline_v1_notify_group_proto_init() }
func file_neoline_v1_notify_group_proto_init() {
	if File_neoline_v1_notify_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_notify_group_proto_rawDesc), len(file_neoline_v1_notify_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_notify_group_proto_goTypes,
		DependencyIndexes: file_neoline_v1_notify_group_proto_depIdxs,
		MessageInfos:      file_neoline_v1_notify_group_proto_msgTypes,
	}.Build()
	File_neoline_v1_notify_group_proto = out.File
	file_neoline_v1_notify_group_proto_goTypes = nil
	file_neoline_v1_notify_group_proto_depIdxs = nil
}
