// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neoline/v1/server.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerSSH stores per-server SSH execution settings. Empty host/port/user
// values inherit from the server host and global runtime SSH defaults.
type ServerSSH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSSH) Reset() {
	*x = ServerSSH{}
	mi := &file_neoline_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSSH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSSH) ProtoMessage() {}

func (x *ServerSSH) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSSH.ProtoReflect.Descriptor instead.
func (*ServerSSH) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerSSH) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServerSSH) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerSSH) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerSSH) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Server is a monitored host with one or more attached monitors.
type Server struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host               string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Environment        string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Region             string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Tags               []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	SortOrder          uint32                 `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Enabled            bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	HealthStatus       string                 `protobuf:"bytes,9,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	LastStatusChangeAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_status_change_at,json=lastStatusChangeAt,proto3" json:"last_status_change_at,omitempty"`
	LastCheckAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_check_at,json=lastCheckAt,proto3" json:"last_check_at,omitempty"`
	Ssh                *ServerSSH             `protobuf:"bytes,12,opt,name=ssh,proto3" json:"ssh,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_neoline_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Server) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Server) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Server) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Server) GetSortOrder() uint32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Server) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Server) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

func (x *Server) GetLastStatusChangeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStatusChangeAt
	}
	return nil
}

func (x *Server) GetLastCheckAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckAt
	}
	return nil
}

func (x *Server) GetSsh() *ServerSSH {
	if x != nil {
		return x.Ssh
	}
	return nil
}

func (x *Server) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Server) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ServerEvent records a server health-status transition.
type ServerEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId       string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	CurrentStatus  string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_neoline_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *ServerEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerEvent) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *ServerEvent) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *ServerEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ServerEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// ServerHealth is the aggregated health view of a server.
type ServerHealth struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerId           string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastStatusChangeAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_status_change_at,json=lastStatusChangeAt,proto3" json:"last_status_change_at,omitempty"`
	LastCheckAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_check_at,json=lastCheckAt,proto3" json:"last_check_at,omitempty"`
	TotalMonitors      uint32                 `protobuf:"varint,5,opt,name=total_monitors,json=totalMonitors,proto3" json:"total_monitors,omitempty"`
	HealthyMonitors    uint32                 `protobuf:"varint,6,opt,name=healthy_monitors,json=healthyMonitors,proto3" json:"healthy_monitors,omitempty"`
	WarningMonitors    uint32                 `protobuf:"varint,7,opt,name=warning_monitors,json=warningMonitors,proto3" json:"warning_monitors,omitempty"`
	CriticalMonitors   uint32                 `protobuf:"varint,8,opt,name=critical_monitors,json=criticalMonitors,proto3" json:"critical_monitors,omitempty"`
	DownMonitors       uint32                 `protobuf:"varint,9,opt,name=down_monitors,json=downMonitors,proto3" json:"down_monitors,omitempty"`
	UnknownMonitors    uint32                 `protobuf:"varint,10,opt,name=unknown_monitors,json=unknownMonitors,proto3" json:"unknown_monitors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerHealth) Reset() {
	*x = ServerHealth{}
	mi := &file_neoline_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHealth) ProtoMessage() {}

func (x *ServerHealth) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHealth.ProtoReflect.Descriptor instead.
func (*ServerHealth) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHealth) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerHealth) GetLastStatusChangeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStatusChangeAt
	}
	return nil
}

func (x *ServerHealth) GetLastCheckAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckAt
	}
	return nil
}

func (x *ServerHealth) GetTotalMonitors() uint32 {
	if x != nil {
		return x.TotalMonitors
	}
	return 0
}

func (x *ServerHealth) GetHealthyMonitors() uint32 {
	if x != nil {
		return x.HealthyMonitors
	}
	return 0
}

func (x *ServerHealth) GetWarningMonitors() uint32 {
	if x != nil {
		return x.WarningMonitors
	}
	return 0
}

func (x *ServerHealth) GetCriticalMonitors() uint32 {
	if x != nil {
		return x.CriticalMonitors
	}
	return 0
}

func (x *ServerHealth) GetDownMonitors() uint32 {
	if x != nil {
		return x.DownMonitors
	}
	return 0
}

func (x *ServerHealth) GetUnknownMonitors() uint32 {
	if x != nil {
		return x.UnknownMonitors
	}
	return 0
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *ListServersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListServersRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListServersRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ListServersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *CreateServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *CreateServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *GetServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *GetServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UpdateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerResponse) Reset() {
	*x = UpdateServerResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerResponse) ProtoMessage() {}

func (x *UpdateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerResponse.ProtoReflect.Descriptor instead.
func (*UpdateServerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{13}
}

type GetServerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerHealthRequest) Reset() {
	*x = GetServerHealthRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerHealthRequest) ProtoMessage() {}

func (x *GetServerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerHealthRequest.ProtoReflect.Descriptor instead.
func (*GetServerHealthRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *GetServerHealthRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ServerHealth          `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerHealthResponse) Reset() {
	*x = GetServerHealthResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerHealthResponse) ProtoMessage() {}

func (x *GetServerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerHealthResponse.ProtoReflect.Descriptor instead.
func (*GetServerHealthResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *GetServerHealthResponse) GetHealth() *ServerHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type ListServerEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServerEventsRequest) Reset() {
	*x = ListServerEventsRequest{}
	mi := &file_neoline_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServerEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServerEventsRequest) ProtoMessage() {}

func (x *ListServerEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServerEventsRequest.ProtoReflect.Descriptor instead.
func (*ListServerEventsRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *ListServerEventsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListServerEventsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServerEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListServerEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ServerEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServerEventsResponse) Reset() {
	*x = ListServerEventsResponse{}
	mi := &file_neoline_v1_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServerEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServerEventsResponse) ProtoMessage() {}

func (x *ListServerEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServerEventsResponse.ProtoReflect.Descriptor instead.
func (*ListServerEventsResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_proto_rawDescGZIP(), []int{17}
}

func (x *ListServerEventsResponse) GetEvents() []*ServerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListServerEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_neoline_v1_server_proto protoreflect.FileDescriptor

const file_neoline_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x17neoline/v1/server.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\tServerSSH\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"\x9a\x04\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\rR\tsortOrder\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12#\n" +
	"\rhealth_status\x18\t \x01(\tR\fhealthStatus\x12M\n" +
	"\x15last_status_change_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12lastStatusChangeAt\x12>\n" +
	"\rlast_check_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastCheckAt\x12'\n" +
	"\x03ssh\x18\f \x01(\v2\x15.neoline.v1.ServerSSHR\x03ssh\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdf\x01\n" +
	"\vServerEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xcc\x03\n" +
	"\fServerHealth\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12M\n" +
	"\x15last_status_change_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastStatusChangeAt\x12>\n" +
	"\rlast_check_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastCheckAt\x12%\n" +
	"\x0etotal_monitors\x18\x05 \x01(\rR\rtotalMonitors\x12)\n" +
	"\x10healthy_monitors\x18\x06 \x01(\rR\x0fhealthyMonitors\x12)\n" +
	"\x10warning_monitors\x18\a \x01(\rR\x0fwarningMonitors\x12+\n" +
	"\x11critical_monitors\x18\b \x01(\rR\x10criticalMonitors\x12#\n" +
	"\rdown_monitors\x18\t \x01(\rR\fdownMonitors\x12)\n" +
	"\x10unknown_monitors\x18\n" +
	" \x01(\rR\x0funknownMonitors\"\x86\x01\n" +
	"\x12ListServersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"k\n" +
	"\x13ListServersResponse\x12,\n" +
	"\aservers\x18\x01 \x03(\v2\x12.neoline.v1.ServerR\aservers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"A\n" +
	"\x13CreateServerRequest\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.neoline.v1.ServerR\x06server\"B\n" +
	"\x14CreateServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.neoline.v1.ServerR\x06server\"\"\n" +
	"\x10GetServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x11GetServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.neoline.v1.ServerR\x06server\"Q\n" +
	"\x13UpdateServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x06server\x18\x02 \x01(\v2\x12.neoline.v1.ServerR\x06server\"B\n" +
	"\x14UpdateServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.neoline.v1.ServerR\x06server\"%\n" +
	"\x13DeleteServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteServerResponse\"(\n" +
	"\x16GetServerHealthRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x17GetServerHealthResponse\x120\n" +
	"\x06health\x18\x01 \x01(\v2\x18.neoline.v1.ServerHealthR\x06health\"e\n" +
	"\x17ListServerEventsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"s\n" +
	"\x18ListServerEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.neoline.v1.ServerEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xeb\x04\n" +
	"\rServerService\x12P\n" +
	"\vListServers\x12\x1e.neoline.v1.ListServersRequest\x1a\x1f.neoline.v1.ListServersResponse\"\x00\x12S\n" +
	"\fCreateServer\x12\x1f.neoline.v1.CreateServerRequest\x1a .neoline.v1.CreateServerResponse\"\x00\x12J\n" +
	"\tGetServer\x12\x1c.neoline.v1.GetServerRequest\x1a\x1d.neoline.v1.GetServerResponse\"\x00\x12S\n" +
	"\fUpdateServer\x12\x1f.neoline.v1.UpdateServerRequest\x1a .neoline.v1.UpdateServerResponse\"\x00\x12S\n" +
	"\fDeleteServer\x12\x1f.neoline.v1.DeleteServerRequest\x1a .neoline.v1.DeleteServerResponse\"\x00\x12\\\n" +
	"\x0fGetServerHealth\x12\".neoline.v1.GetServerHealthRequest\x1a#.neoline.v1.GetServerHealthResponse\"\x00\x12_\n" +
	"\x10ListServerEvents\x12#.neoline.v1.ListServerEventsRequest\x1a$.neoline.v1.ListServerEventsResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_server_proto_rawDescOnce sync.Once
	file_neoline_v1_server_proto_rawDescData []byte
)

func file_neoline_v1_server_proto_rawDescGZIP() []byte {
	file_neoline_v1_server_proto_rawDescOnce.Do(func() {
		file_neoline_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_server_proto_rawDesc), len(file_neoline_v1_server_proto_rawDesc)))
	})
	return file_neoline_v1_server_proto_rawDescData
}

var file_neoline_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_neoline_v1_server_proto_goTypes = []any{
	(*ServerSSH)(nil),                // 0: neoline.v1.ServerSSH
	(*Server)(nil),                   // 1: neoline.v1.Server
	(*ServerEvent)(nil),              // 2: neoline.v1.ServerEvent
	(*ServerHealth)(nil),             // 3: neoline.v1.ServerHealth
	(*ListServersRequest)(nil),       // 4: neoline.v1.ListServersRequest
	(*ListServersResponse)(nil),      // 5: neoline.v1.ListServersResponse
	(*CreateServerRequest)(nil),      // 6: neoline.v1.CreateServerRequest
	(*CreateServerResponse)(nil),     // 7: neoline.v1.CreateServerResponse
	(*GetServerRequest)(nil),         // 8: neoline.v1.GetServerRequest
	(*GetServerResponse)(nil),        // 9: neoline.v1.GetServerResponse
	(*UpdateServerRequest)(nil),      // 10: neoline.v1.UpdateServerRequest
	(*UpdateServerResponse)(nil),     // 11: neoline.v1.UpdateServerResponse
	(*DeleteServerRequest)(nil),      // 12: neoline.v1.DeleteServerRequest
	(*DeleteServerResponse)(nil),     // 13: neoline.v1.DeleteServerResponse
	(*GetServerHealthRequest)(nil),   // 14: neoline.v1.GetServerHealthRequest
	(*GetServerHealthResponse)(nil),  // 15: neoline.v1.GetServerHealthResponse
	(*ListServerEventsRequest)(nil),  // 16: neoline.v1.ListServerEventsRequest
	(*ListServerEventsResponse)(nil), // 17: neoline.v1.ListServerEventsResponse
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
}
var file_neoline_v1_server_proto_depIdxs = []int32{
	18, // 0: neoline.v1.Server.last_status_change_at:type_name -> google.protobuf.Timestamp
	18, // 1: neoline.v1.Server.last_check_at:type_name -> google.protobuf.Timestamp
	0,  // 2: neoline.v1.Server.ssh:type_name -> neoline.v1.ServerSSH
	18, // 3: neoline.v1.Server.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: neoline.v1.Server.updated_at:type_name -> google.protobuf.Timestamp
	18, // 5: neoline.v1.ServerEvent.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 6: neoline.v1.ServerHealth.last_status_change_at:type_name -> google.protobuf.Timestamp
	18, // 7: neoline.v1.ServerHealth.last_check_at:type_name -> google.protobuf.Timestamp
	1,  // 8: neoline.v1.ListServersResponse.servers:type_name -> neoline.v1.Server
	1,  // 9: neoline.v1.CreateServerRequest.server:type_name -> neoline.v1.Server
	1,  // 10: neoline.v1.CreateServerResponse.server:type_name -> neoline.v1.Server
	1,  // 11: neoline.v1.GetServerResponse.server:type_name -> neoline.v1.Server
	1,  // 12: neoline.v1.UpdateServerRequest.server:type_name -> neoline.v1.Server
	1,  // 13: neoline.v1.UpdateServerResponse.server:type_name -> neoline.v1.Server
	3,  // 14: neoline.v1.GetServerHealthResponse.health:type_name -> neoline.v1.ServerHealth
	2,  // 15: neoline.v1.ListServerEventsResponse.events:type_name -> neoline.v1.ServerEvent
	4,  // 16: neoline.v1.ServerService.ListServers:input_type -> neoline.v1.ListServersRequest
	6,  // 17: neoline.v1.ServerService.CreateServer:input_type -> neoline.v1.CreateServerRequest
	8,  // 18: neoline.v1.ServerService.GetServer:input_type -> neoline.v1.GetServerRequest
	10, // 19: neoline.v1.ServerService.UpdateServer:input_type -> neoline.v1.UpdateServerRequest
	12, // 20: neoline.v1.ServerService.DeleteServer:input_type -> neoline.v1.DeleteServerRequest
	14, // 21: neoline.v1.ServerService.GetServerHealth:input_type -> neoline.v1.GetServerHealthRequest
	16, // 22: neoline.v1.ServerService.ListServerEvents:input_type -> neoline.v1.ListServerEventsRequest
	5,  // 23: neoline.v1.ServerService.ListServers:output_type -> neoline.v1.ListServersResponse
	7,  // 24: neoline.v1.ServerService.CreateServer:output_type -> neoline.v1.CreateServerResponse
	9,  // 25: neoline.v1.ServerService.GetServer:output_type -> neoline.v1.GetServerResponse
	11, // 26: neoline.v1.ServerService.UpdateServer:output_type -> neoline.v1.UpdateServerResponse
	13, // 27: neoline.v1.ServerService.DeleteServer:output_type -> neoline.v1.DeleteServerResponse
	15, // 28: neoline.v1.ServerService.GetServerHealth:output_type -> neoline.v1.GetServerHealthResponse
	17, // 29: neoline.v1.ServerService.ListServerEvents:output_type -> neoline.v1.ListServerEventsResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_neoline_v1_server_proto_init() }
func file_neoline_v1_server_proto_init() {
	if File_neoline_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_server_proto_rawDesc), len(file_neoline_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_server_proto_goTypes,
		DependencyIndexes: file_neoline_v1_server_proto_depIdxs,
		MessageInfos:      file_neoline_v1_server_proto_msgTypes,
	}.Build()
	File_neoline_v1_server_proto = out.File
	file_neoline_v1_server_proto_goTypes = nil
	file_neoline_v1_server_proto_depIdxs = nil
}
