// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: neoline/v1/server_certificate.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerCertificate describes one ManagedCertificate authorized for the calling Server.
type ServerCertificate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	// Config name when no active version exists; omitted when active metadata is shown.
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domains          []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	ActiveVersionId  string                 `protobuf:"bytes,4,opt,name=active_version_id,json=activeVersionId,proto3" json:"active_version_id,omitempty"`
	Available        bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Validity         CertificateValidity    `protobuf:"varint,6,opt,name=validity,proto3,enum=neoline.v1.CertificateValidity" json:"validity,omitempty"`
	KeyType          CertificateKeyType     `protobuf:"varint,7,opt,name=key_type,json=keyType,proto3,enum=neoline.v1.CertificateKeyType" json:"key_type,omitempty"`
	LeafFingerprint  string                 `protobuf:"bytes,8,opt,name=leaf_fingerprint,json=leafFingerprint,proto3" json:"leaf_fingerprint,omitempty"`
	NotBefore        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	StagingUntrusted bool                   `protobuf:"varint,11,opt,name=staging_untrusted,json=stagingUntrusted,proto3" json:"staging_untrusted,omitempty"`
	// Safe error summary when available=false (e.g. issuance failed).
	ErrorSummary  string `protobuf:"bytes,12,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCertificate) Reset() {
	*x = ServerCertificate{}
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificate) ProtoMessage() {}

func (x *ServerCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificate.ProtoReflect.Descriptor instead.
func (*ServerCertificate) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *ServerCertificate) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

func (x *ServerCertificate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerCertificate) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *ServerCertificate) GetActiveVersionId() string {
	if x != nil {
		return x.ActiveVersionId
	}
	return ""
}

func (x *ServerCertificate) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ServerCertificate) GetValidity() CertificateValidity {
	if x != nil {
		return x.Validity
	}
	return CertificateValidity_CERTIFICATE_VALIDITY_UNSPECIFIED
}

func (x *ServerCertificate) GetKeyType() CertificateKeyType {
	if x != nil {
		return x.KeyType
	}
	return CertificateKeyType_CERTIFICATE_KEY_TYPE_UNSPECIFIED
}

func (x *ServerCertificate) GetLeafFingerprint() string {
	if x != nil {
		return x.LeafFingerprint
	}
	return ""
}

func (x *ServerCertificate) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *ServerCertificate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *ServerCertificate) GetStagingUntrusted() bool {
	if x != nil {
		return x.StagingUntrusted
	}
	return false
}

func (x *ServerCertificate) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

type ListCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesRequest) Reset() {
	*x = ListCertificatesRequest{}
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesRequest) ProtoMessage() {}

func (x *ListCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_certificate_proto_rawDescGZIP(), []int{1}
}

type ListCertificatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*ServerCertificate   `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesResponse) Reset() {
	*x = ListCertificatesResponse{}
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesResponse) ProtoMessage() {}

func (x *ListCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesResponse.ProtoReflect.Descriptor instead.
func (*ListCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_certificate_proto_rawDescGZIP(), []int{2}
}

func (x *ListCertificatesResponse) GetCertificates() []*ServerCertificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type ServerCertificateServiceGetCertificateBundleRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ManagedCertificateId string                 `protobuf:"bytes,1,opt,name=managed_certificate_id,json=managedCertificateId,proto3" json:"managed_certificate_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServerCertificateServiceGetCertificateBundleRequest) Reset() {
	*x = ServerCertificateServiceGetCertificateBundleRequest{}
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCertificateServiceGetCertificateBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificateServiceGetCertificateBundleRequest) ProtoMessage() {}

func (x *ServerCertificateServiceGetCertificateBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificateServiceGetCertificateBundleRequest.ProtoReflect.Descriptor instead.
func (*ServerCertificateServiceGetCertificateBundleRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_certificate_proto_rawDescGZIP(), []int{3}
}

func (x *ServerCertificateServiceGetCertificateBundleRequest) GetManagedCertificateId() string {
	if x != nil {
		return x.ManagedCertificateId
	}
	return ""
}

type ServerCertificateServiceGetCertificateBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *CertificateBundle     `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCertificateServiceGetCertificateBundleResponse) Reset() {
	*x = ServerCertificateServiceGetCertificateBundleResponse{}
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCertificateServiceGetCertificateBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificateServiceGetCertificateBundleResponse) ProtoMessage() {}

func (x *ServerCertificateServiceGetCertificateBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_server_certificate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificateServiceGetCertificateBundleResponse.ProtoReflect.Descriptor instead.
func (*ServerCertificateServiceGetCertificateBundleResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_server_certificate_proto_rawDescGZIP(), []int{4}
}

func (x *ServerCertificateServiceGetCertificateBundleResponse) GetBundle() *CertificateBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

var File_neoline_v1_server_certificate_proto protoreflect.FileDescriptor

const file_neoline_v1_server_certificate_proto_rawDesc = "" +
	"\n" +
	"#neoline/v1/server_certificate.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$neoline/v1/managed_certificate.proto\"\xaa\x04\n" +
	"\x11ServerCertificate\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12*\n" +
	"\x11active_version_id\x18\x04 \x01(\tR\x0factiveVersionId\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12;\n" +
	"\bvalidity\x18\x06 \x01(\x0e2\x1f.neoline.v1.CertificateValidityR\bvalidity\x129\n" +
	"\bkey_type\x18\a \x01(\x0e2\x1e.neoline.v1.CertificateKeyTypeR\akeyType\x12)\n" +
	"\x10leaf_fingerprint\x18\b \x01(\tR\x0fleafFingerprint\x129\n" +
	"\n" +
	"not_before\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12+\n" +
	"\x11staging_untrusted\x18\v \x01(\bR\x10stagingUntrusted\x12#\n" +
	"\rerror_summary\x18\f \x01(\tR\ferrorSummary\"\x19\n" +
	"\x17ListCertificatesRequest\"]\n" +
	"\x18ListCertificatesResponse\x12A\n" +
	"\fcertificates\x18\x01 \x03(\v2\x1d.neoline.v1.ServerCertificateR\fcertificates\"k\n" +
	"3ServerCertificateServiceGetCertificateBundleRequest\x124\n" +
	"\x16managed_certificate_id\x18\x01 \x01(\tR\x14managedCertificateId\"m\n" +
	"4ServerCertificateServiceGetCertificateBundleResponse\x125\n" +
	"\x06bundle\x18\x01 \x01(\v2\x1d.neoline.v1.CertificateBundleR\x06bundle2\x99\x02\n" +
	"\x18ServerCertificateService\x12_\n" +
	"\x10ListCertificates\x12#.neoline.v1.ListCertificatesRequest\x1a$.neoline.v1.ListCertificatesResponse\"\x00\x12\x9b\x01\n" +
	"\x14GetCertificateBundle\x12?.neoline.v1.ServerCertificateServiceGetCertificateBundleRequest\x1a@.neoline.v1.ServerCertificateServiceGetCertificateBundleResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_server_certificate_proto_rawDescOnce sync.Once
	file_neoline_v1_server_certificate_proto_rawDescData []byte
)

func file_neoline_v1_server_certificate_proto_rawDescGZIP() []byte {
	file_neoline_v1_server_certificate_proto_rawDescOnce.Do(func() {
		file_neoline_v1_server_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_server_certificate_proto_rawDesc), len(file_neoline_v1_server_certificate_proto_rawDesc)))
	})
	return file_neoline_v1_server_certificate_proto_rawDescData
}

var file_neoline_v1_server_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_neoline_v1_server_certificate_proto_goTypes = []any{
	(*ServerCertificate)(nil),                                    // 0: neoline.v1.ServerCertificate
	(*ListCertificatesRequest)(nil),                              // 1: neoline.v1.ListCertificatesRequest
	(*ListCertificatesResponse)(nil),                             // 2: neoline.v1.ListCertificatesResponse
	(*ServerCertificateServiceGetCertificateBundleRequest)(nil),  // 3: neoline.v1.ServerCertificateServiceGetCertificateBundleRequest
	(*ServerCertificateServiceGetCertificateBundleResponse)(nil), // 4: neoline.v1.ServerCertificateServiceGetCertificateBundleResponse
	(CertificateValidity)(0),                                     // 5: neoline.v1.CertificateValidity
	(CertificateKeyType)(0),                                      // 6: neoline.v1.CertificateKeyType
	(*timestamppb.Timestamp)(nil),                                // 7: google.protobuf.Timestamp
	(*CertificateBundle)(nil),                                    // 8: neoline.v1.CertificateBundle
}
var file_neoline_v1_server_certificate_proto_depIdxs = []int32{
	5, // 0: neoline.v1.ServerCertificate.validity:type_name -> neoline.v1.CertificateValidity
	6, // 1: neoline.v1.ServerCertificate.key_type:type_name -> neoline.v1.CertificateKeyType
	7, // 2: neoline.v1.ServerCertificate.not_before:type_name -> google.protobuf.Timestamp
	7, // 3: neoline.v1.ServerCertificate.not_after:type_name -> google.protobuf.Timestamp
	0, // 4: neoline.v1.ListCertificatesResponse.certificates:type_name -> neoline.v1.ServerCertificate
	8, // 5: neoline.v1.ServerCertificateServiceGetCertificateBundleResponse.bundle:type_name -> neoline.v1.CertificateBundle
	1, // 6: neoline.v1.ServerCertificateService.ListCertificates:input_type -> neoline.v1.ListCertificatesRequest
	3, // 7: neoline.v1.ServerCertificateService.GetCertificateBundle:input_type -> neoline.v1.ServerCertificateServiceGetCertificateBundleRequest
	2, // 8: neoline.v1.ServerCertificateService.ListCertificates:output_type -> neoline.v1.ListCertificatesResponse
	4, // 9: neoline.v1.ServerCertificateService.GetCertificateBundle:output_type -> neoline.v1.ServerCertificateServiceGetCertificateBundleResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_neoline_v1_server_certificate_proto_init() }
func file_neoline_v1_server_certificate_proto_init() {
	if File_neoline_v1_server_certificate_proto != nil {
		return
	}
	file_neoline_v1_managed_certificate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_server_certificate_proto_rawDesc), len(file_neoline_v1_server_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_server_certificate_proto_goTypes,
		DependencyIndexes: file_neoline_v1_server_certificate_proto_depIdxs,
		MessageInfos:      file_neoline_v1_server_certificate_proto_msgTypes,
	}.Build()
	File_neoline_v1_server_certificate_proto = out.File
	file_neoline_v1_server_certificate_proto_goTypes = nil
	file_neoline_v1_server_certificate_proto_depIdxs = nil
}
