// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neoline/v1/settings.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Settings holds site-wide presentation configuration for the status page.
type Settings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SiteName        string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	StatusPageTitle string                 `protobuf:"bytes,2,opt,name=status_page_title,json=statusPageTitle,proto3" json:"status_page_title,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_neoline_v1_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_neoline_v1_settings_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *Settings) GetStatusPageTitle() string {
	if x != nil {
		return x.StatusPageTitle
	}
	return ""
}

func (x *Settings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_neoline_v1_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_settings_proto_rawDescGZIP(), []int{1}
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_neoline_v1_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetSettingsResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_neoline_v1_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSettingsRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_neoline_v1_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_settings_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSettingsResponse) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_neoline_v1_settings_proto protoreflect.FileDescriptor

const file_neoline_v1_settings_proto_rawDesc = "" +
	"\n" +
	"\x19neoline/v1/settings.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\bSettings\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12*\n" +
	"\x11status_page_title\x18\x02 \x01(\tR\x0fstatusPageTitle\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x14\n" +
	"\x12GetSettingsRequest\"G\n" +
	"\x13GetSettingsResponse\x120\n" +
	"\bsettings\x18\x01 \x01(\v2\x14.neoline.v1.SettingsR\bsettings\"I\n" +
	"\x15UpdateSettingsRequest\x120\n" +
	"\bsettings\x18\x01 \x01(\v2\x14.neoline.v1.SettingsR\bsettings\"J\n" +
	"\x16UpdateSettingsResponse\x120\n" +
	"\bsettings\x18\x01 \x01(\v2\x14.neoline.v1.SettingsR\bsettings2\xbe\x01\n" +
	"\x0fSettingsService\x12P\n" +
	"\vGetSettings\x12\x1e.neoline.v1.GetSettingsRequest\x1a\x1f.neoline.v1.GetSettingsResponse\"\x00\x12Y\n" +
	"\x0eUpdateSettings\x12!.neoline.v1.UpdateSettingsRequest\x1a\".neoline.v1.UpdateSettingsResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_settings_proto_rawDescOnce sync.Once
	file_neoline_v1_settings_proto_rawDescData []byte
)

func file_neoline_v1_settings_proto_rawDescGZIP() []byte {
	file_neoline_v1_settings_proto_rawDescOnce.Do(func() {
		file_neoline_v1_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_settings_proto_rawDesc), len(file_neoline_v1_settings_proto_rawDesc)))
	})
	return file_neoline_v1_settings_proto_rawDescData
}

var file_neoline_v1_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_neoline_v1_settings_proto_goTypes = []any{
	(*Settings)(nil),               // 0: neoline.v1.Settings
	(*GetSettingsRequest)(nil),     // 1: neoline.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),    // 2: neoline.v1.GetSettingsResponse
	(*UpdateSettingsRequest)(nil),  // 3: neoline.v1.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil), // 4: neoline.v1.UpdateSettingsResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_neoline_v1_settings_proto_depIdxs = []int32{
	5, // 0: neoline.v1.Settings.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: neoline.v1.GetSettingsResponse.settings:type_name -> neoline.v1.Settings
	0, // 2: neoline.v1.UpdateSettingsRequest.settings:type_name -> neoline.v1.Settings
	0, // 3: neoline.v1.UpdateSettingsResponse.settings:type_name -> neoline.v1.Settings
	1, // 4: neoline.v1.SettingsService.GetSettings:input_type -> neoline.v1.GetSettingsRequest
	3, // 5: neoline.v1.SettingsService.UpdateSettings:input_type -> neoline.v1.UpdateSettingsRequest
	2, // 6: neoline.v1.SettingsService.GetSettings:output_type -> neoline.v1.GetSettingsResponse
	4, // 7: neoline.v1.SettingsService.UpdateSettings:output_type -> neoline.v1.UpdateSettingsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_neoline_v1_settings_proto_init() }
func file_neoline_v1_settings_proto_init() {
	if File_neoline_v1_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_settings_proto_rawDesc), len(file_neoline_v1_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_settings_proto_goTypes,
		DependencyIndexes: file_neoline_v1_settings_proto_depIdxs,
		MessageInfos:      file_neoline_v1_settings_proto_msgTypes,
	}.Build()
	File_neoline_v1_settings_proto = out.File
	file_neoline_v1_settings_proto_goTypes = nil
	file_neoline_v1_settings_proto_depIdxs = nil
}
