// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neoline/v1/status.proto

package neolinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicCertificate carries only certificate validity timing, never the
// subject, issuer, DNS names, or serial that would reveal hostnames.
type PublicCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	DaysRemaining int32                  `protobuf:"varint,3,opt,name=days_remaining,json=daysRemaining,proto3" json:"days_remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicCertificate) Reset() {
	*x = PublicCertificate{}
	mi := &file_neoline_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicCertificate) ProtoMessage() {}

func (x *PublicCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicCertificate.ProtoReflect.Descriptor instead.
func (*PublicCertificate) Descriptor() ([]byte, []int) {
	return file_neoline_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *PublicCertificate) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *PublicCertificate) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *PublicCertificate) GetDaysRemaining() int32 {
	if x != nil {
		return x.DaysRemaining
	}
	return 0
}

// StatusMonitor is the slim, anonymous view of one monitor on the status page.
type StatusMonitor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId        string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind            string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IntervalSeconds uint32                 `protobuf:"varint,6,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	LastCheckAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_check_at,json=lastCheckAt,proto3" json:"last_check_at,omitempty"`
	WarningDays     uint32                 `protobuf:"varint,8,opt,name=warning_days,json=warningDays,proto3" json:"warning_days,omitempty"`
	CriticalDays    uint32                 `protobuf:"varint,9,opt,name=critical_days,json=criticalDays,proto3" json:"critical_days,omitempty"`
	Certificate     *PublicCertificate     `protobuf:"bytes,10,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Uptime          *MonitorUptime         `protobuf:"bytes,11,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusMonitor) Reset() {
	*x = StatusMonitor{}
	mi := &file_neoline_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMonitor) ProtoMessage() {}

func (x *StatusMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMonitor.ProtoReflect.Descriptor instead.
func (*StatusMonitor) Descriptor() ([]byte, []int) {
	return file_neoline_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusMonitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusMonitor) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *StatusMonitor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusMonitor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StatusMonitor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusMonitor) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *StatusMonitor) GetLastCheckAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckAt
	}
	return nil
}

func (x *StatusMonitor) GetWarningDays() uint32 {
	if x != nil {
		return x.WarningDays
	}
	return 0
}

func (x *StatusMonitor) GetCriticalDays() uint32 {
	if x != nil {
		return x.CriticalDays
	}
	return 0
}

func (x *StatusMonitor) GetCertificate() *PublicCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *StatusMonitor) GetUptime() *MonitorUptime {
	if x != nil {
		return x.Uptime
	}
	return nil
}

type StatusServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Monitors      []*StatusMonitor       `protobuf:"bytes,5,rep,name=monitors,proto3" json:"monitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusServer) Reset() {
	*x = StatusServer{}
	mi := &file_neoline_v1_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusServer) ProtoMessage() {}

func (x *StatusServer) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusServer.ProtoReflect.Descriptor instead.
func (*StatusServer) Descriptor() ([]byte, []int) {
	return file_neoline_v1_status_proto_rawDescGZIP(), []int{2}
}

func (x *StatusServer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusServer) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StatusServer) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StatusServer) GetMonitors() []*StatusMonitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

type StatusGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     uint32                 `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Servers       []*StatusServer        `protobuf:"bytes,5,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusGroup) Reset() {
	*x = StatusGroup{}
	mi := &file_neoline_v1_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGroup) ProtoMessage() {}

func (x *StatusGroup) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGroup.ProtoReflect.Descriptor instead.
func (*StatusGroup) Descriptor() ([]byte, []int) {
	return file_neoline_v1_status_proto_rawDescGZIP(), []int{3}
}

func (x *StatusGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StatusGroup) GetSortOrder() uint32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *StatusGroup) GetServers() []*StatusServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

type GetStatusOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusOverviewRequest) Reset() {
	*x = GetStatusOverviewRequest{}
	mi := &file_neoline_v1_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusOverviewRequest) ProtoMessage() {}

func (x *GetStatusOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetStatusOverviewRequest) Descriptor() ([]byte, []int) {
	return file_neoline_v1_status_proto_rawDescGZIP(), []int{4}
}

type GetStatusOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*StatusGroup         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusOverviewResponse) Reset() {
	*x = GetStatusOverviewResponse{}
	mi := &file_neoline_v1_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusOverviewResponse) ProtoMessage() {}

func (x *GetStatusOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neoline_v1_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetStatusOverviewResponse) Descriptor() ([]byte, []int) {
	return file_neoline_v1_status_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusOverviewResponse) GetGroups() []*StatusGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_neoline_v1_status_proto protoreflect.FileDescriptor

const file_neoline_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x17neoline/v1/status.proto\x12\n" +
	"neoline.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18neoline/v1/monitor.proto\"\xae\x01\n" +
	"\x11PublicCertificate\x129\n" +
	"\n" +
	"not_before\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12%\n" +
	"\x0edays_remaining\x18\x03 \x01(\x05R\rdaysRemaining\"\xa3\x03\n" +
	"\rStatusMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12)\n" +
	"\x10interval_seconds\x18\x06 \x01(\rR\x0fintervalSeconds\x12>\n" +
	"\rlast_check_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastCheckAt\x12!\n" +
	"\fwarning_days\x18\b \x01(\rR\vwarningDays\x12#\n" +
	"\rcritical_days\x18\t \x01(\rR\fcriticalDays\x12?\n" +
	"\vcertificate\x18\n" +
	" \x01(\v2\x1d.neoline.v1.PublicCertificateR\vcertificate\x121\n" +
	"\x06uptime\x18\v \x01(\v2\x19.neoline.v1.MonitorUptimeR\x06uptime\"\x9f\x01\n" +
	"\fStatusServer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x125\n" +
	"\bmonitors\x18\x05 \x03(\v2\x19.neoline.v1.StatusMonitorR\bmonitors\"\xa6\x01\n" +
	"\vStatusGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\rR\tsortOrder\x122\n" +
	"\aservers\x18\x05 \x03(\v2\x18.neoline.v1.StatusServerR\aservers\"\x1a\n" +
	"\x18GetStatusOverviewRequest\"L\n" +
	"\x19GetStatusOverviewResponse\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.neoline.v1.StatusGroupR\x06groups2s\n" +
	"\rStatusService\x12b\n" +
	"\x11GetStatusOverview\x12$.neoline.v1.GetStatusOverviewRequest\x1a%.neoline.v1.GetStatusOverviewResponse\"\x00B;Z9github.com/orvice/neo-line/pkg/proto/neoline/v1;neolinev1b\x06proto3"

var (
	file_neoline_v1_status_proto_rawDescOnce sync.Once
	file_neoline_v1_status_proto_rawDescData []byte
)

func file_neoline_v1_status_proto_rawDescGZIP() []byte {
	file_neoline_v1_status_proto_rawDescOnce.Do(func() {
		file_neoline_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neoline_v1_status_proto_rawDesc), len(file_neoline_v1_status_proto_rawDesc)))
	})
	return file_neoline_v1_status_proto_rawDescData
}

var file_neoline_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_neoline_v1_status_proto_goTypes = []any{
	(*PublicCertificate)(nil),         // 0: neoline.v1.PublicCertificate
	(*StatusMonitor)(nil),             // 1: neoline.v1.StatusMonitor
	(*StatusServer)(nil),              // 2: neoline.v1.StatusServer
	(*StatusGroup)(nil),               // 3: neoline.v1.StatusGroup
	(*GetStatusOverviewRequest)(nil),  // 4: neoline.v1.GetStatusOverviewRequest
	(*GetStatusOverviewResponse)(nil), // 5: neoline.v1.GetStatusOverviewResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
	(*MonitorUptime)(nil),             // 7: neoline.v1.MonitorUptime
}
var file_neoline_v1_status_proto_depIdxs = []int32{
	6, // 0: neoline.v1.PublicCertificate.not_before:type_name -> google.protobuf.Timestamp
	6, // 1: neoline.v1.PublicCertificate.not_after:type_name -> google.protobuf.Timestamp
	6, // 2: neoline.v1.StatusMonitor.last_check_at:type_name -> google.protobuf.Timestamp
	0, // 3: neoline.v1.StatusMonitor.certificate:type_name -> neoline.v1.PublicCertificate
	7, // 4: neoline.v1.StatusMonitor.uptime:type_name -> neoline.v1.MonitorUptime
	1, // 5: neoline.v1.StatusServer.monitors:type_name -> neoline.v1.StatusMonitor
	2, // 6: neoline.v1.StatusGroup.servers:type_name -> neoline.v1.StatusServer
	3, // 7: neoline.v1.GetStatusOverviewResponse.groups:type_name -> neoline.v1.StatusGroup
	4, // 8: neoline.v1.StatusService.GetStatusOverview:input_type -> neoline.v1.GetStatusOverviewRequest
	5, // 9: neoline.v1.StatusService.GetStatusOverview:output_type -> neoline.v1.GetStatusOverviewResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_neoline_v1_status_proto_init() }
func file_neoline_v1_status_proto_init() {
	if File_neoline_v1_status_proto != nil {
		return
	}
	file_neoline_v1_monitor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neoline_v1_status_proto_rawDesc), len(file_neoline_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neoline_v1_status_proto_goTypes,
		DependencyIndexes: file_neoline_v1_status_proto_depIdxs,
		MessageInfos:      file_neoline_v1_status_proto_msgTypes,
	}.Build()
	File_neoline_v1_status_proto = out.File
	file_neoline_v1_status_proto_goTypes = nil
	file_neoline_v1_status_proto_depIdxs = nil
}
